Handling new datapass archive and revoke event
etalab/admin_api_entreprise pull request #1011
Opened 2023-04-17 13:18 UTC by Un3x

closes #382

Blacklist current authorization request token on revoke event Delete current authorization request token on archive event if token is not blacklisted
Archive current authorization request token on archive event if token is blacklisted

2023-04-17 13:21 UTC, Un3x commented
Petit disclaimer ici, 
Il y a un point d'incertitude sur le devs réalisé.

Actuellement, une authorization request peut avoir plusieurs token, or nous on va chercher le premier token de l'authorization request.

Le token concerné suit la règle suivante : 
* Soit il y a un token actif et on le prend
* Soit on prend le 1er token trouvé.

Dans le cas où le webhook concerne le token inactif ca ferait du caca
Dans le cas où le webhook concerne un token inactif et qu'on ai plusieurs token inactif cela ferait du caca.

J'ai pas digué parce que je ne sais pas si ces cas peuvent arrivé et que c'est juste des traitements supplémentaire. 

Probablement besoin de l'avis de @Haelle, @skelz0r et/ou @Samuelfaure là dessus.

2023-04-17 13:52 UTC, skelz0r requested changes
Je pense que je n'ai pas été assez clair sur l'issue.
Ce que je propose est:

* Si une demande n'a jamais été validée et est archivée -> on supprime tout ;
* Si une demande a été validée et est révoquée -> on blacklist les jetons (à noter que blacklister les jetons ici ne suffit pas, il faut aussi les propager sur le serveur, donc je préconise de nous shoote run email pour blacklister les jetons) ;
* Si une demande a été révoquée et est archivée -> on ne fait rien.

A noter que par design, vu qu'on ne peut pas archivée une demande validée (il faut la révoquée à un moment), on ne peut pas supprimer une demande qui a un moment ou un autre été validée.

A la lumière des infos ci-dessus:

* A aucun moment on ne doit supprimer de jeton
* Il n'y a pas de suppression de demande dans ce code

D'ailleurs, histoire d'être clair je ferai une méthode `revoke!` sur les demandes, qui iront blacklister les jetons (et nous notifier au passage).
Et pour le archive, si la demande n'a pas été révoquée -> un bon gros `destroy` (et non `delete`, c'est à proscrire en rails).

2023-04-17 16:44 UTC, Un3x commented
Oui ok j'ai été un peu rapide là dessus.

Je veux bien éclaircir l'information "on supprime tout". 
C'est quoi le scope de tout ? Genre je supprime les scopes, + token + authorization request ? J'imagine que c'est ca que tu entends par 'tout'.

C'est quoi un token qui a déjà été validé ? Pour moi les token non blacklist, non archivé et non expiré sont les tokens 'actifs' et donc validé. J'ai l'impression que ca sous entend d'autres cas que ceux cité plus haut, mais aucune idée de comment avoir cette information.

> A aucun moment on ne doit supprimer de jeton

A la lumière de ce que tu dis plus haut, ce message génère une très haute confusion de ma part.

Ok pour le reste

2023-04-17 17:28 UTC, skelz0r commented
> Je veux bien éclaircir l'information "on supprime tout".
> C'est quoi le scope de tout ? Genre je supprime les scopes, + token + authorization request ? J'imagine que c'est ca que tu entends par 'tout'.

En fait tout c'est la demande DataPass seulement. Si il y a des dépendances à supprimer, celles-ci sont définies dans le modèle (typiquement les contacts vont se détruire si on détruit la demande, car les contacts sont seulement associé à cette demande). Ça se définit à l'aide du `dependent: :destroy` sur les associations.

> C'est quoi un token qui a déjà été validé ? Pour moi les token non blacklist, non archivé et non expiré sont les tokens 'actifs' et donc validé. J'ai l'impression que ca sous entend d'autres cas que ceux cité plus haut, mais aucune idée de comment avoir cette information.

En fait, y'a pas de notion de token validé : il y a des demandes validées. 
La validation d'une demande crée un jeton.
Quand une demande est validée, à priori elle ne va pas plus loin. Elle peut seulement être révoquée.

En gros mon point de "supprimer une demande", c'est supprimé une demande qui n'a jamais dépassé le stade de la validation, et qui n'a donc in-fine aucune raison de terminer sur le backoffice, qui gère uniquement les jetons. La source d'autorité des demandes reste DataPass.

2023-04-18 08:58 UTC, Un3x commented
Ok du coup en bilan.

On attend la fin du dev de @Samuelfaure  sur le merge des contacts et des users.

Ensuite on mets en place : 


* Si une demande n'a jamais été validée et est archivée, on supprime tout
* Si une demande a été validée et est révoquée, on blacklist les jetons
* Si une demande a été révoquée et est archivée, on ne fait rien

On identifie une `authorization_request` validée par <je sais toujours pas>
On supprime tout -> Suppression de l'`authorization_request` associée au call

Lors du blacklist des jetons, il faudra propager sur le serveur le blacklisting des jetons, cette opération doit être fait manuelle, et à ce titre, un email devra être envoyé à <insérer l'email ici> afin de notifier le blacklisting des jetons. 

L'email devra à minima contenir les critère d'identification de l'ensemble des jetons blacklistés qui sont : <son id je suppose>.
Peut être rappeler la procédure de blacklisting du jetons dans l'email, ou une ref vers l'endroit où la trouver.

Tout le monde valide @Samuelfaure @skelz0r @Haelle ?

2023-05-16 08:30 UTC, Un3x commented
Oula, à mon avis il faut reprendre toute la PR.
On voulait attendre la fin du travail de sam pour continuer sur ce travail, mais du coup là faut tout refaire + corriger, je pense que ce qui a été fait ne correspond pas à mon dernier commentaire

2023-09-01 09:44 UTC, closed without merging