feat(MailjetContact): async job to remotly create new entries
etalab/admin_api_entreprise pull request #113
Opened 2021-05-03 18:08 UTC by cyril

# Création vers Mailjet des nouveaux contacts

Proposition de code pour permettre, chaque jour, de mettre à jour la base de données Mailjet en lui soumettant nos nouveaux contacts.

Je pense qu'on peut être plus précis dans la construction des paramètres (= attributs Mailjet) que nous envoyons à Mailjet, mais si nous partons sur cette base, nous pourrons en ajouter et les affiner.

Tout est dans l'opération `Create`, y compris le client HTTP. Pour info il y a bien une gem officielle de Mailjet mais elle n'a pas fonctionné (retours 404 à chacune de mes requêtes, étrangement).

Je me suis permis de mettre des fichiers dotenv pour mes tests. J'ai mis une issue pour en parler si vous le souhaitez ici : https://github.com/etalab/admin_api_entreprise/issues/112. Si besoin je peux en faire une PR pour séparer. Sinon je supprime et remplace par une autre méthode (fichier YAML + ansible si je me trompe pas).

J'ai mis cette PR en draft, n'hésitez pas pour les retours.

2021-05-04 07:24 UTC, skelz0r commented
Vu la basecode je préfère faire un commentaire global:

1. Concernant le .env, mon avis (décorellé de la PR): il ne faut pas faire les choses à moitié => soit on suit le README (qui précise d'aller chercher la master key du ansible), soit on migre tout. Mon sentiment: en test/dev ça me semble plus simple/logique de faire du dotenv et de chiffrer uniquement la prod. Ici t'as le process dans le README pour utiliser le système actuel, c'est du [custom credentials](https://edgeguides.rubyonrails.org/security.html#custom-credentials)
2. Ton opération devrait être split en au minimum 2 opérations: retrieve et update (et potentiellement retrieve/build/update)
3. Étrange que tu n'arrives pas à faire fonctionner Mailjet, c'est bien cette gem que tu utilises https://github.com/mailjet/mailjet-gem ? Je pense que tu devrais plus creuser l'affaire

2021-05-04 07:25 UTC, skelz0r reviewed
Vu la basecode je préfère faire un commentaire global:

1. Concernant le .env, mon avis (décorellé de la PR): il ne faut pas faire les choses à moitié => soit on suit le README (qui précise d'aller chercher la master key du ansible), soit on migre tout. Mon sentiment: en test/dev ça me semble plus simple/logique de faire du dotenv et de chiffrer uniquement la prod. Ici t'as le process dans le README pour utiliser le système actuel, c'est du [custom credentials](https://edgeguides.rubyonrails.org/security.html#custom-credentials)
2. Ton opération devrait être split en au minimum 2 opérations: retrieve et update (et potentiellement retrieve/build/update)
3. Étrange que tu n'arrives pas à faire fonctionner Mailjet, c'est bien cette gem que tu utilises https://github.com/mailjet/mailjet-gem ? Je pense que tu devrais plus creuser l'affaire

2021-05-04 08:17 UTC, brindu commented
Mon avis concernant le dotenv est que ça n'a rien à faire dans cette PR. Et comme le dit @skelz0r dans tous les cas ne pas le mettre à côté de tout le reste...

Ce n'est pas pour rien que j'ai encrypté le fichier de variable en dev : il y a le _client secret_ pour interagir avec l'OAuth API Gouv qui ne peut pas être public. Si on fait ce que tu proposes il faudra toujours aller chercher des infos dans le Ansible pour l'environnement de dev. Je n'y vois personnellement pas de gains mais dans tous les cas ça n'a rien à faire dans cette PR de feature.

2021-05-05 07:44 UTC, cyril commented
> Ton opération devrait être split en au minimum 2 opérations: retrieve et update (et potentiellement retrieve/build/update)

Okay, si je comprends bien tu veux dire :

1. déjà je prends la liste des contacts Mailjet
2. je la compare avec la liste que nous avons dans la base
3. j'envoie les nouveaux contacts qui ne sont pas encore sur Mailjet vers Mailjet

Tu préfères plutôt comme ça ? Dans le code actuelle j'avais mis une fenêtre de 24h, mais on peut changer.

> Étrange que tu n'arrives pas à faire fonctionner Mailjet, c'est bien cette gem que tu utilises https://github.com/mailjet/mailjet-gem ? Je pense que tu devrais plus creuser l'affaire

Le souci venait de la version de l'API Mailjet, en downgradant de 3.1 vers 3 maintenant ça fonctionne. J'ai mis le code à jour.

2021-05-05 08:03 UTC, skelz0r commented
Mon point sur le split de ton code est surtout pour respecter SRP : 1 responsabilité / classe. Au passage le naming n'est pas bon, ta classe s'appelle `MailjetContact::Operation::Create`, on comprends que ça créer un contact mailjet.

Ce que je propose c'est que tu décomposes au moins de cette manière:

1. Retrieve : sortir les contacts
2. Update : update le(s) contact(s) sur mailjet

Après vu comment le code est architecturé (les opérations ont l'air d'être huge / limite god pattern), je sais pas trop quoi en penser (surtout que je crois que c'est pas basé sur la version "cool" de Trailblazer donc doit pas y avoir toutes les features)

Je te laisse avancer et je verrai la tête des tests.

Si tu veux voir/creuser un peu les concepts TrailBlazer en 1 one pager: http://2019.trailblazer.to/2.1/tutorials/activity.html#tutorials-railway-basics

2021-05-05 08:12 UTC, cyril commented
> Au passage le naming n'est pas bon, ta classe s'appelle `MailjetContact::Operation::Create`, on comprends que ça créer un contact mailjet.

Oui, c'est tout à fait ça tu as bien compris.

Pas sûr de comprendre ce que tu entends pas "sortir les contacts".

Est-ce que tu veux dire plutôt ça ?

1. déjà je prends la liste des contacts Mailjet
2. je la compare avec la liste que nous avons dans la base
3. j'envoie les nouveaux contacts qui ne sont pas encore sur Mailjet vers Mailjet

2021-05-05 08:23 UTC, skelz0r commented
> > Au passage le naming n'est pas bon, ta classe s'appelle `MailjetContact::Operation::Create`, on comprends que ça créer un contact mailjet.
> 
> Oui, c'est tout à fait ça tu as bien compris.

De ce que je comprends du code tu prends les contacts crée dans les dernières 24h et tu créer des contacts sur mailjet (et non un contact). Un meilleur naming pour cette classe serait à mon sens (un truc du genre): `CreateLastDayContactsOnMailjet` (si on joue avec les namespaces on aurait un truc du genre `Mailjet::Operation::CreateLastDayContacts`)

Après ma remarque sur le code était surtout sur potentiellement faire plusieurs classes (i.e. 2 opérations `Users::Operation::RetrieveLastDayContacts` et `Mailjet::Operation::UpdateContacts` séquencées dans la première mais peut-être overkill 🤷), mais comme je disais avance je verrai les tests.

2021-05-05 10:52 UTC, cyril commented
> De ce que je comprends du code tu prends les contacts crée dans les dernières 24h et tu crées des contacts sur mailjet (et non un contact).

Oui, c'est bien ça.

> Un meilleur naming pour cette classe serait à mon sens (un truc du genre): CreateLastDayContactsOnMailjet (si on joue avec les namespaces on aurait un truc du genre Mailjet::Operation::CreateLastDayContacts)

J'ai mis le module au pluriel, mais si ce n'est pas suffisamment clair on peut encore changer.

> Après ma remarque sur le code était surtout sur potentiellement faire plusieurs classes (i.e. 2 opérations Users::Operation::RetrieveLastDayContacts et Mailjet::Operation::UpdateContacts séquencées dans la première mais peut-être overkill shrug), mais comme je disais avance je verrai les tests.

Okay. Les tests sont très légers, comme le code, mais ils suffisent je pense.

2021-05-11 09:13 UTC, skelz0r commented on app/concepts/mailjet_contacts/operation/create.rb
> +          'nom': nil,                 # String
pourquoi ce n'est pas rempli ?

2021-05-11 09:13 UTC, skelz0r commented on app/concepts/mailjet_contacts/operation/create.rb
> +          'prénom': nil,              # String
pourquoi ce n'est pas rempli ?

2021-05-11 09:14 UTC, skelz0r commented on spec/concepts/mailjet_contact/operation/create_spec.rb
> +RSpec.describe MailjetContacts::Operation::Create do
Il manque pas mal de tests non ?

2021-05-11 13:25 UTC, cyril commented on app/concepts/mailjet_contacts/operation/create.rb
> +      users_relation.find_each do |user|
👍🏽

2021-05-11 13:32 UTC, cyril commented on app/concepts/mailjet_contacts/operation/create.rb
> +          'prénom': nil,              # String
Là non plus, nous ne possédons pas en base cette info pour le moment.

2021-05-11 13:34 UTC, cyril commented on spec/concepts/mailjet_contact/operation/create_spec.rb
> +RSpec.describe MailjetContacts::Operation::Create do
Je viens de renseigner dans la spec la structure d'info que nous retournons dans le scénario utilisé. Si tu as d'autres points important à vérifier, n'hésite pas à me dire. Tu voudrais que nous testions unitairement chaque step de l'opération ?

2021-05-11 13:42 UTC, skelz0r commented on spec/concepts/mailjet_contact/operation/create_spec.rb
> +RSpec.describe MailjetContacts::Operation::Create do
> Au passage tu pourrais clarifier tes 3 create(:contact) dans des let avec des noms plus explicite pour qu'on comprenne ce qu'ils font là (typiquement je me demande pourquoi le contact tech est en premier et les 2 autres derrière 🤷)

Mieux: une factory avec un trait me semble plus adapté.

2021-05-11 13:43 UTC, skelz0r commented on app/concepts/mailjet_contacts/operation/create.rb
> +          'default': nil,             # String
Vu qu'il y a un compact à la fin ça n'a en effet aucun intérêt à être là.

2021-05-11 13:47 UTC, cyril commented on app/concepts/mailjet_contacts/operation/create.rb
> +        serialized_properties[:'contact_demandeur'] = user.contacts.map(&:contact_type).include?('other')
Yes. J'avais bien compris ce que tu veux dire.

Mais dans mon code, les clés sont toutes des symboles. Il n'y a aucune chaîne de caractères. Donc aucune duplication avec des clés comme "`ok`" et `:ok`.

Exemple :

```ruby
h = { 'techlettre': nil } # => {:techlettre=>nil}
h[:'techlettre'] = true
h # => {:techlettre=>true}
```

2021-05-11 13:50 UTC, cyril commented on app/concepts/mailjet_contacts/operation/create.rb
> +          'prénom': nil,              # String
Ref : https://github.com/etalab/admin_api_entreprise/pull/113#discussion_r630185666

2021-05-11 13:51 UTC, skelz0r commented on app/concepts/mailjet_contacts/operation/create.rb
> +        serialized_properties[:'contact_demandeur'] = user.contacts.map(&:contact_type).include?('other')
Wow ok en effet, j'avais jamais vu cette écriture c'est clairement brainfuck d'avoir un string qui se transforme en symbol.

2021-05-11 13:56 UTC, skelz0r commented on app/concepts/mailjet_contacts/operation/create.rb
> +          'nom': nil,                 # String
Ok. Doit y avoir un moyen de renseigner ça de manière à ce que ça ne soit pas "brainfuck" (je vois ça je scout commit le code perso) : peut-être dans le message de commit ?

2021-05-11 14:19 UTC, cyril commented on app/concepts/mailjet_contacts/operation/create.rb
> +          'nom': nil,                 # String
Ça me va, je mets l'info dans le commit.

2021-05-11 14:37 UTC, skelz0r commented on app/concepts/mailjet_contacts/operation/create.rb
> +          origine:            'dashboard',
C'est pas plutôt `datapass` ?

2021-05-11 14:42 UTC, skelz0r commented on spec/concepts/mailjet_contact/operation/create_spec.rb
> +      expect(Mailjet::Contactslist_managemanycontacts).to receive(:create).with(
un `expect` dans un `before` ? 😬

2021-05-11 14:45 UTC, skelz0r commented on spec/concepts/mailjet_contact/operation/create_spec.rb
> +    create(:contact, :tech, jwt_api_entreprise: jwt_api_entreprise)
C'est un peu plus clair mais pas tant que ça je trouve.

2021-05-11 14:49 UTC, skelz0r commented on spec/concepts/mailjet_contact/operation/create_spec.rb
> +RSpec.describe MailjetContacts::Operation::Create do
Bon, c'est un peu mieux, mais ça reste insuffisant je trouve.

1. On ne décrit pas explicitement ce qu'on renvoi en fonction des contacts dispo
2. On ne précise pas qu'on appelle Mailjet (ton `expect` est dans un `before` ..?)

Fonctionnellement (un truc du genre, qui est très succinct et minimal)

```ruby
context 'with a user which has only a tech contact' do
  it { is_expected.to be_a_success }

  it 'calls Mailjet API with contact_demandeur as false, contact_technique as true, contact_métier as false'
end
```

Et tu déclines pour traduire le comportement fonctionnel de ta classe.

Au passage avec une approche pareil on se rend vite compte que ça devient un casse tête à tester, et que ça mérite potentiellement un refactor.

2021-05-11 15:47 UTC, cyril commented on spec/concepts/mailjet_contact/operation/create_spec.rb
> +    create(:contact, :tech, jwt_api_entreprise: jwt_api_entreprise)
Je n'ai pas modifié cette ligne.

2021-05-11 17:06 UTC, skelz0r commented on app/concepts/mailjet_contacts/operation/create.rb
> +          origine:            'dashboard',
Ok soit

2021-05-11 17:08 UTC, skelz0r commented on app/concepts/mailjet_contacts/operation/create.rb
> +        serialized_properties = {
> > ça se refactor
> 
> Dans une PR précédente, j'avais cru comprendre que la Trailblazer-way c'était surtout d'utiliser une méthode par step, mais découper comme tu le proposes ça ne m'embête pas.

Ça n'empêche pas d'utiliser des méthodes privées pour clarifier le code.

> > D'ailleurs ce ctx[:serialized_contacts].any? est-t'il nécessaire ? Vu qu'on ne fait aucun filtrage à cette étape, et que ce filtrage existe déjà à la fin de la première step ?
> 
> Pas nécessaire, et on pourrait certainement faire autre chose que `ctx[:serialized_contacts].any?`, mais en tout cas je préfère retourner `true` plutôt qu'un array pour dire à Trailblazer que l'étape s'est bien déroulée. C'est plus explicite.

Je t'avoue que je ne sais pas, ça me choque pas c'était une question que je me posais.

2021-05-12 09:36 UTC, cyril commented on spec/concepts/mailjet_contact/operation/create_spec.rb
> +RSpec.describe MailjetContacts::Operation::Create do
Le refactor bien mérité vient d'arriver. Je te laisse regarder.

2021-05-12 09:39 UTC, cyril commented on app/concepts/mailjet_contacts/operation/create.rb
> +        serialized_properties = {
C'est une bonne question. Je me rends compte que cette étape intermédiaire n'a pas de sens, et je l'ai fusionné dans la première. Pour réduire la complexité, j'ai ajouté dans lib une classe dont la responsabilité est de mapper les propriétés. Je l'ai testé unitairement. Ses tests sont un peu redondant avant ceux de l'opération, donc nous pourrions aussi les effacer (les tests de la lib ajouté).

2021-05-12 09:46 UTC, cyril commented on spec/concepts/mailjet_contact/operation/create_spec.rb
> +      expect(Mailjet::Contactslist_managemanycontacts).to_not receive(:create)
En l'état, les deux tests ne sont pas indépendant (car l'un mock l'appel réseau).

Je peux découper en 2 tests distincts en utilisant une cassette ceci dit, mais ça alourdirait la spec inutilement, à mon avis.

2021-05-12 10:06 UTC, skelz0r requested changes
Cf mes retours.

2021-05-12 10:06 UTC, skelz0r commented on spec/concepts/mailjet_contact/operation/create_spec.rb
> +    context 'when the contact is tech' do
Vu que tu testes déjà les types de contacts dans le test de la lib, je me serai pas du tout pris la tête. J'aurais seulement testé:

1. Que ça appelle le builder avec les bons arguments
2. Que ça passe la payload du builder à Mailjet

Et tout ça indépendamment de l'implémentation du builder. On travaille donc en isolation.

Si tu veux faire plus high level/tester toute la chaine sans stubbing (ce que je peux entendre) j'en ferai qu'un.

2021-05-12 10:06 UTC, skelz0r commented on lib/mailjet/property_builder.rb
> +  class PropertyBuilder
`Mailjet::PropertiesBuilder` au moins (on ne construit pas une propriété mais plusieurs propriétés)
J'aurais tendance plus à coller à la nomenclature de Mailjet ici -> `Mailjet::ContactPropertiesBuilder`
Et enfin, c'est certes un builder, mais ça ressemble plus à un adapter à mon sens -> `Mailjet::ContactPropertiesAdapter`

Au choix suivant l'intention que tu veux traduire, mais en tout cas `Property` au singulier c'est faux à mon sens.

2021-05-12 10:06 UTC, skelz0r commented on spec/concepts/mailjet_contact/operation/create_spec.rb
> +    context 'when the contact is tech' do
Mon commentaire plus bas sur les N types de contact est valide aussi ici.

2021-05-12 10:08 UTC, skelz0r commented on spec/concepts/mailjet_contact/operation/create_spec.rb
> +      expect(Mailjet::Contactslist_managemanycontacts).to_not receive(:create)
> En l'état, les deux tests ne sont pas indépendant (car l'un mock l'appel réseau).

Une approche possible:

```ruby
before do
  allow(WhateverClass).to receive(:method).and_return(whatever)
end

it { is_expected.to be_a_success }

it 'calls WhateverClass with valid params' do
  subject

  expect(WhateverClass).to have_receive(:method).with(whatever)
end
```

2021-05-12 13:28 UTC, cyril commented on lib/mailjet/property_builder.rb
> +      raise ::TypeError, user.class.inspect unless user.is_a?(::User)
Ce n'était pas une nécessité, je l'ai enlevé.

2021-05-12 13:29 UTC, cyril commented on config/initializers/mailjet_property_builder.rb
> +require_relative '../../lib/mailjet/property_builder'
J'utilise plutôt require pour les gem. Lorsque je suis dans un fichier, je préfère les chemins relatifs.

2021-05-12 13:30 UTC, cyril commented on spec/lib/mailjet/property_builder_spec.rb
> +  context 'when the contact is tech' do
J'ai clarifié le wording et réécrit les tests pour vérifier le comportement sans contacts, et avec plusieurs. Sans chercher à tout tester non plus.

2021-05-12 13:31 UTC, cyril commented on spec/concepts/mailjet_contact/operation/create_spec.rb
> +    context 'when the contact is tech' do
Oui, c'est ce que je disais dans mon commentaire. J'en ai profité pour alléger cette spec.

2021-05-12 13:32 UTC, skelz0r commented on config/initializers/mailjet_property_builder.rb
> +require_relative '../../lib/mailjet/property_builder'
Cela reste peu conventionnel. Je me demande même si c'est nécessaire de faire un quelconque require en rails 6.

D'ailleurs je me rends compte qu'il y a un `app/lib` dans l'app, autant le coller là et retirer les require pour profiter de l'autoload.

2021-05-12 13:44 UTC, cyril commented on config/initializers/mailjet_property_builder.rb
> +require_relative '../../lib/mailjet/property_builder'
En fait c'est pas si non conventionnel que ça. Tout dépend des projets sur lesquels tu as bossé et de leur base de code :) Moi c'est plutôt voir le dossier lib/ dans le dossier app/ que je trouve peu conventionnel. On pourra challenger ça plus tard, c'est bon à savoir. J'ai déplacé le fichier en attendant.

2021-05-12 13:51 UTC, skelz0r commented on config/initializers/mailjet_property_builder.rb
> +require_relative '../../lib/mailjet/property_builder'
> En fait c'est pas si non conventionnel que ça. Tout dépend des projets sur lesquels tu as bossé et de leur base de code :)

En rails, avec l'autoload activé, mettre un require pour tout autre chose qu'une gem est un code smell à mon sens.

> Moi c'est plutôt voir le dossier lib/ dans le dossier app/ que je trouve peu conventionnel.

Oui je te l'accorde, mais c'est là donc autant l'utiliser.

2021-05-12 14:04 UTC, skelz0r approved these changes
C'est OK pour moi. Merci d'avoir pris en compte les retours ;)

2021-05-12 14:11 UTC, cyril commented
@skelz0r C'est moi qui te remercie pour ton temps et ta réactivité.

2021-05-12 14:11 UTC, merged