Particulier/manage contacts datapass
etalab/admin_api_entreprise pull request #1158
Opened 2023-08-03 11:10 UTC by Samuelfaure

fix https://linear.app/pole-api/issue/API-571/nourrir-automatiquement-la-nouvelle-mailing-list

2023-08-07 12:02 UTC, skelz0r requested changes
Pour moi les 2 derniers commits n'ont rien à faire dans le scope de cette PR, qui si j'ai bien compris s'occupe uniquement d'alimenter une ML.
Concernant le 3e commit en partant de la fin, j'ai mis un commentaire.

imo focus sur l'alimentation de la ML, le schedule du reste on verra plus tard (surtout que je suis quasiment sûr que ça ne fonctionnera pas/est du code mort)

2023-08-07 12:02 UTC, skelz0r commented on app/organizers/datapass_webhook/api_particulier.rb
> +      ::DatapassWebhook::ScheduleAuthorizationRequestEmails
```suggestion
      ::DatapassWebhook::UpdateMailjetContacts
```

2023-08-07 13:00 UTC, Samuelfaure commented
Commits séparés dans la PR suivante: https://github.com/etalab/admin_api_entreprise/pull/1161

2023-08-07 13:04 UTC, skelz0r commented
Ce n'est pas la réalité du terrain actuellement, je pense que tu devrais quand même faire sans maintenant quitte à l'introduire par la suite. (cc @Haelle)

Et en plus ça se trouve ça va marcher out of the box tout de suite 🤷

2023-08-08 08:15 UTC, Samuelfaure commented
@skelz0r Ajouté un test dans le dernier commit, ça semble marcher out-of-the-box, ça te semble correct?

2023-08-08 08:22 UTC, Samuelfaure commented
J'hésite aussi à rajouter un test pour vérifier que y'a bien aucun contact métier et que ça marche quand même (au cas ou les factories changent et ajoutent un contact métier par défaut):

```ruby
    it 'updates accordingly despite no contact_metier' do
      expect(authorization_request.contact_metier).to be_nil

      expect(Mailjet::Contactslist_managemanycontacts).to receive(:create).with(
        hash_including(
          id: anything,
          action: 'addnoforce',
          contacts: [
            {
              email: authorization_request.demandeur.email,
              properties: hash_including(
                'contact_demandeur' => true,
                'contact_technique' => false
              )
            },
            {
              email: authorization_request.contact_technique.email,
              properties: hash_including(
                'contact_demandeur' => false,
                'contact_technique' => true
              )
            }
          ]
        )
      )

      subject
    end
```

2023-08-08 08:28 UTC, Un3x approved these changes
Techniquement c'est ok pour moi, mais je sais que je manque de "culture" sur ce que devrait contenir un webhook ou non. Donc ok modulo les retours métier associé à la PR,

Du coup, qu'est ce qui fait que dans api particulier on a pas de contact métier ? Je suis pas sur de bien piger la raison.

2023-08-08 08:33 UTC, skelz0r requested changes
Il ne doit y avoir aucune trace de `contact_metier` pour API Particulier.

2023-08-08 08:33 UTC, skelz0r commented on spec/interactors/datapass_webhook/update_mailjet_contacts_spec.rb
> +              properties: hash_including(
je pense qu'ici il faut vérifier que c'est exactement ce hash.

si tu fais ça il faudra modifier la classe associé pour ne pas inclure `contact_metier`

2023-08-08 08:33 UTC, skelz0r commented on spec/organizers/datapass_webhook/api_entreprise_spec.rb
> +                     properties: { 'contact_demandeur' => true,
cf mon com d'avant, tu as fait un match exact ici il faut le faire aussi pour API Part

2023-08-08 08:33 UTC, skelz0r commented on spec/organizers/datapass_webhook/api_particulier_spec.rb
> +      build(:datapass_webhook_team_member_model, type: 'contact_metier')
pourquoi ? justement ce n'est pas présent

2023-08-08 08:33 UTC, skelz0r commented on spec/organizers/datapass_webhook/api_particulier_spec.rb
> +  describe 'when contact metier is empty (non-regression test)' do
ce n'est pas vraiment un test de non régression ici, c'est tout le temps comme ça + c'est une nouvelle feature

2023-08-08 08:33 UTC, skelz0r commented on spec/organizers/datapass_webhook/api_particulier_spec.rb
> +                                   'contact_métier' => false,
c'est faux ceci fonctionnellement

2023-08-08 08:33 UTC, skelz0r commented on spec/support/shared_examples/datapass_webhooks.rb
> +  end
c'est faux fonctionnellement pour API Particulier, il ne faut justement pas que cela crée de contact métier

2023-08-08 08:35 UTC, skelz0r commented
> Du coup, qu'est ce qui fait que dans api particulier on a pas de contact métier ? Je suis pas sur de bien piger la raison.

Aucune idée, mais ce n'est pas vraiment important imo. Faut voir si on l'ajoute cc @Haelle

2023-08-08 08:45 UTC, Samuelfaure commented on spec/organizers/datapass_webhook/api_particulier_spec.rb
> +  describe 'when contact metier is empty (non-regression test)' do
C'est du code qui était déjà présent ici mais que j'ai refacto dans le 1er commit

2023-08-08 08:50 UTC, skelz0r commented on spec/organizers/datapass_webhook/api_particulier_spec.rb
> +  describe 'when contact metier is empty (non-regression test)' do
c'était en effet présent dans `spec/organizers/datapass_webhook/api_entreprise_spec.rb` où ça avait du sens, ça n'en n'a aucun dans ce fichier, il faut à mon sens le supprimer

2023-08-10 09:56 UTC, Samuelfaure commented
Disjonction effectuée dans le commit https://github.com/etalab/admin_api_entreprise/pull/1158/commits/19d0de0ba76ba1371ada9e4c1128e2c0d5d38a11

Je sépare du reste pour pouvoir revert plus tard

2023-08-10 11:03 UTC, skelz0r requested changes
Y'a encore de la simplification possible, notamment 2 méthodes que tu as modifié pour rien imo

2023-08-10 11:03 UTC, skelz0r commented on app/interactors/datapass_webhook/update_mailjet_contacts.rb
> +    contacts.push(mailjet_payload_for(:contact_metier)) if authorization_request.api == 'entreprise'
ce code est inutile car le contact n'existe pas, tu peux le retirer et revert tes changements sur la méthode `mailjet_contact_payloads`

2023-08-10 11:03 UTC, skelz0r commented on app/interactors/datapass_webhook/extract_mailjet_variables.rb
> +    variables.merge!(build_contact_payload(:contact_metier)) if authorization_request.api == 'entreprise'
ce code est inutile car le contact n'existe pas, tu peux le retirer et revert tes changements sur la méthode `build_common_mailjet_variables`

2023-08-10 11:03 UTC, skelz0r commented on spec/interactors/datapass_webhook/update_mailjet_contacts_spec.rb
> -              email: authorization_request.contact_metier.email,
en voyant cette modif je pense que tu peux harden l51 avec un `contain_exactly`

2023-08-10 11:03 UTC, skelz0r commented on spec/organizers/datapass_webhook/api_entreprise_spec.rb
> +  it 'create one contact metier' do
```suggestion
  it 'creates one contact metier' do
```

2023-08-10 11:03 UTC, skelz0r commented on spec/organizers/datapass_webhook/api_particulier_spec.rb
> -  it 'creates one demandeur' do
pour être sûr je vérifierai que ça ne crée pas de contact métier (c'est pas ultra clair)

2023-08-11 07:03 UTC, Un3x commented on spec/interactors/datapass_webhook/update_mailjet_contacts_spec.rb
> +        hash_including(
Vu la discussion je suppose que ici non plus on a pas besoin du hash_including

2023-08-11 08:13 UTC, skelz0r approved these changes

2023-08-11 08:17 UTC, merged