Feature/api 1077 fix catalogue
etalab/admin_api_entreprise pull request #1202
Opened 2023-09-01 12:38 UTC by Un3x

2023-09-01 12:56 UTC, Un3x commented
On pourrait chippoter sur la couleur choisi à la fois pour ce tag mais aussi pour le beta.

Du vert pour du "c'est prêt mais pas vraiment" c'est bizarre.
Du bleu pour du "c'est prêt et c'est fini" c'est bizarre.

Accessoirement, on a pas de display du badge déprécié dans la vue globale du catalogue, uniquement sur le détail, j'ai trouvé ca chelou mais je me suis dit que c'était intentionnel.

2023-09-01 13:12 UTC, skelz0r commented
Les dépréciés ne sont pas dans le catalogue

2023-09-03 08:25 UTC, Samuelfaure requested changes
Un petit changement IMO

Pour les couleurs et questions d'UX faudra valider avec notre désigneuse officielle©️

2023-09-03 08:25 UTC, Samuelfaure commented on app/helpers/endpoint_helper.rb
> +    end
Je serais partisan d'utiliser l'I18n pour les couleurs et le label. Quelque chose comme ça (syntaxe probablement fausse mais dans l'idée):

```
"<p class="fr-badge fr-badge--new fr-badge-#{I18n.t(endpoint.status.color)}">#{I18n.t(endpoint.status.label)}</p>".html_safe
```

Et coté config:

```
beta:
  label: "Version beta"
  color: "green-bourgeon"
```

(again ma syntaxe est probablement bidon)

2023-09-04 09:51 UTC, Un3x commented on app/helpers/endpoint_helper.rb
> +    end
On aurait un genre de `endpoint.status` qui renverrai le status (et qui du coup contiendrait le "if" pour renvoyer le bon status qu'on concatènrai pour avoir la bonne chaine du I18n qui n'est pas vraiment de la traduction.

En vrai je trouve ca assez smart, en revanche c'est pas du tout intuitif. 
IMO faut qu'on décide de ce qu'on fait avec ces status / labels au sens large avant de designé un truc un peu plus propre.

2023-09-05 10:03 UTC, Samuelfaure commented on app/helpers/endpoint_helper.rb
> +    end
On fait déjà ça dans l'app à plusieurs endroits, par exemple dans `app/helpers/scope_helper.rb`

Perso je suis partisan de cette solution, c'est intuitif quand on connait le trick imo

Je suis d'accord qu'il faut être fixé sur quels labels, couleurs on veut, c'est une décision qui implique au minimum @DorineLam qui sera dispo juste après le séminaire

A mon avis vaut mieux pas ship tant qu'on est pas sûrs

2023-09-05 10:07 UTC, skelz0r commented on app/helpers/endpoint_helper.rb
> +    end
Je plussoie le `status` (peut-être un autre nom ..? genre `pending_status`) + l'i18n, plus on exporte les wordings mieux c'est.

2023-09-05 13:24 UTC, Un3x commented on app/helpers/endpoint_helper.rb
> +    end
Fixed

2023-09-08 10:01 UTC, DorineLam commented
Coucou, merci de m'avoir attendue pour les couleurs.
On retire le vert, et on évite le rouge. Du coup je vous propose de : 
- garder le bleu pour nouveauté `fr-badge--blue-ecume`
- changer le vert par le purple (malheureusement un peu trop rose du DSFR) pour le beta `fr-badge--purple-glycine`
- garder le beige pour le prochainement 


Je ne sais pas si ça a sa place dans cette PR, mais ce serait chouette que les API sur lesquelles il y a un tag, soient automatiquement affichées en premier dans l'index.

2023-09-11 08:13 UTC, Un3x commented
![FireShot Capture 029 - API Entreprise - entreprise api localtest me](https://github.com/etalab/admin_api_entreprise/assets/9677688/b8d3d0dc-c5cb-43ea-9b27-a923aaddb832)

2023-09-11 08:50 UTC, Samuelfaure requested changes
J'ai 2 doléances

2023-09-11 08:56 UTC, Un3x commented on app/models/abstract_endpoint.rb
> +  end
Yes, mais là on est dans de l'activeModel. Ca n'existe pas.

2023-09-11 09:02 UTC, Un3x commented on app/controllers/api_entreprise/endpoints_controller.rb
> +      .sort { |endpoint1, endpoint2| helpers.order_by_position_or_status(endpoint1, endpoint2) }
Hmmm, du coup ca veut dire que dans le cas où on ajoute un status on a encore un nouvel endroit où il ne faut pas oublier de le rajouter ? 
IMO ca fait bcp entre le model + les traductions déjà

2023-09-11 09:04 UTC, Un3x commented on app/controllers/api_entreprise/endpoints_controller.rb
> +      .sort { |endpoint1, endpoint2| helpers.order_by_position_or_status(endpoint1, endpoint2) }
Et aussi, les endpoints sont déjà trié par position dans le EndpointStore pendant le loading.

2023-09-11 09:14 UTC, Samuelfaure commented on app/controllers/api_entreprise/endpoints_controller.rb
> +      .sort { |endpoint1, endpoint2| helpers.order_by_position_or_status(endpoint1, endpoint2) }
> Hmmm, du coup ca veut dire que dans le cas où on ajoute un status on a encore un nouvel endroit où il ne faut pas oublier de le rajouter ?

Non je pensais faire un truc similaire à ce que tu as dans `order_by_position_or_status(endpoint1, endpoint2)` avec de la métaprog simple, ou alors importer les valeurs depuis les traductions

après j'ai le cerveau cassé aujourd'hui donc je préfère attendre un peu avant de valider d'être sûr de pas avoir une meilleure idée qui vient, à moins que ça convienne à @skelz0r et dans ce cas on merge

2023-09-11 09:45 UTC, Un3x commented on app/controllers/api_entreprise/endpoints_controller.rb
> +      .sort { |endpoint1, endpoint2| helpers.order_by_position_or_status(endpoint1, endpoint2) }
Mouais, IMO on merge ca avant le retour de loic.
J'avoue que faire de la metaprog pour ca, pour le coup je trouve ca assez fucked up. J'ai un peu du mal à comprendre ce qui te semble compliqué dans ce qui est fait.

Après, ta solution aurait l'avantage de regrouper les éléments par tag ce que ma solution ne fait pas, ca je suis d'accord et c'est un vrai argument.

2023-09-11 10:02 UTC, Samuelfaure commented on app/controllers/api_entreprise/endpoints_controller.rb
> +      .sort { |endpoint1, endpoint2| helpers.order_by_position_or_status(endpoint1, endpoint2) }
En effet je viens de me rappeller que Loic est en vacances

Laisse moi jusqu'à demain voir si je trouve un truc un peu mieux et sinon osef on merge

2023-09-12 08:18 UTC, DorineLam commented on app/controllers/api_entreprise/endpoints_controller.rb
> +      .sort { |endpoint1, endpoint2| helpers.order_by_position_or_status(endpoint1, endpoint2) }
Cette issue à prendre en compte avant de merger.

2023-09-12 08:33 UTC, Un3x commented on app/controllers/api_entreprise/endpoints_controller.rb
> +      .sort { |endpoint1, endpoint2| helpers.order_by_position_or_status(endpoint1, endpoint2) }
Pour moi on merge même s'il y a une autre issue et on fait une autre PR pour l'autre issue.

2023-09-12 10:15 UTC, Samuelfaure commented on app/controllers/api_entreprise/endpoints_controller.rb
> +      .sort { |endpoint1, endpoint2| helpers.order_by_position_or_status(endpoint1, endpoint2) }
BTW j'ai toujours pas mieux donc OK pour valider pour moi

2023-09-12 12:42 UTC, merged