Feature/api 1069 revoir la page qui liste les jetons
etalab/admin_api_entreprise pull request #1244
Opened 2023-09-20 12:13 UTC by Un3x

Par rapport au ticket initial il reste ces questions à répondre : 

- Qu'est ce qu'on appelle le nom d'une administration ?
- Actuellement s'il n'y a pas de token actif, on affiche le plus 'récent'. Mais ils peuvent être archivé, expiré ou blacklisté. Est ce qu'on veut bien que ces 3 cas soient affiché ?
- Pour chacun de ces cas j'ai rajouté des badges pour que ce soit visible au user -> Est ce que ce sont les bonnes couleurs ? @DorineLam

2023-09-20 15:10 UTC, skelz0r commented
Je ne veux pas faire mon rabat-joie, mais ça ne devrait être une page à part spéciale éditeur : on les tag à la mano (ou avec un filtre sur un domain name) et on affiche une page différente en fonction ? Parce que ça risque d'être brainfuck pour les autres users non ?

2023-09-20 15:22 UTC, skelz0r requested changes
Cf mes coms.

Et sinon je ne comprends pas: tu as fait toutes les modifications pour API Entreprise mais l'issue est sur la migration API Particulier https://linear.app/pole-api/issue/API-1069/revoir-la-page-qui-liste-les-jetons

2023-09-20 15:22 UTC, skelz0r commented on app/models/authorization_request.rb
> +  def latest_expiration_token
`most_recent_token` ? (comme ce que t'as écrit dans ton test)

2023-09-20 15:22 UTC, skelz0r commented on app/models/authorization_request.rb
> +  scope :with_tokens_for, ->(api) { where(api:).joins(:tokens) }
Je ne suis pas fan de mettre ce `joins` sans `where` specifique, cela fait du load inutile de données.

Si c'est pour tirer les jetons dans une vue par exemple, c'est mieux de faire un truc du genre:

```ruby
# model 
scope :for_api, ->(api) { where(api:) }

# controller
AuthorizationRequest.for_api('particulier').includes(:tokens)
```

2023-09-20 15:22 UTC, skelz0r commented on app/controllers/api_entreprise/tokens_controller.rb
> +    @tokens = authorization_requests.map(&:token)
Ok donc je vois ce que tu veux faire, clairement pas le plus opti ce `with_token_for`, faut coller un scope sur `Token` ici et non `AuthorizationRequest`. L'interface devrait être ça imo:

```ruby
@tokens = current_user.tokens.for_api('entreprise')
```

2023-09-20 15:22 UTC, skelz0r commented on app/controllers/api_entreprise/tokens_controller.rb
> +    @tokens = authorization_requests.map(&:token).sort_by(&:exp).reverse
Ça se fait en full AR ici (sans scope):

```ruby
@tokens = Token.joins(:authorization_request).where(authorization_request: { api: 'entreprise' }).order(exp: :desc)
```

Ça peut mériter un scope btw

2023-09-20 15:22 UTC, skelz0r commented on app/views/api_entreprise/tokens/_token.html.erb
> +          <% end %>
indent ici pour que ca soit plus lisible, le rendu final html on s'en fiche vu qu'on le lit pas forcément

2023-09-20 15:22 UTC, skelz0r commented on app/views/api_entreprise/tokens/_token.html.erb
> +          <span class="fr-badge fr-badge--yellow-moutarde"> Expiré </span>
A déporter en i18n (idem pour les 3 du dessous)

2023-09-20 15:22 UTC, skelz0r commented on app/views/api_entreprise/tokens/_token.html.erb
> +        <p>
c'est DSFR friendly ce `p` ?

2023-09-20 15:22 UTC, skelz0r commented on app/controllers/api_entreprise/tokens_controller.rb
> +    datapass_id = params[:datapass]
Je pense comprendre ce que tu veux faire, mais clairement tu peux complètement simplifier ça avec 0 ligne de code: une ancre.

A noter que sur DataPass on stock l'id du jeton, donc on peut aussi envoyer un `token_ID` et coller cette ancre partout => `compte#token_id` et ça focus dessus.

2023-09-21 07:02 UTC, Un3x commented
> Cf mes coms.
> 
> Et sinon je ne comprends pas: tu as fait toutes les modifications pour API Entreprise mais l'issue est sur la migration API Particulier https://linear.app/pole-api/issue/API-1069/revoir-la-page-qui-liste-les-jetons

You are all right. J'avoue que le phrasing du ticket m'a fait comprendre qu'il fallait rajouter les éléments à la page existante. Donc c'est ce que j'ai fais en step 1.
Après, je ne sais effectivement pas s'il faut rajouter cette page côté api-particulier, j'ai posé la questions à @Haelle dans le ticket mais j'ai pas vraiment eu de réponse so far.
J'ai fais ce qui me semblait faisable en attendant la réponse.

> Je ne veux pas faire mon rabat-joie, mais ça ne devrait être une page à part spéciale éditeur : on les tag à la mano (ou avec un > filtre sur un domain name) et on affiche une page différente en fonction ? Parce que ça risque d'être brainfuck pour les autres users non ?

Don't know. Je ne suis pas sûr de comprendre ce qui va être brainfuck pour les autres users. Cette page existe déjà, et limite le contenu est moins clair qu'aujourd'hui.

2023-09-21 07:06 UTC, Un3x commented on app/controllers/api_entreprise/tokens_controller.rb
> +    @tokens = authorization_requests.map(&:token)
J'avais fais qqchose comme ca au début. 
Mais je ne suis pas sur que ce soit beaucoup mieux.

La méthode `token` de `authorization_request` c'est pas juste yolo on va fetch un token. Elle va chercher un `active_token` et sinon le token avec la date d'expiration la plus lointaine (passé / futur).

2023-09-21 07:10 UTC, Un3x commented on app/models/authorization_request.rb
> +  def latest_expiration_token
Tu as identifié mon struggle de naming sur cette variable GG !

2023-09-21 07:27 UTC, Un3x commented on app/controllers/api_entreprise/tokens_controller.rb
> +    @tokens = authorization_requests.map(&:token).sort_by(&:exp).reverse
Same remarque sur la méthode token qu'au dessus.

2023-09-21 07:35 UTC, skelz0r commented on app/models/authorization_request.rb
> +  scope :with_tokens_for, ->(api) { where(api:).joins(:tokens) }
Dans le cadre de ce commit ce n'est pas un problème.

Sinon oui on peut avoir des demandes sans jeton, car on les sauvegarde dès leur sauvegarde côté DataPass.

2023-09-21 07:39 UTC, skelz0r commented on app/controllers/api_entreprise/tokens_controller.rb
> +    @tokens = authorization_requests.map(&:token)
Tu veux sortir quoi exactement ? Parce que l'ancien code me parait correct d'un point de vue fonctionnel:

```ruby
scope :active, -> { not_blacklisted.not_archived.unexpired }
scope :active_for, ->(api) { active.joins(:authorization_request).where(authorization_request: { api: }).uniq }
```

2023-09-21 07:39 UTC, Un3x commented on app/models/authorization_request.rb
> +  scope :with_tokens_for, ->(api) { where(api:).joins(:tokens) }
L'équivalent moche serait 

`authorization_requests = current_user.authorization_requests.for_api('entreprise').includes(:tokens).select { |ar| ar.tokens.length.positive? }`

2023-09-21 07:39 UTC, skelz0r commented on app/controllers/api_entreprise/tokens_controller.rb
> +    @tokens = authorization_requests.map(&:token).sort_by(&:exp).reverse
Même réponse qu'au dessus, ça dépend ce que tu veux sortir exactement. A mon sens ici tu veux trier, chose qu'on peut faire (et doit) faire en sql.

2023-09-21 07:42 UTC, skelz0r commented
> > Cf mes coms.
> > Et sinon je ne comprends pas: tu as fait toutes les modifications pour API Entreprise mais l'issue est sur la migration API Particulier https://linear.app/pole-api/issue/API-1069/revoir-la-page-qui-liste-les-jetons
> 
> You are all right. J'avoue que le phrasing du ticket m'a fait comprendre qu'il fallait rajouter les éléments à la page existante. Donc c'est ce que j'ai fais en step 1. Après, je ne sais effectivement pas s'il faut rajouter cette page côté api-particulier, j'ai posé la questions à @Haelle dans le ticket mais j'ai pas vraiment eu de réponse so far. J'ai fais ce qui me semblait faisable en attendant la réponse.

Au pire on verra dans un second temps.

> > Je ne veux pas faire mon rabat-joie, mais ça ne devrait être une page à part spéciale éditeur : on les tag à la mano (ou avec un > filtre sur un domain name) et on affiche une page différente en fonction ? Parce que ça risque d'être brainfuck pour les autres users non ?
> 
> Don't know. Je ne suis pas sûr de comprendre ce qui va être brainfuck pour les autres users. Cette page existe déjà, et limite le contenu est moins clair qu'aujourd'hui.

Simple réflexion, ça me semble logique de faire un backend/vue différent pour les éditeurs. 
En l'état en effet ça change pas grand chose.
Après, j'ai une idée assez arrêtée sur les outils qu'on devrait déployer ici pour les éditeurs (i.e. une API) pour les forcer à faire une intégration clean.

2023-09-21 07:43 UTC, skelz0r commented on app/models/authorization_request.rb
> +  scope :with_tokens_for, ->(api) { where(api:).joins(:tokens) }
https://poe.com/s/SSQ02erBZWtoyOcPPMDU :}

2023-09-21 07:49 UTC, Un3x commented on app/views/api_entreprise/tokens/_token.html.erb
> +        <p>
aucune idée. Je sais même pas où se trouvent les règles. J'ai fais sauté au final

2023-09-21 07:57 UTC, Un3x commented on app/controllers/api_entreprise/tokens_controller.rb
> +    datapass_id = params[:datapass]
En effet, tout est déjà là.

Le format de la ref est `token_<token_id>`

2023-09-21 08:39 UTC, Un3x commented
Du coup, j'ai vu avec @Haelle,

On a décidé que ces modifications ne concernait que la page api entreprise (donc c'est bien au bon endroit).

Il y a un chantier d'uniformisation entreprise / particulier qui inclut aussi du travail UX et de visibilité selon les rôles. Donc je délègue ca à mon moi du futur

2023-09-21 08:58 UTC, Un3x commented on app/controllers/api_entreprise/tokens_controller.rb
> +    @tokens = authorization_requests.map(&:token)
Alors non pas tout à fait. 

Ce que je veux faire c'est sortir exactement 1 token par authorization request, ce token doit être un token actif s'il en existe un et sinon ce doit être le `most_recent_token`.

L'anciens code, ne me renvoie que les authorizations_request qui ont un token actif. I.e, on avait pas la visibilité sur les authorization_request qui n'avaient pas de token actif, et donc ils ne pouvaient pas faire une demande de renouvellement depuis l'interface et ne pouvais pas non plus voir que leur token était <blacklisted/archived/expired> (via chez nous).

2023-09-21 08:59 UTC, Un3x commented on app/controllers/api_entreprise/tokens_controller.rb
> +    @tokens = authorization_requests.map(&:token).sort_by(&:exp).reverse
Ici tu as autant de token qu'il en existe. On en veut qu'un seul par authorization_request, déterminer par la règle du dessus.

2023-09-21 09:08 UTC, skelz0r commented on app/controllers/api_entreprise/tokens_controller.rb
> +    @tokens = authorization_requests.map(&:token)
Dans ce cas là devrait-on pas plutôt lister toutes les demandes validées et leurs jetons associés ? 
En gros recycler `APIEntreprise::AuthorizationRequestsController#index` en incluant un params `status` et afficher tous les jetons ?
Pour moi la page qui liste les jetons devraient tous les lister, quitte à mettre des filtres en query param.

D'un point de vue UX je trouve ça plus logique d'avoir une page avec ses demandes et les jetons associés d'une part, et la liste de tous les jetons d'autre part, quitte à afficher des informations différentes en fonction de ce que l'on veut afficher.

Si on réfléchit d'un point de vue fonctionnel, on peut presque dire que l'index des jetons n'a pas vraiment d'intérêt, et qu'on devrait la flip et ne garder que la page des demandes, où l'on listerait les demandes (par ordre de status, validated_at desc), avec l'ensemble des jetons en sous-section de la demande (actif en premier, le reste en dessous imo on s'en fout ici).

2023-09-21 09:12 UTC, Un3x commented on app/controllers/api_entreprise/tokens_controller.rb
> +    @tokens = authorization_requests.map(&:token)
Alors oui IMO t'as raison.

Mais, comme là on vient de se dire avec @Haelle, que le chantiers d'unification api-entreprise/api-particulier allait impliquer de l'ux (pour ceux qui ont 100+ ar), du remaniement des pages, de l'uniformisation, des critères d'affichage selon les roles.

Je pense que changer ca maintenant alors que je vais tout changer dans 3 semaines c'est pas opti. 

Je t'avoue que le sujet aurait été mis sur la table plus tôt, j'aurais pas fait ce ticket et je l'aurais delayed à après les discussions.

2023-09-21 09:16 UTC, skelz0r commented on app/controllers/api_entreprise/tokens_controller.rb
> +    @tokens = authorization_requests.map(&:token)
On peut couper la poire en deux et sortir sur la page des jetons tous les jetons ordonnés par `status, validated_at desc` (et pourquoi pas `exp desc` mais imo c'est inclut dans le couple précédent), ça simplifie le code, et surtout je pense que ça change rien pour les éditeurs en l'état (et dtf on change dans 3 semaines comme t'as dit).

2023-09-21 09:22 UTC, skelz0r commented on app/controllers/api_entreprise/tokens_controller.rb
> +    @tokens = authorization_requests.map(&:token)
Et d'ailleurs

> L'anciens code, ne me renvoie que les authorizations_request qui ont un token actif. I.e, on avait pas la visibilité sur les authorization_request qui n'avaient pas de token actif, et donc ils ne pouvaient pas faire une demande de renouvellement depuis l'interface et ne pouvais pas non plus voir que leur token était <blacklisted/archived/expired> (via chez nous).

Ici on ne parle exclusivement que des demandes qui expirent, ça me semble logique de mettre ce bouton de renouvellement dans la vue des demandes (et donc sur `/compte`), suffit d'ajouter un bouton si la demande expire dans moins de X jours.

2023-09-21 09:35 UTC, Un3x commented on app/models/authorization_request.rb
> +  scope :with_tokens_for, ->(api) { where(api:).joins(:tokens) }
Mais ...on peut faire un where sur la colonne d'une table qui n'est pas join ?

2023-09-21 09:35 UTC, Un3x commented on app/models/authorization_request.rb
> +  scope :with_tokens_for, ->(api) { where(api:).joins(:tokens) }
ah ben non ca marche pas

2023-09-21 09:40 UTC, skelz0r commented on app/models/authorization_request.rb
> +  scope :with_tokens_for, ->(api) { where(api:).joins(:tokens) }
Ouais faut join ici, mais du coup ma remarque du commentaire initial n'est plus valide

2023-09-21 09:51 UTC, Un3x commented on app/controllers/api_entreprise/tokens_controller.rb
> +    @tokens = authorization_requests.map(&:token)
Alors oui on peut, et ca semble logique.

Mais du coup je suis aller check la raison de l'état de cette page, et on retombe dans les travers de ce ticket : https://github.com/etalab/admin_api_entreprise/issues/892.

Et on a du coup plus ou moins déjà eu cette conversation. J'avoue que je suis pour shipper, et mettre à plat ou ne pas shipper du tout et mettre à plat. Mais pas faire l'entre deux.

2023-09-21 09:58 UTC, skelz0r commented on app/controllers/api_entreprise/tokens_controller.rb
> +    @tokens = authorization_requests.map(&:token)
Je te laisse trancher.

2023-09-22 07:32 UTC, DorineLam commented
@Un3x j'ai lu en diagonale vos échanges, on en reparle début d'aprem avec les maquettes.

2023-09-22 14:49 UTC, Un3x commented
Pas mal de choses ont changé dans la PR suite à notre point avec @DorineLam et @Haelle.

Conformément à ce qu'on a dit, on investit pas des masses sur ce sujet. Le nouvel état étant mieux que le précédent on continue dans cette esprit et on a un vrai sujet de refonte qui sera traité dans un chantier linear à part entière.

Les changements par rapport à la dernière review : 
* Changement du titre de la page : Habilitation et jetons.
* Afficher les habilitations avec un jetons actif en premier, les autres en 2nd.
* Mettre un séparateur entre les 2 sections.
* Déplacer les label de l'habilitation vers le jetons, utiliser les badges de la page des habilitations

![image](https://github.com/etalab/admin_api_entreprise/assets/9677688/870bfb0b-3df4-4c9a-831b-9570f727d9f3)

Je suis pas hyper fan de l'affichage du badge que je trouve un peu collé. J'aimerai bien que quelqu'un mexplique le fonctionnement de dsfr parce que j'ose rien faire en terme de css / design à proprement parler parce que je ne sais pas d'où viennent les règles.

J'ai utilisé le titre comme séparateur. J'ai laissé l'affichage du warning de non divulgation des jetons dans la partie inactif. Pas sûr que ce soit pertinent.

2023-09-22 14:55 UTC, Un3x commented
Et dans le cas où il n'y a pas de token inactif 

![image](https://github.com/etalab/admin_api_entreprise/assets/9677688/5c4a7835-3204-437f-8ae5-395d4f94e387)

2023-09-22 14:56 UTC, skelz0r commented
> Je suis pas hyper fan de l'affichage du badge que je trouve un peu collé. J'aimerai bien que quelqu'un mexplique le fonctionnement de dsfr parce que j'ose rien faire en terme de css / design à proprement parler parce que je ne sais pas d'où viennent les règles.

https://www.systeme-de-design.gouv.fr/

enjoy

2023-09-22 14:59 UTC, Un3x commented
> (sur un design system de manière général je stick au max aux composants, comme ça je fais 0 ligne de css parce que c'est pas ton taff)

Oui on est raccord. J'avais la flemme de lire tout le css et les composants pour piger comment ca marche, je cherchais plutot les règles. Merci pour le lien.

2023-09-22 15:10 UTC, skelz0r commented
> > (sur un design system de manière général je stick au max aux composants, comme ça je fais 0 ligne de css parce que c'est pas ton taff)
> 
> Oui on est raccord. J'avais la flemme de lire tout le css et les composants pour piger comment ca marche, je cherchais plutot les règles. Merci pour le lien.

Honnêtement ce n'est pas notre boulot (à toute l'équipe), on nous impose une charte et des composants je me pose même pas la question. i.e. je ne regarde pas l'UI mais l'UX

2023-09-22 15:17 UTC, skelz0r requested changes
2 requêtes SQL pour sortir quasi la même donnée, c'est une 1 requête de trop.

2023-09-22 15:17 UTC, skelz0r commented on app/controllers/api_entreprise/tokens_controller.rb
> +    @inactive_tokens = authorization_requests.map(&:token).sort_by(&:exp).reverse - @active_tokens
Pourquoi ne pas sortir tout ça en une fois et en ordonnant en SQL ?

2023-09-22 15:17 UTC, skelz0r commented on app/models/authorization_request.rb
> +    tokens.max_by(&:exp)
```suggestion
    tokens.order(exp: :desc).limit(1).first
```

2023-09-22 15:17 UTC, skelz0r commented on app/controllers/api_entreprise/tokens_controller.rb
> +    @inactive_tokens = authorization_requests.map(&:token).sort_by(&:exp).reverse - @active_tokens
Quitte à les `group_by` avec une ligne supplémentaire. Mon point ici est de ne faire qu'une requête SQL.

2023-09-26 07:27 UTC, DorineLam commented on app/views/api_entreprise/tokens/_token.html.erb
> +          <span class="fr-text--sm fr-m-0 pull-right">
Je me demande si ton problème de tag "collé" ne viendrait pas du fait que tu as mis une margin à 0.

Essaye peut-être ça : 
```suggestion
          <span class="fr-text--sm fr-m-2w pull-right">
```

2023-09-26 07:42 UTC, Un3x commented on app/views/api_entreprise/tokens/_token.html.erb
> +          <span class="fr-text--sm fr-m-0 pull-right">
oui c'est fixé, c'était pas tout à fait ca mais c'est bon now :)

2023-09-26 12:05 UTC, merged

2023-09-26 12:10 UTC, Un3x commented
J'ai mergé parce que le seul points de "frictions" tech est sur les 2 requêtes sql.

Mais je viens de valider avec @Haelle que ce n'est pas le bon mécanisme et qu'il va falloir changer pour une règle qui est en discussions. 

Donc on se fait pas chier à clean ca, ca va clean d'ici 10jours avec la nouvelle règle.

2023-09-26 12:27 UTC, skelz0r commented
Ça me va.