Mails/migrer ScheduleAuthorizationRequestMailjetEmail sans Mailjet
etalab/admin_api_entreprise pull request #1252
Opened 2023-09-26 10:39 UTC by Samuelfaure

Review à faire commit-par-commit

Première partie pour https://linear.app/pole-api/issue/API-725/refacto-du-code-pour-envoyer-les-mails-depuis-admin-et-non-avec-des

Ce que fait la PR:

- Du refacto sur un mailer Particulier/Entreprise 
- du clean + des changements de noms de variable pour préparer la migration hors de Mailjet
- Ajout de la possibilité de configurer la config datapass webhook pour envoyer les mails depuis UserMailer

Ce qui sera fait dans les prochaines PR:

- Même chose pour ScheduleExpirationNoticeMailjetEmailJob
- Implémentation des templates d'emails & adaptation de la config datapass webhook pour envoyer seulement depuis UserMailer
- Finalement, suppression de la possibilité d'envoyer par Mailjet

2023-09-26 11:02 UTC, skelz0r requested changes
J'ai plusieurs soucis avec cette PR:

1. Le refactor de `UserMailer` n'a pas lieu d'être car les 2 emails envoyé par ce `UserMailer` sont spécifiques à API Entreprise et n'utilise pas le templating de Mailjet
2. Tu définies une méthode `deliver_email` dans `ScheduleAuthorizationRequestEmailJob` où il n'y a pas réellement de template, et tu utilises le `UserMailer` alors qu'il s'agit d'un `AuthorizationRequestMailer`

Pour 1., la seule chose à faire imo est de renommer `UserMailer` en `APIEntreprise::UserMailer`

Pour 2., je comprends la logique que tu as voulu appliquer, mais 1. le naming est mauvais à mon sens, et 2. tu devrais directement implémenter les vues au lieu de préparer un terrain avec du code abstrait/non fonctionnel en l'état. Ce que je ferai à ta place est d'abord de rappatrier les emails API Entreprise et faire un `APIEntreprise::AuthorizationRequestMailer` "simple", et dans un second temps tu refactor pour introduire les emails API Particulier. En gros ici tu introduis de la complexité avant de la fonctionnalité, et je pense que tu devrais le faire dans l'autre sens (i.e. rappatrier d'abord les templates Mailjet pour l'existant, et ensuite faire API Particulier): ça sera beaucoup plus simple dans ce sens imo.

J'ai arrêté de mettre des inlines comment quand je me suis rendu compte que tu allais faire un god pattern avec le `UserMailer`

2023-09-26 11:03 UTC, skelz0r commented on app/mailers/concerns/user_mailers_commons.rb
> +    @login_url = "https://dashboard.#{api}.api.gouv.fr/login"
(ce commentaire est finalement irrelevant car cette fonctionnalité n'existe pas sur API Particulier)

2023-09-26 11:04 UTC, skelz0r commented on app/mailers/concerns/user_mailers_commons.rb
> +    subject = "API #{api.capitalize} - Délégation d'accès"
(ce commentaire est finalement irrelevant car cette fonctionnalité n'existe pas sur API Particulier)

2023-09-26 11:04 UTC, skelz0r commented on app/mailers/concerns/user_mailers_commons.rb
> +    subject = "API #{api.capitalize} - Réconciliation de demandes d'accès à un nouvel usager"
(ce commentaire est finalement irrelevant car cette fonctionnalité n'existe pas sur API Particulier)

2023-09-26 12:07 UTC, Samuelfaure commented
1. L'objectif est qu'à la fin de cette série de PR, on ait une standardisation complète Particulier/Entreprise, et à ce moment là les méthodes vont servir; mon point de vue est que refactoriser tout ça un peu plus tôt me permet de travailler plus proprement par la suite, même si ces 2 méthodes sont orphelines sur Particulier pour le moment;
2. Je trouvais plus simple de faire comme j'ai fait ici, où je rajoute la fonctionnalité, ensuite on intègre à la vitesse qu'on veut, puis on supprime l'existant; l'alternative ça va être de devoir intégrer tout les mails + le mailer, qui seront d'ailleurs temporairement du code orphelin, et de refaire le travail que j'ai fait ici

Mais je fais confiance à ton expérience;

Je propose de mettre cette PR en pause, de faire une nouvelle PR comme tu le conseilles en commençant par le bas et en allant vers le haut, et puis je réutiliserais des bouts de celle-ci le moment venu

WDYT?

2023-09-26 12:15 UTC, skelz0r commented
> Je propose de mettre cette PR en pause, de faire une nouvelle PR comme tu le conseilles en commençant par le bas et en allant vers le haut, et puis je réutiliserais des bouts de celle-ci le moment venu

Ça me va.

J'entends pour 1. qu'on veuille standardiser, mais les 2 méthodes du `UserMailer` font parti de fonctionnalités à part entière qui à mon sens n'ont rien à faire dans le scope du projet sur lequel tu travailles (et d'ailleurs, est-ce qu'on veut pouvoir transférer ses jetons sur API Particulier ?), et on peut clairement ignorer ce mailer pour le travail que tu fais (vu que ça impacte les emails liés aux demandes et non aux users en tant que tel).

Pour 2., vu la manière dont tu procèdes, tu vas te retrouver à 1. rapatrier les emails API Entreprise avec une abstraction pour les 2 apps et 2. devoir implémenter dans la foulée les emails API Particulier. Ce que je propose est déjà de migrer l'existant, ce qui te permet d'avoir un code plus simple dans un premier temps (et directement jeter Mailjet en bonus), et après refactoriser (ou non, ça dépendra de l'implémentation en vrai) pour implémenter le fonctionnel d'API Particulier, ce qui à mon sens est plus simple pour le code et pour la relecture. Le red flag que je pointe ici est que tu fais une abstraction sans apport fonctionnel, avec du code qui est mort (car non utilisé), et qui, ça se trouve, sera jeté au moment où tu feras l'import effectif.

2023-09-26 14:12 UTC, Un3x commented
J'arrive après la bataille :/

2023-10-24 13:20 UTC, skelz0r commented
On est d'accord qu'ici on close ?

2023-10-24 15:58 UTC, Un3x commented
J'ai compris ca oui à voir avec @Samuelfaure

2023-11-06 09:15 UTC, Un3x commented
ah ben ca vient de repush ici, on close peut être pas :O ??

2023-11-06 09:20 UTC, Samuelfaure commented
@Un3x J'ai fix les conflits / rebase viteuf voir si je réutilise le code ici pour la suite des mails

2023-11-07 12:47 UTC, Un3x reviewed
Cf mes coms +  ceux de loic du coup.
Je comprends pas du tout le dernier commit :O

2023-11-07 12:47 UTC, Un3x commented on app/mailers/api_entreprise_mailer.rb
> +  end
?

2023-11-07 12:47 UTC, Un3x commented on app/mailers/api_particulier_mailer.rb
> +  end
?

2023-11-07 12:47 UTC, Un3x commented on app/jobs/schedule_authorization_request_email_job.rb
> +    end
Si je comprends bien les vérifications liés à l'authorization request ne devrait concerner que le `deliver_email_using_mailjet` on ? Si oui, il faut cut l'exec early sur le deliver

2023-11-07 12:47 UTC, Un3x commented on app/jobs/schedule_authorization_request_email_job.rb
> +    end
Après bon je trouve toute la classe un peu cheloue. Pour moi ici il aurait été optimal d'avoir un pattern adapter. Ca aurait permit de mettre une interface unique et juste d'injecter le bon mailer en fonction d'une condition.

2023-11-07 12:57 UTC, Samuelfaure commented
@Un3x Woops, la demande de review datait d'il y a très longtemps, on est absolument pas prêt à une review ici ^^

2023-11-09 13:44 UTC, Un3x approved these changes

2023-11-09 13:44 UTC, Un3x commented on app/jobs/schedule_authorization_request_email_job.rb
> +    interesting_mail_attributes = {
interesting

2023-11-09 13:44 UTC, Un3x commented on app/jobs/schedule_authorization_request_email_job.rb
> +    interesting_mail_attributes = {
En vrai je trouve que le naming ici est pas dingo

2023-11-09 13:44 UTC, Un3x commented on app/jobs/schedule_authorization_request_email_job.rb
> +    interesting_mail_attributes = {
not critical cela dit.

2023-11-09 13:44 UTC, Un3x commented on app/jobs/schedule_authorization_request_email_job.rb
> +    mail_klass = "#{api_klass}::AuthorizationRequestMailer".constantize
Je sortirais bien ces lignes de cette méthodes pour les ranger ailleurs.

Genre un `def api_klass` et un `def mailer_klass` ca respecte un peu plus le OC principle.

2023-11-09 13:49 UTC, skelz0r commented
@Samuelfaure est-ce que tu peux rebase sur develop stp ?

2023-11-09 13:51 UTC, skelz0r requested changes
Pour pas que tu merges à la suite du approve de Thomas, y'a beaucoup de code mort en survolant.

2023-11-09 14:05 UTC, skelz0r requested changes
Globalement y'a encore du clean à faire, y'a des choses lié à Mailjet dans les mailers, alors que ça n'a plus rien à voir.

Au passage je pense que tu devrais revert l'ajout des attributs sur le contact métier et postpone à après la migration effective histoire de simplifier.

2023-11-09 14:05 UTC, skelz0r commented on app/jobs/schedule_authorization_request_email_job.rb
> +    api_klass = "#{API}#{@authorization_request.api.capitalize}".constantize
omg ce `"#{API}` est monstrueusement brainfuck 😨

Ça devrait être `"API#{@authorization_request.api.capitalize}"`

2023-11-09 14:05 UTC, skelz0r commented on app/jobs/schedule_authorization_request_email_job.rb
> +    mail_klass = "#{api_klass}::AuthorizationRequestMailer".constantize
Je plussoie Thomas, tu devrais refactor ca dans une autre méthode `mailer_klass` (`mail_klass` n'est pas un bon wording car ce n'est pas un mail mais bien un mailer)

2023-11-09 14:05 UTC, skelz0r commented on app/jobs/schedule_authorization_request_email_job.rb
> +    mail_klass.public_send(mail_attributes[:template_name].to_sym, interesting_mail_attributes)
A la lumière des différents commentaires que j'ai fait:

```suggestion
    mailer_klass.public_send(mail_attributes[:template_name], mail_recipients_attributes)
```

2023-11-09 14:05 UTC, skelz0r commented on app/jobs/schedule_authorization_request_email_job.rb
> +      vars: mail_attributes['vars'],
Je ne comprends à quoi sert ce `vars`

2023-11-09 14:05 UTC, skelz0r commented on app/jobs/schedule_authorization_request_email_job.rb
> +      'Mj-TemplateID' => mail_attributes['template_id']
??? je ne comprends pas ce que c'est

2023-11-09 14:05 UTC, skelz0r commented on app/jobs/schedule_expiration_notice_mailjet_email_job.rb
> +  include MailHelpers
Ce `MailHelpers` ne devrait pas être inclut dans le `MailjetHelpers` ? Car ce n'est pas utilisé dans les mailers mais uniquement dans Mailjet.

2023-11-09 14:19 UTC, Samuelfaure commented on app/jobs/schedule_authorization_request_email_job.rb
> +    api_klass = "#{API}#{@authorization_request.api.capitalize}".constantize
Aouch :sweat_smile:

2023-11-09 14:20 UTC, skelz0r commented on app/jobs/schedule_authorization_request_email_job.rb
> +    api_klass = "#{API}#{@authorization_request.api.capitalize}".constantize
C'est tombé en marche en vrai ici 😅

2023-11-09 14:53 UTC, skelz0r commented on app/jobs/concerns/mailjet_helpers.rb
> -  def from_name(api)
Oui j'ai en effet suggéré ça plus bas en déroulant le code en local.

2023-11-09 19:55 UTC, Samuelfaure commented
@skelz0r J'ai changé l'interface de la classe dans le dernier commit pour simplifier, si ça te va go merge

2023-11-09 20:29 UTC, skelz0r requested changes
Globalement le code c'est OK. 

Par contre comme évoqué en inline comment, shipper ici les emails API Particulier avec le contact métier fait que ça ne fonctionnera pas, car il n'y a pas de contact métier côté DataPass. 

Un dernier (gros) point: je pense qu'il faudrait tester que les templates utilisés dans le fichier de config DataPass existent (parce que là dans ta config tu as mentionné des templates inconnus 🤷), maintenant que c'est dans l'app c'est simple, et au moins on est sûr que ça fonctionne.

2023-11-09 20:29 UTC, skelz0r commented on app/jobs/schedule_authorization_request_email_job.rb
> +    "API#{@authorization_request.api.capitalize}".constantize
```suggestion
    "API#{@authorization_request.api.classify}".constantize
```

2023-11-09 20:29 UTC, skelz0r commented on config/datapass_webhooks_particulier.yml
> +          - 'authorization_request.contact_metier'
Pourquoi ce changement métier ?

2023-11-09 20:29 UTC, skelz0r commented on config/datapass_webhooks_particulier.yml
> +          - 'authorization_request.contact_metier'
Et surtout, je pense qu'en l'état ça ne marchera pas: il n'y a pas de contact métier côté API Particulier. Du coup, `recipient_payload` va juste fail quand il va faire un `.email` sur le contact.

A ce stade, comme dit plusieurs fois dans cette PR, il faut supprimer toutes traces du contact métier côté API Particulier pour pouvoir shipper, sinon c'est du code défectueux qu'on va délivrer en production, où il faudra au choix revert ici ou itérer pour mettre sur toutes les demandes datapass le contact métier (et d'ailleurs, même les validés seraient potentiellement impacté). Imo c'est un très mauvais move

2023-11-09 20:29 UTC, skelz0r commented on config/datapass_webhooks_particulier.yml
> +      - template: 'embarquement_valide_to_metier_cc_demandeur_tech'
Ce template n'existe pas car j'ai migré sans contact_metier

2023-11-09 20:29 UTC, skelz0r commented on config/datapass_webhooks_particulier.yml
> +      - template: 'embarquement_valide_to_metier_cc_demandeur_tech'
Ce template n'existe pas car j'ai migré sans contact_metier

2023-11-09 20:29 UTC, skelz0r commented on config/datapass_webhooks_particulier.yml
> +      - template: 'embarquement_valide_to_demandeur_is_metier_not_tech'
Ce template n'existe pas car j'ai migré sans contact_metier

2023-11-09 20:29 UTC, skelz0r commented on config/datapass_webhooks_particulier.yml
> +      - template: 'embarquement_demande_to_tech_cc_demandeur_metier'
Ce template existe MAIS j'ai loupé un renaming ici 😅 Faudrait renommer en `embarquement_demande_to_tech_cc_demandeur`

2023-11-09 20:29 UTC, skelz0r commented on config/datapass_webhooks_particulier.yml
> +      - template: 'enquete_satisfaction'
Globalement ici faut clean tous les templates pour retirer toute trace du contact métier.

2023-11-09 20:29 UTC, skelz0r commented on config/datapass_webhooks_particulier.yml
> +      - template: 'enquete_satisfaction'
Et par ailleurs, à la lumière de mes commentaires plus bas on a un trou dans la raquette: on ne teste pas que ça fonctionne partout.. imo faudrait itérer sur spec/acceptances/datapass_webhooks_config_format_spec.rb pour vérifier que les méthodes existent sur chaque mailer.

2023-11-09 20:29 UTC, skelz0r commented on spec/interactors/datapass_webhook/schedule_authorization_request_emails_spec.rb
> -      ).at(14.days.from_now)
Pourquoi on retire ce test, on a envie de voir que y'a bien 2 trucs différents de schedule non ?

2023-11-09 20:29 UTC, skelz0r commented on spec/interactors/datapass_webhook/schedule_authorization_request_emails_spec.rb
> -          expect(ScheduleAuthorizationRequestMailjetEmailJob).to have_been_enqueued.exactly(:once).with(
Pourquoi on retire ce test, on a envie de voir que y'a bien 2 trucs différents de schedule non ?

2023-11-09 20:29 UTC, skelz0r commented on spec/jobs/schedule_authorization_request_email_job_spec.rb
> +      end
imo ça se flip les non-regression quand on ré-écrit une classe

2023-11-09 20:29 UTC, skelz0r commented on spec/jobs/schedule_authorization_request_email_job_spec.rb
> +    end
```suggestion
    before(:all) do
      class APIEntreprise::AuthorizationRequestMailer
        def email_template; end
      end
    end
```

Y'avait vraiment besoin de redéfinir une méthode ? Elles sont toutes iso en plus donc en tester une = toutes les tester.

2023-11-09 20:29 UTC, skelz0r commented on spec/organizers/datapass_webhook/api_particulier_spec.rb
> +  describe 'when no contact métier (non-regression)' do
non régression sur une nouvelle feature ?? très étrange

2023-11-10 08:07 UTC, Samuelfaure commented on spec/jobs/schedule_authorization_request_email_job_spec.rb
> +    end
Tu veux dire qu'on pourrait utiliser une méthode qui existe déjà dans le mailer? Je préfère en redéfinir une ici histoire de montrer que le fonctionnement est indépendant des méthodes existantes

2023-11-10 08:11 UTC, skelz0r commented on spec/jobs/schedule_authorization_request_email_job_spec.rb
> +    end
C'est peu conventionnel de ré-ouvre une classe existante dans la codebase pour y ajouter une méthode, ça peut avoir des side effects.

Je vais pas me formaliser là dessus, juste je ne comprends pas pourquoi on a besoin de définir une méthode supplémentaire (ce qui m'aménerai à scout commit si je repasse sur le fichier pour simplifier)

2023-11-10 19:30 UTC, merged