feat(Mailjet): add role properties
etalab/admin_api_entreprise pull request #126
Opened 2021-05-26 14:21 UTC by cyril

Ajout de nouvelles propriétés relatives aux rôles dans le payload à envoyer à [Mailjet](https://fr.mailjet.com/).

2021-05-26 14:22 UTC, cyril commented
Je propose d'ajouter une tâche pour ajouter les rôles aux contacts précédemment ajoutés via une autre PR.

2021-05-26 16:36 UTC, skelz0r requested changes
Il manque des tests pour montrer que fonctionnellement on transmet des valeurs à true si les rôles sont présents.

2021-05-26 16:36 UTC, skelz0r commented on app/models/role.rb
> +  has_many :users, through: :jwt_api_entreprise
Pourquoi ? Et surtout: pourquoi ce n'est pas dans un autre commit ? (fonctionnellement ça n'a rien à voir avec la feature).

2021-05-26 16:36 UTC, skelz0r commented on spec/models/role_spec.rb
> +RSpec.describe Role do
A mettre dans un commit à part imo.

2021-05-26 16:36 UTC, skelz0r commented on spec/models/user_spec.rb
> +    it { is_expected.to have_many(:roles).through(:jwt_api_entreprise) }
A mettre dans un commit à part imo

2021-05-27 12:33 UTC, cyril commented on app/lib/mailjet/contact_properties_adapter.rb
> +      ].freeze
Nous pourrions le faire, avec l'avantage de ne pas répéter l'information. Ce serait clairement mieux sur ce plan.

La seule chose qui me gène, c'est que cette liste doit matcher l'interface de nous propriétés nouvellement ajoutés de Mailjet. Si nous générons cette liste dynamiquement via nos rôles qui sont en DB, c'est DRY, mais on crée une contrainte fonctionnelle entre nos données en DB et les attributs sur Mailjet. Je crois que ce serait source d'erreurs, nous ou nos successeurs pourraient sans le savoir casser la syncho juste en modifiant nos rôles. Je préférerais que le procédé de sérialisation du payload puisse se faire explicitement, sans couplage direct avec notre base.

De la même façon qu'on préfère tous faire des API web avec des sérialiseurs, bien qu'il soit possible de faire dynamiquement `@article.as_json`.

J'ajoute que sur Mailjet, nous n'avons pas forcément tous les rôles qui sont en base, comme par exemple le rôle `uptime` (sauf erreur, il n'y a pas besoin de propriété `role_uptime` puisqu'il n'est utilisé que pour un bot).

2021-05-27 14:18 UTC, cyril commented on app/lib/mailjet/contact_properties_adapter.rb
> +      ].freeze
Ok alors pour cette contrainte fonctionnelle, mais on est d'accord que ça va à l'encontre du principe de separation of concerns entre d'une part des attributs Mailjet et d'autre part des valeurs que nous avons en base de données.

2021-05-27 15:28 UTC, cyril commented on app/lib/mailjet/contact_properties_adapter.rb
> +      ].freeze
Coté implémentation, je préférerais inclure explicitement les bonnes valeurs plutôt qu'exclure les mauvaises (au risque d'en oublier, ou d'être victime d'un effet de bord, lorsqu'on en ajouterait d'autres - question de sécurité). En reprenant le draft précédent, ça correspondrait à ça :

```ruby
def availables_roles
  Role.where(code: included_roles).pluck(:code)
end

def included_roles
  %w[
    actes_inpi
    associations
    attestations_agefiph
    attestations_fiscales
    attestations_sociales
    bilans_entreprise_bdf
    bilans_inpi
    certificat_agence_bio
    certificat_cnetp
    certificat_opqibi
    certificat_rge_ademe
    conventions_collectives
    documents_association
    entreprises
    entreprises_artisanales
    eori_douanes
    etablissements
    exercices
    extrait_court_inpi
    extraits_rcs
    fntp_carte_pro
    liasse_fiscale
    msa_cotisations
    probtp
    qualibat
  ]
end
```

Pour être franc, ça m'a pas l'air mieux. Moyennant ladite concession sur la séparation des responsabilité en moins. Il est toujours temps de remettre ce choix en question :)

2021-05-27 16:30 UTC, cyril commented
@skelz0r, je viens d'ajouter deux tests units. Si c'est nécessaire, je peux en ajouter pour tester des combinaisons de 2 roles, voire 3. Dis moi ce que tu en penses.

2021-05-28 10:00 UTC, skelz0r commented on app/lib/mailjet/contact_properties_adapter.rb
> +      ].freeze
> Pour être franc, ça m'a pas l'air mieux. 

Là c'est une version moins optimisée de ta version de base et en retirant l'intérêt fonctionnel discuté plus haut, clairement c'est moins bien que la version d'origine.

> ou d'être victime d'un effet de bord, lorsqu'on en ajouterait d'autres - question de sécurité

C'est un risque qu'on peut prendre, vu que de toute façon on effectue des actions manuels d'envoi des NLs, en fonction de ces critères. Si il y a un souci au pire on peut toujours nettoyer, je ne vois pas trop les autres risques possibles.

Je pense que ma version plus haut est mieux.

@brindu @Haelle thoughts ?

2021-05-28 10:13 UTC, brindu commented on app/lib/mailjet/contact_properties_adapter.rb
> +      ].freeze
> Je pense justement qu'on veut créer cette contrainte fonctionnelle. Le cas contraire il faudrait, en plus de quand on ajoute le rôle dans la db, l'ajouter ici : l'argument que tu avances est d'autant plus vrai plus vrai si on laisse en hardcodé et qu'on oublie justement de l'ajouter ici (là on se retrouve avec une désynchro).

Je préfère aussi ta version @skelz0r, pour cette raison.

2021-05-28 10:15 UTC, skelz0r commented
> @skelz0r, je viens d'ajouter deux tests units. Si c'est nécessaire, je peux en ajouter pour tester des combinaisons de 2 roles, voire 3. Dis moi ce que tu en penses.

Je pense que ça suffit, au moins on comprend que c'est lié aux rôles présents en base en lisant les tests 👍

2021-05-31 15:15 UTC, cyril commented on app/lib/mailjet/contact_properties_adapter.rb
> +      ].freeze
Je viens de mettre en place ce mécanisme.

2021-05-31 15:16 UTC, cyril commented
Pour info, j'ai ajouté une modification annexe pour simplifier l’écriture du code. Cette [modification annexe a sa propre PR](https://github.com/etalab/admin_api_entreprise/pull/128), que je vous propose de valider en amont si elle vous convient.

2021-06-01 12:30 UTC, skelz0r approved these changes

2021-06-02 09:41 UTC, merged