Export legacy token to file
etalab/admin_api_entreprise pull request #1261
Opened 2023-10-02 08:33 UTC by Un3x

2023-10-04 09:06 UTC, Samuelfaure approved these changes
Bon j'ai procrastiné cette review parce que le code est relou à comprendre, mais en vrai c'est testé et à jeter donc osef perso je valide

2023-10-04 12:11 UTC, skelz0r requested changes
J'ai omis des questions de style parce que c'est du jetable.

Par contre y'a des trucs bizarres:

* On peut avoir N jetons pour 1 legacy jeton ?
* Le constructeur est vraiment bizarre, pourquoi tu passes le path vers le fichier des legacy ainsi que des legacy ..? Ça me semble redondant. Si l'objectif est de nettoyer au fur et à mesure, tu peux juste maintenir le fichier.

2023-10-04 12:11 UTC, skelz0r commented on app/services/token_export.rb
> +    end
J'en déduis ici qu'il peut y avoir N token pour un legacy token ? Cela me semble étrange.

2023-10-04 12:11 UTC, skelz0r commented on app/services/token_export.rb
> +    token_to_export.find_each do |token|
`tokens_to_export`

2023-10-04 12:11 UTC, skelz0r commented on app/services/token_export.rb
> +  def key(token)
```suggestion
  def filename(token)
```

2023-10-04 12:11 UTC, skelz0r commented on app/services/token_export.rb
> +    if token.authorization_request.demarche.present?
question peut-être stupide mais: pourquoi on n'utilise pas le datapass_id comme clé ? elle n'est pas tout le temps renseignée ?

2023-10-04 12:11 UTC, skelz0r commented on app/services/token_export.rb
> +    @filepath = filepath
Je ne comprends pas à quoi sert cette variable: le fichier est toujours le même non ? D'ailleurs le naming est chelou.
Et en y repensant, tu passes aussi `legacy_tokens`, je ne comprends pas pourquoi.

2023-10-04 12:11 UTC, skelz0r requested changes
J'ai omis des questions de style parce que c'est du jetable.

Par contre y'a des trucs bizarres:

* On peut avoir N jetons pour 1 legacy jeton ?
* Le constructeur est vraiment bizarre, pourquoi tu passes le path vers le fichier des legacy ainsi que des legacy ..? Ça me semble redondant. Si l'objectif est de nettoyer au fur et à mesure, tu peux juste maintenir le fichier.

2023-10-09 07:08 UTC, Un3x commented on app/services/token_export.rb
> +    end
La clé c'est pas le legacy token, la clé ca peut être une demarche datapass, un contact technique ou alors (le cas échéant) le demandeur.

L'idée c'est d'avoir 1 fichier par contact qui gère potentiellement N clé.

2023-10-09 07:10 UTC, Un3x commented on app/services/token_export.rb
> +    if token.authorization_request.demarche.present?
parce que justement le but est de rassemblé les token selon une certaines démarche en priorité.

2023-10-09 07:11 UTC, Un3x commented on app/services/token_export.rb
> +    @filepath = filepath
alors, c'était pour simplifier les tests je l'admets. J'ai eu un élan de flemme à un moment et je me suis dis, c'est jetable, donc comme ca je peux mocker plus facilement le contenu du fichier.

2023-10-09 08:48 UTC, skelz0r commented on app/services/token_export.rb
> +    end
Ok c'est pas clair dans les wordings.

2023-10-09 08:49 UTC, skelz0r commented on app/services/token_export.rb
> +    end
`ExportTokensGroupedByMainContact` me semble plus approprié ici par exemple

2023-10-09 09:14 UTC, skelz0r approved these changes

2023-10-09 09:26 UTC, Un3x commented on app/services/token_export.rb
> +    end
ouais ca aurait été mieux, j'avoue que je flemme sur ce retour vu que ca va être executer une seule fois et j'envoie !

2023-10-09 09:26 UTC, merged