Provide Standard URL for new token file
etalab/admin_api_entreprise pull request #1266
Opened 2023-10-09 13:29 UTC by Un3x

Cette PR est dans la foulée de la PR de génération des fichiers.

Il fallait fournir une url unique pour N user cachée, derrière un login MCP qui renvoit le premier fichier matchant la nomenclature.
À jeter une fois que la migration des tokens sera terminée

2023-10-09 13:33 UTC, Haelle commented on config/routes/api_particulier.rb
> +    get '/compte/nouveau-jeton', to: 'users#new_token', as: :legacy_to_new_token
```suggestion
    get '/compte/nouveaux-jetons', to: 'users#new_token', as: :legacy_to_new_tokens
```

2023-10-09 13:36 UTC, skelz0r requested changes
Go appliquer ma suggestion sur la route, tout le reste découlera.

2023-10-09 13:36 UTC, skelz0r commented on app/controllers/api_particulier/users_controller.rb
> +  def new_token
je ne comprends pas ce nom de méthode, et le rapport avec le fait d'envoyer un fichier, c'est pas rest

2023-10-09 13:36 UTC, skelz0r commented on app/controllers/api_particulier/users_controller.rb
> +    file = file(current_user.email)
`file` comme nom de méthode dans ce controller c'est non

2023-10-09 13:36 UTC, skelz0r commented on app/controllers/api_particulier/users_controller.rb
> +    return send_data file, filename: "jetons_#{current_user.email}.csv" if file.present?
je ne suis pas sûr que mettre un `@` dans une url soit valide et fonctionnel sur tous les navigateurs, faut normaliser.

2023-10-09 13:36 UTC, skelz0r commented on app/controllers/api_particulier/users_controller.rb
> +    return send_data file, filename: "jetons_#{current_user.email}.csv" if file.present?
je ferai un `if/else`

2023-10-09 13:36 UTC, skelz0r commented on config/routes/api_particulier.rb
> +    get '/compte/nouveau-jeton', to: 'users#new_token', as: :legacy_to_new_token
```ruby
    get '/compte/nouveaux-jetons/telecharger', to: 'new_tokens#download', as: :download_new_tokens
```

si on veut rester rest way

du coup faut faire le controller et la route --^

2023-10-09 14:10 UTC, Un3x commented on config/routes/api_particulier.rb
> +    get '/compte/nouveau-jeton', to: 'users#new_token', as: :legacy_to_new_token
fblblbl,

En vrai je voulais faire ca au début et après ... voilà. 

Je fix

2023-10-09 14:35 UTC, Un3x commented on app/controllers/api_particulier/users_controller.rb
> +    return send_data file, filename: "jetons_#{current_user.email}.csv" if file.present?
j'ai changé le nom du fichier pour qu'il soit iso pour tout le monde, mais il n'y avais psa de @ dans le navigateur.

2023-10-10 07:10 UTC, Samuelfaure commented on app/controllers/api_particulier/new_tokens_controller.rb
> +    [
Je chipote de ouf mais j'aurais séparé ces deux lignes par une ligne vide

2023-10-10 08:10 UTC, Un3x commented on app/controllers/api_particulier/new_tokens_controller.rb
> +    [
c'est bien parce que c'est toi que je le fais <3

2023-10-10 08:34 UTC, skelz0r requested changes
Modulo le dossier `tmp/` c'est OK pour moi.

2023-10-10 08:34 UTC, skelz0r commented on app/controllers/api_particulier/new_tokens_controller.rb
> +    file_path = Rails.root.join('./tmp/token_export')
`tmp/` est régulièrement nettoyé, il faudrait ajouter un dossier ou en réutiliser un. `storage/` m'a l'air d'être bien.

2023-10-10 09:05 UTC, Un3x commented on app/controllers/api_particulier/new_tokens_controller.rb
> +    file_path = Rails.root.join('./tmp/token_export')
erf du coup c'est passé dans le générator des fichiers (la PR jetable).

Bon je vais devoir changer du coup

2023-10-10 09:12 UTC, skelz0r commented on app/controllers/api_particulier/new_tokens_controller.rb
> +    file_path = Rails.root.join('./tmp/token_export')
Je pensais pas que ça allait être distribué via l'app et donc être de la donnée non-temporaire (ce qui est contradictoire avec le nom du dossier :D)

2023-10-12 09:29 UTC, Un3x commented
> Modulo le dossier `tmp/` c'est OK pour moi.

Du coup c'est bien dans le dossier tmp/ que ca doit attérir finalement vu que le reste saute lors d'un déploiement de l'app.

En attente de merge de https://github.com/etalab/very_ansible/pull/440 pour l'ajout du symlink sur le dossier des token_export

2023-10-12 09:48 UTC, skelz0r commented
Alors non parce que `tmp/` est clean de manière +/- random. Faut que tu fasses un shared dir dans ce cas.
Des explications ici btw https://linear.app/pole-api/issue/API-1419/les-clefs-gpg-publique-de-chiffrement-ne-sont-plus-deployees#comment-bd35ae86

2023-10-12 10:10 UTC, Un3x commented
> Alors non parce que `tmp/` est clean de manière +/- random. Faut que tu fasses un shared dir dans ce cas. Des explications ici btw https://linear.app/pole-api/issue/API-1419/les-clefs-gpg-publique-de-chiffrement-ne-sont-plus-deployees#comment-bd35ae86

J'ai rajouté dans ansible un directory dans le shared /tmp et normalement à l'install le symlink va être fait automatiquement.

2023-10-12 10:12 UTC, skelz0r commented
> > Alors non parce que `tmp/` est clean de manière +/- random. Faut que tu fasses un shared dir dans ce cas. Des explications ici btw https://linear.app/pole-api/issue/API-1419/les-clefs-gpg-publique-de-chiffrement-ne-sont-plus-deployees#comment-bd35ae86
> 
> J'ai rajouté dans ansible un directory dans le shared /tmp et normalement à l'install le symlink va être fait automatiquement.

Bah ..? pourquoi l'avoir mis dans `tmp/` ce shared folder ..? Ce dossier est clean parfois, faut rien mettre de permanent dedans.

2023-10-16 11:55 UTC, merged