Ajoute section CGU spéifique dans les fiches métiers
etalab/admin_api_entreprise pull request #1280
Opened 2023-10-17 16:23 UTC by DorineLam

- Initie un nouvel espace pour ajouter des CGU spécifiques à l'API dans API Part et Entreprise
- Ajoute le champ "Ouverture de la donnée" qui était absent d'API Particulier. J'ai ajouté un champ en dur vue que toutes les API part sont des données protégées
- Ajoute le paragraphe attendu pour les CGU de liste de paiements Pole emploi.

2023-10-17 16:33 UTC, skelz0r requested changes
OK niveau code.

C'est surtout le terme `numéro allocataire` qui me semble non appropriée vu qu'on parle d'identifiant plus haut dans la même page.

2023-10-17 16:33 UTC, skelz0r commented on app/views/api_particulier/endpoints/show.html.erb
> +
C'est forcément protégée non ? imo y'a pas besoin de le mettre.

2023-10-17 16:33 UTC, skelz0r commented on config/endpoints/api_particulier/pole_emploi.yml
> +        Il est **indispensable de recouper l'identité du particulier avec le numéro d'allocataire** avant d'utiliser cette API.
c'est un identifiant comme précisé plus haut, autant garder la même nomenclature.

2023-10-18 07:41 UTC, DorineLam commented on config/endpoints/api_particulier/pole_emploi.yml
> +        Il est **indispensable de recouper l'identité du particulier avec le numéro d'allocataire** avant d'utiliser cette API.
Oui d'ailleurs on va parler d'identifiant Pôle Emploi, c'est comme ça qu'il est nommé. J'attends juste une confirmation de Vincent. Merci de ta vigilance, je vais rectifier.

2023-10-18 07:42 UTC, DorineLam commented on app/views/api_particulier/endpoints/show.html.erb
> +
Ici je suis pour le rappeler. C'est pas long, et ça remet dans le contexte les CGU.

2023-10-18 07:45 UTC, skelz0r commented on app/views/api_particulier/endpoints/show.html.erb
> +
as u ouiche

2023-10-24 10:07 UTC, DorineLam commented
@skelz0r j'ai effectué les modifications. Il est donc confirmé que l'identifiant du compte utilisateur ne figure sur aucun document. J'ai tout expliqué dans la doc. C'est prêt pour être mergé selon moi

2023-10-24 10:17 UTC, skelz0r approved these changes

2023-10-24 10:17 UTC, merged