[Draft] Feature/api 1459 jai acces aux details de mon jeton
etalab/admin_api_entreprise pull request #1293
Opened 2023-10-23 16:20 UTC by Un3x

2023-10-23 16:21 UTC, Un3x commented
Modale de prolongation de token : 

![image](https://github.com/etalab/admin_api_entreprise/assets/9677688/e98e3bdf-4f32-48b6-9ebd-6a6e25cdd200)

2023-10-24 08:04 UTC, Un3x commented
La modale voir un token : 

![image](https://github.com/etalab/admin_api_entreprise/assets/9677688/1d8789cb-d65d-44a5-954f-8e89efd2a9e1)

2023-10-25 08:57 UTC, skelz0r requested changes
Cf mon gros com

2023-10-25 08:57 UTC, skelz0r commented on app/views/shared/authorization_requests/show.html.erb
> +          <% if @authorization_request.demandeur == @current_user or @authorization_request.contact_technique == @current_user %>
Vu que tu fais pas mal de logique dans la vue, je pense qu'il faudrait refactoriser ça.

Je vois 2 choix possibles ici:
1. Une facade -> `AuthorizationRequestFacade` avec des méthodes outils du genre `can_show_technical_user_modal?` and stuff
2. Une gestion de droits via un système comme [Pundit](https://github.com/varvet/pundit)

En l'état de ton code je partirai avec 1., cependant je pense que l'ensemble de tes modals plus bas devrait être refactorisé dans des actions spécifiques, et je pencherai donc plus pour 2.

Pour ce qui est du refactor des modals, il y a une mécanique existante dans le code qui exploite turbo pour afficher une modale (ou ouvrir une nouvelle page). 

Un exemple: https://entreprise.api.gouv.fr/catalogue/inpi/rne/beneficiaires_effectifs
Si tu cliques sur `[Aperçu d'un exemple de réponse JSON](https://entreprise.api.gouv.fr/catalogue/inpi/rne/beneficiaires_effectifs/exemple)` depuis cette page cela ouvre une modal, mais si tu l'ouvres dans un nouvel onglet c'est une autre page.

Je t'invite à refactoriser tout ton bloc de N modals avec cette mécanique, et limiter les actions via une gestion de droit en fonction des conditions que tu appliques.

Cette approche a plusieurs avantages:
1. C'est plus kiss et simple à tester
2. C'est rétrocompatible si tu n'as pas de js
3. On peut faire des liens directs vers les éléments

2023-10-25 09:17 UTC, Un3x commented on app/decorators/token_show_decorator.rb
> +  def self.inferred_object_class
ouais alors ce truc là j'en ai eu besoin parce que dans la vue il arrivait pas à retrouver l'objet inferred. Si je l'enlève la vue pète.

2023-10-25 09:18 UTC, skelz0r commented on app/decorators/token_show_decorator.rb
> +  def self.inferred_object_class
je ..? 😅

T'as quoi comme erreur ?

2023-10-25 09:27 UTC, Un3x commented on app/decorators/token_show_decorator.rb
> +  def self.inferred_object_class
`Could not infer an object for TokenShowDecorator.`

2023-10-25 09:28 UTC, skelz0r commented on app/decorators/token_show_decorator.rb
> +  def self.inferred_object_class
La calltrace exacte* sorry

2023-10-25 10:14 UTC, Un3x commented on app/decorators/token_show_decorator.rb
> +  def self.inferred_object_class
C'est trigger par `dom_id(@main_token, ...)`

Je pourrais être un poil moins relou et juste definir le `self.object_class` ce qui est un poil plus propre (Et que je vais faire du coup).

Mais grosso modo c'est un soucis de délégation du decorator vers l'objet de base quand il a besoin de convertir l'objet en nom d'objet.

Si tu veux voir : 

```

TokenShowDecorator.inferred_object_class
draper (4.0.2) lib/draper/decorator.rb, line 256
TokenShowDecorator.object_class
draper (4.0.2) lib/draper/decorator.rb, line 71
TokenShowDecorator.model_name
draper (4.0.2) lib/draper/decorator.rb, line 225
TokenShowDecorator#model_name
draper (4.0.2) lib/draper/delegation.rb, line 10
#<Class:0x00007fbce60fb680>#model_name_from_record_or_class
actionview (7.1.1) lib/action_view/model_naming.rb, line 11
#<Class:0x00007fbce60fb680>#dom_class
actionview (7.1.1) lib/action_view/record_identifier.rb, line 79
#<Class:0x00007fbce60fb680>#dom_id
actionview (7.1.1) lib/action_view/record_identifier.rb, line 98
#<Class:0x00007fbce60fb680>#_app_views_shared_authorization_requests_show_html_erb___1079520186412400052_139460
app/views/shared/authorization_requests/show.html.erb, line 52
```

2023-10-25 10:32 UTC, skelz0r commented on app/decorators/token_show_decorator.rb
> +  def self.inferred_object_class
Hum, je ne trouve rien sur les internets mais ça me semble un peu pourri comme comportement 🙄

Dans tous les cas ce n'est pas au bon endroit, ça devrait être dans l'ApplicationDecorator.
J'overriderai la méthode `to_model` de cette façon https://github.com/rails/rails/blob/main/actionview/lib/action_view/model_naming.rb#L6

2023-10-31 09:34 UTC, Un3x commented on app/decorators/token_show_decorator.rb
> +  def self.inferred_object_class
C'est lié au fait qu'on utilise un TokenShowDecorator et non un TokenDecorator. Il cherche l'objet en fonction se son nom et non en fonction de celui qu'on lui a passé

2023-10-31 09:37 UTC, skelz0r commented on app/decorators/token_show_decorator.rb
> +  def self.inferred_object_class
C'est un poil stupide comme comportement 🙄

2023-10-31 09:50 UTC, Un3x commented on app/decorators/token_show_decorator.rb
> +  def self.inferred_object_class
Le bout de code que tu m'as filé est déjà appelé par la view btw. C'est plus loin dans la chaîne que ca pète. So far je trouve rien d'élégant en tout cas

2023-10-31 09:52 UTC, skelz0r commented on app/decorators/token_show_decorator.rb
> +  def self.inferred_object_class
Ça me semble logique d'override le `to_model` qui à priori ne renvoi pas un object ActiveModel (pourquoi ..?) pour que ça marche plus loin.

2023-10-31 09:53 UTC, Un3x commented on app/decorators/token_show_decorator.rb
> +  def self.inferred_object_class
On regardera quand t'auras un moment en pair ou toi de ton côté mais là j'avoue que c'est complicada. 
J'arrive pas à intercepter proprement ce qu'il veut sauf via cette methode `inferred_object_class` dans le decorator :/.

2023-10-31 09:55 UTC, skelz0r commented on app/decorators/token_show_decorator.rb
> +  def self.inferred_object_class
Sinon on subtilise le `TokenDecorator` (qui en vrai n'est pas vraiment utilisé comme decorator, on peut déporter ce code ailleurs genre dans une façade).

2023-10-31 10:00 UTC, Un3x commented on app/decorators/token_show_decorator.rb
> +  def self.inferred_object_class
aller

2023-10-31 10:01 UTC, skelz0r commented on app/decorators/token_show_decorator.rb
> +  def self.inferred_object_class
(je vois le code imo tu peux aller tout mettre dans la facade existante)

2023-10-31 10:10 UTC, Un3x commented on app/decorators/token_show_decorator.rb
> +  def self.inferred_object_class
Oui, on utilise le decorator dans le model du token, un vrai plaisir :D

2023-11-02 16:13 UTC, Un3x commented
Bon du coup c'est théoriquement fini.

Au final j'ai : 
- Utiliser la facade pour la gestion des droits
- Utiliser turbo frame pour les modales
- Ameliorer grandement les tests

J'ai pas utilise la gem pour les droits parce que dans tous les cas j'ai besoin d'une facade pour la vue, donc voilà.

Reste quelques sujets : 
- Certains namings sont bof surtout dans le dernier commit.
- La modale de modale n'est pas faite avec turbo. C'est pas DRY non plus (mais on va supprimer l'autre implem). Là je sais pas trop pourquoi mais turbo il aime pas trop la modale de modale. Je crois qu'il intercepte l'event comme étant une fermeture de modale. Bref je regarderai si c'est bloquant 

Ca peut se lire commit par commit, mais clairement j'ai fais des refacto des choses que j'avais codé et d'autres refacto en cours de route.

2023-11-02 16:14 UTC, skelz0r commented
> La modale de modale 

je .. quoi ? 😅

2023-11-02 16:18 UTC, Un3x commented
> > La modale de modale
> 
> je .. quoi ? 😅

Oui il y a la modale qui permet de voir un token et de le copier ou de le transférer, au quel cas il faut ouvrir la modale de transfer.

Sinon j'ai un cas un peu bizarre.
Uniquement sur api particulier, quand t'essaye d'aller sur l'une des pages avec un token inexistant, il ne retrouve pas les message d'erreur dans le flash. Il va les chercher dans le fichier api_particulier, au lieu d'aller dans api_entreprise concerns.
Ce qui n'est pas le cas pour le contenu de la modale.

là où c'est chiant c'est que si je les mets pas on a pas de traduction et si je les mets c'est i18n unused qui est pas d'accord.

2023-11-02 16:23 UTC, Un3x commented
El famoso modalo de modalo 

![image](https://github.com/etalab/admin_api_entreprise/assets/9677688/569def36-9ca3-479d-8a6c-062e9f5c390c)

2023-11-02 17:37 UTC, skelz0r requested changes
(j'ai pas tout relu)

Je request des changes parce que la double modale niveau UX c'est un peu wtf et imo faut le wipe. Y'a aussi le coup des authorizations que tu pourrais simplifier avec Pundit (cf un de mes coms).

<img width="981" alt="Screenshot 2023-11-02 at 18 24 43" src="https://github.com/etalab/admin_api_entreprise/assets/1279968/632680bb-780a-4b0e-a717-423e59261bc9">

<img width="920" alt="Screenshot 2023-11-02 at 18 24 47" src="https://github.com/etalab/admin_api_entreprise/assets/1279968/08371ce2-4e87-49d1-b078-996fefaa5200">

Les 2 CtA peuvent être direct sur le jeton, c'est plus simple 🤷

Ensuite niveau routes:

* `/tokens/:id/extend` -> ok, c'est logique (faudrait rename en `etendre` pour garder le français)
* `/tokens/:id/content` -> on est d'accord que c'est un show ici ? fondamentalement comme je dis plus haut imo cette route n'as pas lieu d'être
* `/tokens/:id/ask_for_extensions` -> niveau restful j'aurais fait `GET /tokens/:id/demande-extension` et `POST /tokens/:id/demande-extension` pour relancer par email (manque ce dernier on est d'accord ?)
* `/tokens/:id/use` => on est d'accord que c'est AUSSI un show ?

Les routes fait essayer de garder des trucs resftul simple pour que ça soit simple à étendre/tester. Genre le `demande-extension` ça pourrait être un `APIEntreprise::AskForTokenExtensionToDemandeurController` histoire de garder un truc kiss/simple

2023-11-02 17:37 UTC, skelz0r commented on app/controllers/concerns/tokens_management.rb
> +module TokensManagement
Bon clairement ici t'as ~ish refait du Pundit en moins bien 😅
Je me suis rendu compte que c'était déjà une dépendance, donc je t'invite à juste l'utiliser directement.

En gros ça donne:

```ruby
class TokenPolicy < ApplicationPolicy
  def initialize(user, token)
    @user = user
    @token = token
  end

  def extend?
    demandeur? and token.day_left < 90
  end
```

Dans le code du controller:

```ruby
  def extend
    authorize(@token)

    render 'shared/tokens/extend'
  end
```

Et dans les vues: 

```erb
<% if policy(@token).extend? %>
<% end %>
```

Pas impossible qu'il faille implémenter le catch de l'authorization, mais au moins c'est global.

2023-11-02 17:37 UTC, skelz0r commented on app/controllers/concerns/tokens_management.rb
> +  def extend_token
A rename en `extend`

2023-11-02 17:37 UTC, skelz0r commented on app/controllers/concerns/tokens_management.rb
> +  def extend_token
Ok j'ai le souci ici ahah.

Tu fais un `ExtendTokensController#new` ici

2023-11-03 09:00 UTC, Un3x commented
>     /tokens/:id/extend -> ok, c'est logique (faudrait rename en etendre pour garder le français)
>     /tokens/:id/content -> on est d'accord que c'est un show ici ? fondamentalement comme je dis plus haut imo cette route n'as pas lieu d'être
>     /tokens/:id/ask_for_extensions -> niveau restful j'aurais fait GET /tokens/:id/demande-extension et POST /tokens/:id/demande-extension pour relancer par email (manque ce dernier on est d'accord ?)
>     /tokens/:id/use => on est d'accord que c'est AUSSI un show ?
> 

Du coup après des points de synchro avec tout le monde :

- `Content` et `Use` vont être fusionné en une seule page
- `ask_for_extensions` renommé et laissé à cet endroit en attendant que l'on avance sur la partie formulaire de demande
- `extend` renommé
- La double modale laissée tel quel et il y aura une reprise de modale afin que ce ne soit qu'une seule modale et non une double à terme.

2023-11-06 13:28 UTC, skelz0r requested changes
Globalement:
1. Je pense que `prolong` et `prolonger` sont mieux que `extend` et `étendre`
2. Il y a le `TokensManagement` à clean avec les N rescue qui devraient être plus haut

Et des bricoles.

On est pas loin d'un truc clean là.

2023-11-06 13:28 UTC, skelz0r commented on app/controllers/concerns/tokens_management.rb
> +    redirect_current_user_to_homepage
```suggestion
```

2023-11-06 13:28 UTC, skelz0r commented on app/controllers/concerns/tokens_management.rb
> +  def extend_token
`prolong` ? en plus ça match le français de `prolonger`

2023-11-06 13:28 UTC, skelz0r commented on app/controllers/concerns/tokens_management.rb
> +  def ask_for_extension
```suggestion
  def ask_for_prolongation
```

si on reste consistant avec le reste

2023-11-06 13:28 UTC, skelz0r commented on app/controllers/concerns/tokens_management.rb
> +    redirect_current_user_to_homepage
```suggestion
```

et en vrai le `Pundit::NotAuthorizedError` tu rediriges vers /compte no matter what sans sommation avec un "Vous n'avez pas le droit d'effectuer cette action". A priori un user ne tombera jamais sur un lien qui trigger ça, donc c'est forcément quelqu'un qui aura fait un direct access.

2023-11-06 13:28 UTC, skelz0r commented on app/controllers/concerns/tokens_management.rb
> +    redirect_current_user_to_homepage
Idem ça imo faudrait que ça soit hook au niveau du ApplicationController

2023-11-06 13:28 UTC, skelz0r commented on app/policies/token_policy.rb
> +    !demandeur? and token.day_left < 90
```suggestion
    !demandeur? && token.day_left < 90
```

2023-11-06 13:28 UTC, skelz0r commented on app/policies/token_policy.rb
> +    demandeur? and token.day_left < 90
```suggestion
    demandeur? && token.day_left < 90
```

2023-11-06 13:28 UTC, skelz0r commented on app/policies/token_policy.rb
> +  end
```suggestion
  def demandeur?
    authorization_request.demandeur == user
  end

  def contact_technique?
    authorization_request.contact_technique == user
  end

  def contact_metier?
    authorization_request.contact_metier == user
  end
  
  def authorization_request
    @authorization_request ||= token.authorization_request
  end
```

2023-11-06 13:28 UTC, skelz0r commented on config/environments/development.rb
>  Rails.application.configure do
Je suis étonné que ça passe le linter: revert les suppression des espaces, les `do/end` étant des blocks valides.

2023-11-06 15:24 UTC, Un3x commented on config/environments/development.rb
>  Rails.application.configure do
Trop bizarre, c'est l'indentation de mon vim qui a fait ca oO

2023-11-06 15:49 UTC, Un3x commented on app/controllers/concerns/tokens_management.rb
> +    redirect_current_user_to_homepage
Ouais alors j'ai fais sauté le standard Error parce que ca n'avait pas trop de sens.
J'ai bien remonté le Pundit::NotAuthorizedError dans l'application controller. 

J'ai exploité cet erreur aussi pour afficher le cannot_show qui est l'autre version de la modale. À voir si c'est ok, je comprendrai qu'on voie ca comme un trick.

2023-11-06 16:09 UTC, Un3x commented on app/controllers/concerns/tokens_management.rb
> +    redirect_current_user_to_homepage
J'ai flip ces erreurs parce que elles ne servent pas ici.

2023-11-06 18:01 UTC, skelz0r approved these changes

2023-11-07 08:20 UTC, merged