[API Particulier] Ajoute section demonstrateur en page d'accueil
etalab/admin_api_entreprise pull request #1305
Opened 2023-10-31 15:55 UTC by DorineLam

Ajout d'un section en page d'accueil : 
<img width="1179" alt="image" src="https://github.com/etalab/admin_api_entreprise/assets/46896006/49bfdda3-b3cd-4fe6-999d-fec4b56e3b51">

2023-10-31 15:58 UTC, DorineLam commented
J'ai réussi à réaliser le composant de section, par contre c'est un échec car ça détruit complètement le layout du reste de la page  (les sections partenaires et dev sont complètement déstructurées) 

![image](https://github.com/etalab/admin_api_entreprise/assets/46896006/e295537f-6937-4d45-a693-732db71b090c)

2023-10-31 16:08 UTC, skelz0r commented
T'as du oublier de fermer une balise.

2023-11-03 10:16 UTC, DorineLam commented
Merci @skelz0r, effectivement c'était bien ça 😅

2023-11-03 10:52 UTC, skelz0r requested changes
Cf mes 2 changes, c'est du détail (à minima mettre le bon lien dans les locales)

2023-11-03 10:52 UTC, skelz0r commented on app/views/api_particulier/pages/home/_section_demonstrateur.html.erb
> +     <a href="https://demonstrateur.particulier.api.gouv.fr/" class="fr-btn fr-btn--lg fr-m-1w" target="_blank"><%= t('.demo_link_title') %></a>
```suggestion
     <%= link_to t('.demo_link_title'), t('.demo_link'), class: %w[fr-btn fr-btn--lg fr-m-1w], target: '_blank' %>
```

2023-11-03 10:52 UTC, skelz0r commented on config/locales/api_particulier/fr.yml
> +          demo_link: https://api-particulier-demonstrateur.osc-secnum-fr1.scalingo.io/
```suggestion
          demo_link: https://demonstrateur.particulier.api.gouv.fr
```

2023-11-03 15:20 UTC, DorineLam commented
ok merci ! Oui en effet, c'était pas propre.
Peux-tu revalider @skelz0r j'ai commité tes suggestions

2023-11-03 15:35 UTC, skelz0r approved these changes

2023-11-03 15:36 UTC, merged