scumbag typo
etalab/admin_api_entreprise pull request #1319
Opened 2023-11-08 14:21 UTC by Samuelfaure

2023-11-08 14:46 UTC, skelz0r requested changes
Tes tests ne testent pas le code effectif, mais tu mockes une méthode et tu testes que le mock renvoi bien ce que tu as mock.

2023-11-08 16:14 UTC, Un3x commented on spec/facade/entreprise_with_attestations_facade_spec.rb
> +  let(:attestations_scope_service) { instance_double(AttestationsScopeService) }
```suggestion
  let(:attestations_scope_service) { instance_double(AttestationsScopeService) }
```

2023-11-09 08:47 UTC, skelz0r approved these changes

2023-11-09 08:51 UTC, Un3x approved these changes

2023-11-09 08:51 UTC, merged