Feature/api 1465 je peux utiliser le sommaire pour naviguer dans la page
etalab/admin_api_entreprise pull request #1320
Opened 2023-11-08 16:10 UTC by Un3x

Partialisation de la partie side menu et breadcrumb.
Le premier commit est pas ouf, mais je suis obligé de faire un truc dans le genre pour conserver les pages existante ca va sauter quand je vais mass delete le contenu existant.

J'ai fais beaucoup d'essai sur le look-n-feel (même si on ne dirait pas) et j'ai eu quelques discussions avec dorine au sujet du side menu. Notament sur la numérotation et le highlight du side menu pour au final revenir à la version la plus basique proposée dans le dsfr.

J'ai pas testé le breadcrumb parce que il est assez statiques et je pense pas que ca risque grand chose.

2023-11-08 17:09 UTC, skelz0r requested changes
Le `resolve_layout` c'est brainfuck, faut itérer soit en changeant les noms des layouts, soit en faisant un side menu dynamique.

Et au passage `resolve_layout` c'est pas ouf, et tu peux juste faire ça:

```ruby
def show
  render 'show', layout: 'your_layout'
end
```

2023-11-08 17:09 UTC, skelz0r commented on app/views/shared/authorization_requests/_side_menu.html.erb
> +          <a class="fr-sidemenu__link" id="habilitation_main_token_infos_link" href="#habilitation_main_token_infos" target="_self">
tes liens se link à eux-même ? 😅

2023-11-09 08:14 UTC, Un3x commented on app/views/shared/authorization_requests/_side_menu.html.erb
> +          <a class="fr-sidemenu__link" id="habilitation_main_token_infos_link" href="#habilitation_main_token_infos" target="_self">
non y a un `_link` en plus sur l'id

2023-11-09 08:19 UTC, skelz0r commented on app/views/shared/authorization_requests/_side_menu.html.erb
> +          <a class="fr-sidemenu__link" id="habilitation_main_token_infos_link" href="#habilitation_main_token_infos" target="_self">
ah pardon j'avais pas les yeux en face des trous

2023-11-09 08:29 UTC, Un3x commented on app/controllers/api_entreprise/authorization_requests_controller.rb
> +  end
Ouais en fait c'est clairement la partie qui est bizarre de cette PR.

En gros cote api_entre on a un layout comprenant un side menu et non coté api part sur toute la partie `user_signed_in`.

Quand je vais supprimer toutes les pages inutiles, ce sides menu (et donc ce layout) ne sera plus utile  et il faudra tout faire sauter. Et tout ce resolve layout va disparaître vu que le side menu que j'ai fais n'est valable que pour une unique page, le show. 

J'ai pas voulu faire le side menu dans un layout parce qu'il sera présent que sur une seule page et il ne permet la navigation qu'à l'intérieur de la page.

Après on peut changer la facon de faire mon idée en faisant comme ca c'est que je n'aurais rien à modifier, que des choses à supprimer quand je ferais le switch (en tout cas niveau layout)

2023-11-09 08:33 UTC, skelz0r commented on app/controllers/api_entreprise/authorization_requests_controller.rb
> +  end
Je t'invite à supprimer cette méthode et faire un `render 'view', layout: 'my_layout'` comme ça c'est plus propre

2023-11-09 08:34 UTC, skelz0r commented on app/controllers/api_entreprise/authorization_requests_controller.rb
> +  end
Et à ce stade, pourquoi on ne migre pas ? Fonctionnellement on est iso ?

2023-11-09 08:38 UTC, Un3x commented on app/controllers/api_entreprise/authorization_requests_controller.rb
> +  end
À ce stade on a terminé cette page, en exploitant les informations qu'on a (il y a encore du taff mais sur des données que nous n'avons pas).

Il reste la page permettant de faire le listing des habilitations à faire. Une fois que c'est fait :dynamite:

2023-11-09 08:42 UTC, skelz0r commented on app/controllers/api_entreprise/authorization_requests_controller.rb
> +  end
Ok, je ferai une review plus poussé sur le clean donc

2023-11-09 08:43 UTC, skelz0r commented on app/controllers/api_entreprise/authorization_requests_controller.rb
> +  end
(et je t'invite btw à faire tourner avec le coverage activé post clean pour voir si y'a de la méthode morte au passage)

2023-11-09 11:20 UTC, Un3x commented on app/controllers/api_entreprise/authorization_requests_controller.rb
> +  end
Vu que c'est dans un concerns et que je dois soit partir sur api_entreprise soit api_particulier, c'est hyper relou vu que je peux pas interpoler le layout.

J'assume, j'enforce et je nettoie.

2023-11-09 13:14 UTC, merged

2023-11-09 13:26 UTC, skelz0r commented on app/controllers/api_entreprise/authorization_requests_controller.rb
> +  end
```ruby
render 'show', layout: "#{namespace}/application"
```

:}

2023-11-09 13:26 UTC, skelz0r commented on app/controllers/api_entreprise/authorization_requests_controller.rb
> +  end
Mais si c'est clean rapidement ça me va (dtf si je passe dessus je nettoierai si c'est pas fait)

2023-11-09 13:46 UTC, Un3x commented on app/controllers/api_entreprise/authorization_requests_controller.rb
> +  end
MAIS !@#$%%^@#$%^. J'arrête pas de me planter dans les "" d'interpolation. J'ai tester 
```ruby
`#{namespace}/application`
```

Foutu javascript