Mails/expiration notices
etalab/admin_api_entreprise pull request #1340
Opened 2023-11-17 10:23 UTC by Samuelfaure

fix https://linear.app/pole-api/issue/API-1632/rapatrier-mails-expirationnotice

2023-11-17 10:29 UTC, Samuelfaure commented
Note: cette PR me fait me rendre compte qu'il faudrait un test pour vérifier que les previews ne cassent pas, je me note de faire ça sur un nouveau ticket

2023-11-17 11:18 UTC, skelz0r requested changes
1. Où sont les tests ? Il manque un template (le J0) ça aurait été détecté ;
2. Ça ne fixe pas le ticket Linear, rien n'est branché => faut changer en `ref` et non `fix`

Vu que c'est assez simple ici (clairement moins de chose que la première PR avec les milles refactors) tu pourrais migrer aussi `ScheduleExpirationNoticeMailjetEmailJob` comme ça c'est fini et ça fixe vraiment.

2023-11-17 11:18 UTC, skelz0r commented on app/views/layouts/mailer.html.mjml
> +        font-size: 23px; line-height: 26px; font-weight: normal;
```suggestion
        font-size: 23px; line-height: 26px; 
        font-weight: normal;
```

2023-11-17 12:39 UTC, Samuelfaure commented on app/views/layouts/mailer.html.mjml
> +        font-size: 23px; line-height: 26px; font-weight: normal;
du mal à comprendre l'interêt de ce changement

2023-11-17 12:41 UTC, skelz0r commented on app/views/layouts/mailer.html.mjml
> +        font-size: 23px; line-height: 26px; font-weight: normal;
Ok en fait je me rends compte que t'as tout mis sur une ligne partout, j'ai juste mécaniquement changé là sans faire attention.

J'ai jamais vu ça nul part, les règles CSS sont systématiquement mis à la ligne à la suite d'un `;`. Pour moi faut fixer (dans une commit à part)

2023-11-20 08:58 UTC, skelz0r approved these changes

2023-11-20 08:58 UTC, skelz0r commented on app/jobs/concerns/mailjet_helpers.rb
![feels-good](https://github.com/etalab/admin_api_entreprise/assets/1279968/fcc48f6c-519f-4251-9709-ce05f26e1a7c)

2023-11-20 08:58 UTC, skelz0r commented on app/jobs/schedule_expiration_notice_email_job.rb
> +    }[expires_in]
Limite on pourrait rename `expiration_notice_0J_expired` en `expiration_notice_0J` et juste vérifier que la méthode existe sur le mailer.

2023-11-20 10:08 UTC, merged