Fixes after new admin deployment
etalab/admin_api_entreprise pull request #1352
Opened 2023-11-22 13:26 UTC by Un3x

2023-11-22 15:46 UTC, skelz0r requested changes
ça mériterait un test non ?

2023-11-22 15:49 UTC, Samuelfaure commented
J'ai link l'issue de Linéar (qui m'étais attribuée, du coup merci mais attention j'ai failli la faire aujourd'hui ;)

2023-11-22 16:05 UTC, Samuelfaure requested changes
Code bon mais même remarque

2023-11-22 17:55 UTC, Un3x commented
Alors il y a un test à cette feature qui est présent dans feat/api_entreprise.

Comme toutes les features de l'admin ne sont testé que d'un seul côté (soit côté api part soit api entreprise) je n'ai pas fais de modification sur les tests.

2023-11-22 17:57 UTC, skelz0r commented
Ça s'entend, j'ai tendance à systématiquement accompagner d'un test si je fixe quelque chose.

D'ailleurs je me dis que là on pourrait commencer à partager du code de tests et/ou auditer là où y'a des diffs pour harden tout ça.

2023-11-22 18:07 UTC, Un3x commented
> Ça s'entend, j'ai tendance à systématiquement accompagner d'un test si je fixe quelque chose.
> 
> D'ailleurs je me dis que là on pourrait commencer à partager du code de tests et/ou auditer là où y'a des diffs pour harden tout ça.

IMO je suis ok avec le fait d'avoir des tests sur ces écrans coté api entreprise ET api part, mais c'est clairement un sujet plus large que juste là le faire dans le test existant.

2023-11-23 09:00 UTC, Un3x commented
Bon du coup j'ai c/p le test de api entreprise coté api-part.
Faudra qu'on revoit ce système

2023-11-23 09:01 UTC, skelz0r commented
> Bon du coup j'ai c/p le test de api entreprise coté api-part. Faudra qu'on revoit ce système

T'aurais pu juste ouvrir un ticket et ditch le souci :D

2023-11-23 10:02 UTC, merged