Returning cas usage record instead of name
etalab/admin_api_entreprise pull request #1362
Opened 2023-11-27 13:53 UTC by Samuelfaure

Dans le cadre de ce ticket: https://linear.app/pole-api/issue/API-1714/rendre-les-cas-dusage-cliquables-dans-les-documentations-metiers

Je me dit que ça serait pas mal que Endpoint.use_cases renvoie l'objet CasUsage plutôt que juste le label du cas d'usage.

Ça sous entend de changer tous les fichiers de config pour remplacer les labels par les UIDs (+ autres changements techniques un peu relou) du coup je préfère que vous validiez l'idée de ce draft avant de m'y mettre.

Autre soucis possible: en console ça prend un petit moment de load les fichiers de config, j'ai peur que ça nous ralentisse en prod. WDYT?

2023-11-28 07:51 UTC, skelz0r requested changes
Faudrait en effet transformer ça en vrai relation, et déporter le listing des endpoints vers les cas d'usages, ce qui est largement plus cohérent.

Related https://github.com/etalab/admin_api_entreprise/issues/938 point 3.

2023-11-28 07:51 UTC, skelz0r commented on app/models/abstract_endpoint.rb
> +    use_cases_uid.map { |endpoint_use_case| "#{api.classify}::CasUsage".constantize.all.find { |use_case| use_case.uid == endpoint_use_case } }
Y'a un `.find` sur le modèle.

2023-11-28 07:51 UTC, skelz0r commented on app/models/abstract_endpoint.rb
> +  # pass cas_usage_uid instead here
Non, faut passer le modèle

2023-11-28 07:51 UTC, skelz0r commented on app/models/abstract_endpoint.rb
> +  # pass cas_usage_uid instead here
Et en vrai faut complètement revoir cette logique: c'est au niveau des cas d'usages qu'il faut renseigner les endpoints et non l'inverse.

2023-11-28 07:51 UTC, skelz0r commented on app/views/api_entreprise/endpoints/_use_cases.html.erb
> +      <% @endpoint.use_cases_records.each do |use_case| %>
Non faut passer `use_cases` ici

2023-11-28 07:51 UTC, skelz0r commented on config/endpoints/api_entreprise/1_insee_etablissements.yml
> +  use_cases_uid:
cf plus faut, faut tout déporter dans les use cases.

2023-11-28 12:11 UTC, Samuelfaure commented on app/views/api_entreprise/endpoints/_use_cases.html.erb
> +      <% @endpoint.use_cases_records.each do |use_case| %>
Oui en effet c'était mon intention

2023-11-28 12:12 UTC, Samuelfaure commented on config/endpoints/api_entreprise/1_insee_etablissements.yml
> +  use_cases_uid:
Ok donc on liste les endpoints dans les cas d'usage et pas l'inverse 👌

2023-11-29 13:57 UTC, Un3x commented on config/endpoints/api_entreprise/1_insee_etablissements.yml
> +  use_cases_uid:
Ouais c'est clairement une meilleure solution

2023-12-01 07:23 UTC, Samuelfaure commented
Pfiou pas compliqué cette PR mais relou à souhait

2023-12-01 07:53 UTC, skelz0r requested changes
3 points:

1. Rename la clé `AbstractCasUsage::CAS_USAGE_KEYS`
2. Faire du lazy sur les associations pour éviter de devoir reload à chaque fois
3. Je ne suis pas sûr que tes commits soient assez atomiques (genre depuis le premier les tests passent ?) c'est du "détail" mais si tu peux faire en sorte que tout soit green à chaque commit ça serait cool (limit tu peux tout squash sauf le dernier qui ajoute la fonctionnalitée effective)

2023-12-01 07:53 UTC, skelz0r commented on config/endpoints/api_particulier/cnaf_msa_complementaire_sante_solidaire.yml
> -  use_cases:
lol

2023-12-01 07:53 UTC, skelz0r commented on app/models/abstract_cas_usage.rb
> +  CAS_USAGE_KEYS = %i[
Cette clé devrait s'appeller `ATTRIBUTES` car c'est exactement ça dans le cadre d'un ActiveModel

2023-12-01 07:53 UTC, skelz0r commented on config/locales/api_entreprise/cas_usages_entries.fr.yml
> +        endpoints_forbidden:
c'est valide ça ? c'est pas censé être un `[]` ?

2023-12-01 07:53 UTC, skelz0r commented on app/models/abstract_endpoint.rb
> +    Kernel.const_get(api.classify)::CasUsage.for_endpoint(uid)
maybe en lazy ?

```
@use_cases ||=
```

2023-12-01 07:53 UTC, skelz0r commented on app/models/abstract_endpoint.rb
> +    Kernel.const_get(api.classify)::CasUsage.forbidden_for_endpoint(uid)
idem que plus haut

2023-12-01 10:08 UTC, Samuelfaure commented on config/locales/api_entreprise/cas_usages_entries.fr.yml
> +        endpoints_forbidden:
ça passe 🤷

2023-12-01 10:18 UTC, skelz0r commented on config/locales/api_entreprise/cas_usages_entries.fr.yml
> +        endpoints_forbidden:
```
3.2.2 :005 > YAML.load("---oki: []")
 => {"---oki"=>[]}
3.2.2 :006 > YAML.load("---oki:")
 => {"---oki"=>nil}
```

tu devrais forcer l'array vide imo

2023-12-01 11:02 UTC, Samuelfaure commented on config/locales/api_entreprise/cas_usages_entries.fr.yml
> +        endpoints_forbidden:
Tu conseilles de faire ça où? Créer un test d'acceptance?

2023-12-01 11:54 UTC, Samuelfaure commented on config/locales/api_entreprise/cas_usages_entries.fr.yml
> +        endpoints_forbidden:
dooone

2023-12-01 13:00 UTC, skelz0r commented on app/models/abstract_cas_usage.rb
> +  AbstractCasUsage::ATTRIBUTES = %i[
```suggestion
  ATTRIBUTES = %i[
```

2023-12-01 13:00 UTC, skelz0r commented on app/models/abstract_cas_usage.rb
> +  attr_accessor(*AbstractCasUsage::ATTRIBUTES)
```suggestion
  attr_accessor(*ATTRIBUTES)
```

2023-12-01 13:00 UTC, skelz0r commented on app/models/abstract_cas_usage.rb
> +        *AbstractCasUsage::ATTRIBUTES
```suggestion
        *ATTRIBUTES
```

2023-12-01 15:23 UTC, Samuelfaure commented
ah si je peux bypass

2023-12-01 15:23 UTC, merged