Ajustements UI compte utilisateur
etalab/admin_api_entreprise pull request #1371
Opened 2023-11-30 14:49 UTC by DorineLam

- Ajuste bouton vers le compte
- Règle la grille du tableau des habilitations et ajuste la taille des typos et des marges pour plus de lisibilité
- Layout et fond blanc pour les espaces habilitations et compte

2023-11-30 16:44 UTC, DorineLam commented
### Côté grid des habilitations :

Impossible de trouver comment faire vraiment une UI responsive avec le DSFR. J'ai donc choisi la version la plus propre et efficace sur desktop, et qui n'est pas complètement destructurée en mobile : 

@thomas, j'ai supprimé la version intermédiaire à deux colonnes qui rendait le contenu incompréhensible.

<img width="1151" alt="image" src="https://github.com/etalab/admin_api_entreprise/assets/46896006/b54faf2d-762a-41bd-bc83-7f0bc3eb4694">

<img width="474" alt="image" src="https://github.com/etalab/admin_api_entreprise/assets/46896006/5d27673e-bf32-4d65-8be2-76d3a0206977">

2023-11-30 18:04 UTC, DorineLam commented
#### Fix les marges et le fond de l'espace usager

<img width="1139" alt="image" src="https://github.com/etalab/admin_api_entreprise/assets/46896006/48556f40-c93b-4b49-b619-1a12b5ed99bc">

2023-11-30 18:04 UTC, DorineLam commented
#### Fix les marges et le fond de l'espace habilitations

<img width="1158" alt="image" src="https://github.com/etalab/admin_api_entreprise/assets/46896006/08eb2f0f-d068-41dc-970b-0c038099a0a2">

2023-12-01 10:31 UTC, Un3x requested changes
Cf coms, le reste is ok.

Pour le tableau on en avait parlé de vive voix et on est aligné donc ca me va.

2023-12-01 10:31 UTC, Un3x commented on app/views/shared/authorization_requests/index.html.erb
> +                <% elsif policy(authorization_request.token).prolong? %>
Je comprends ce changement mais je suis contre.
Pour moi on ne doit pas afficher les actions en attente de facon dépendante les unes des autres.
S'il y a un token à remplacer on affiche
S'il y a un token à prolonger on affiche
S'il y a autre chose on affiche

Si on est dans ces 3 cas en même temps, on affiche les 3 actions

Il ne faut pas que l'affichage des actions en attente soit conditionné par le fait qu'une autre action est déjà en attente.

2023-12-01 10:31 UTC, Un3x commented on app/views/shared/authorization_requests/index.html.erb
> +                <% else %>
Du coup je comprends que tu ai fait ca pour simplifier ici l'affichage de cet élément. mais je ne pense pas que ce soit la facon de le faire.

Je peux reprendre au besoin

2023-12-01 14:40 UTC, DorineLam commented on app/views/shared/authorization_requests/index.html.erb
> +                <% elsif policy(authorization_request.token).prolong? %>
Oui tu as raison 👍

2023-12-01 14:41 UTC, DorineLam commented
Vu avec Miryad, je vais changer "Contact principal" par demandeur pour ne pas créer une disjonction avec Datapass.

2023-12-05 07:51 UTC, DorineLam commented
Besoin de ta re-revue pour pouvoir merger :) @Un3x

2023-12-05 08:02 UTC, merged