Layout "no container" error 500 with Gaffe
etalab/admin_api_entreprise pull request #1406
Opened 2023-12-27 12:14 UTC by Samuelfaure

Testé en sandbox

Ça n'error plus, on obtient ça:

![image](https://github.com/etalab/admin_api_entreprise/assets/14159757/d421859a-c2d8-44cf-bbda-32fac2360dee)

Good enough?

2023-12-27 13:07 UTC, skelz0r requested changes
Pourquoi ? Y'a 0 test, 0 explication, 0 log. Faut dig et fixer en conséquence.

2023-12-28 13:26 UTC, Samuelfaure commented
J'avoue que je sèche ici.

- Les logs du serveur ne m'apprennent rien:

```
I, [2023-12-27T12:54:07.600215 #893868]  INFO -- : [ce328728-b0fb-41cd-bc4a-5514b7524000] Started GET "/ewjhdjawhduw" for <IP> at 2023-12-27 12:54:07 +0100
E, [2023-12-27T12:54:07.601391 #893868] ERROR -- : [ce328728-b0fb-41cd-bc4a-5514b7524000]
[ce328728-b0fb-41cd-bc4a-5514b7524000] ActionController::RoutingError (No route matches [GET] "/ewjhdjawhduw"):
[ce328728-b0fb-41cd-bc4a-5514b7524000]
I, [2023-12-27T12:54:07.602452 #893868]  INFO -- : [ce328728-b0fb-41cd-bc4a-5514b7524000] Processing by APIEntreprise::ErrorsController#show as HTML
I, [2023-12-27T12:54:07.602760 #893868]  INFO -- sentry: [Transport] Sending envelope with items [transaction, client_report] cf9571b9688943858789ea408bcef3ff to Sentry
I, [2023-12-27T12:54:07.604323 #893868]  INFO -- : [ce328728-b0fb-41cd-bc4a-5514b7524000]   Rendered layout layouts/api_entreprise/no_container.html.erb (Duration: 1.1ms | Allocations: 1165)
I, [2023-12-27T12:54:07.605282 #893868]  INFO -- : [ce328728-b0fb-41cd-bc4a-5514b7524000] Completed 500 Internal Server Error in 3ms (Allocations: 1834)
```

- J'ai rien coté Sentry
- Les tests de feature avec Capybara semblent impossible avec cette gem (CF leur README)
- Le test de request fonctionne / ne bug pas alors que ça ne devrait pas fonctionner

Si quelqu'un a une idée sur comment dig mieux que ça 🤷

2023-12-28 13:33 UTC, skelz0r commented
Doit y avoir quelque chose dans l'un des partials du layout qui n'est pas existant. Je check vite fait

2023-12-28 13:35 UTC, skelz0r commented
Je pense que `namespace` n'est pas défini (utilisé dans `app/views/shared/_matomo.html.erb`)

2023-12-28 13:36 UTC, Samuelfaure commented
Je vais jeter un oeil de ce coté

2023-12-28 13:36 UTC, skelz0r commented
le fix me semble trivial: faut hériter du bon controller.

2023-12-28 13:41 UTC, Samuelfaure commented
OK c'était bien ça: https://sandbox.particulier.api.gouv.fr/wdadwawdada

Par contre niveau tests on est OK de ne pas en avoir? C'est là-dessus que je coince surtout

2023-12-28 13:54 UTC, skelz0r commented
Faut faire avec, c'est pas bien grave.

2023-12-28 13:59 UTC, merged