Link to github test cases
etalab/admin_api_entreprise pull request #1408
Opened 2023-12-29 11:43 UTC by Samuelfaure

Ça fonctionne sauf pour certains repos dans siade_staging_data où on a écrit "diffusable" au lieu de "diffusible" - je vais faire une PR pour corriger ça.

Je met ça là pour le moment, à voir si @DorineLam veut changer à son retour :

![image](https://github.com/etalab/admin_api_entreprise/assets/14159757/04519171-5a67-4caf-b255-2dfa0510043b)

2023-12-29 11:59 UTC, Samuelfaure commented
Complexité ici: les noms dans siade_staging_data (diffusables) correspondent aux X-OperationID de SIADE.

Du coup... Soit on fait un mapping dégueux ici, soit on uniformise tout vers "diffusables"... Je préfèrerais uniformiser vers "diffusible" mais on peut pas se permettre un tel breaking change

2023-12-29 13:49 UTC, skelz0r requested changes
Je ne comprends pas comment cela peut fonctionner sans utiliser la même mécanique que la génération des dossiers dans le dépôt (ou le système de mock dans siade) qui utilise tous les 2 le même identifiant unique : le `operation_id`.

Cet `operation_id` est dans les swaggers sous la clé `x-operationId`, suffit de lookup ça:

```ruby
def test_cases_external_url
  "https://github.com/etalab/siade_staging_data/tree/develop/payloads/#{operation_id}"
end
```

et voilà 🤷

2023-12-29 13:53 UTC, skelz0r commented
> Complexité ici: les noms dans siade_staging_data (diffusables) correspondent aux X-OperationID de SIADE.

Et en fait, c'est ce qui fait que c'est simple :D

2024-01-03 08:51 UTC, Samuelfaure commented
💀

2024-01-03 09:31 UTC, Samuelfaure commented
Oops petit oubli de code mort atta

2024-01-03 10:05 UTC, skelz0r approved these changes
Clairement plus simple :D

2024-01-03 10:05 UTC, skelz0r commented on config/locales/api_entreprise/fr.yml
> +        test_cases: "Cas de test"
```suggestion
        test_cases: "Cas de tests"
```

non ?

2024-01-03 10:05 UTC, skelz0r commented on config/locales/api_particulier/fr.yml
> +        test_cases: "Cas de test"
```suggestion
        test_cases: "Cas de tests"
```

2024-01-03 10:19 UTC, merged