Feature/api 2029 email de transfert des habilitations
etalab/admin_api_entreprise pull request #1444
Opened 2024-01-26 15:08 UTC by Un3x

Il y a pas mal de chose dans cette PR.

J'aurais pu faire des découpages mais j'ai choisi de ne pas le faire parce que ca aurait été faux.

J'ai essayé d'aller au "best effort" vu que l'ensemble du processus est censé être repris avec datapass reborn.
Il y a un sujet que je n'aime pas trop c'est la redondance des tests entre api_particulier et api_entreprise. J'ai l'impression qu'on peut faire mieux, mais je n'ai pas particulièrement trouvé de solution (typiquement j'aurais aimé pouvoir lancer 2x les mêmes tests avec un app: %w[entreprise particulier]).

Bref, normalement avec tous les tests supplémentaires ca fonctionne.

2024-01-26 16:30 UTC, skelz0r requested changes
Fondamentalement c'est presque OK pour moi, mais je me dis que jarter `api` au profit de `namespace` simplifie un peu le code.

Pour la redondance des tests j'entends faudra potentiellement résoudre ça.

2024-01-26 16:30 UTC, skelz0r commented on app/controllers/api_particulier/sessions_controller.rb
> +  end
Tu peux le déporter dans `app/controllers/concerns/sessions_management.rb` vu que c'est le même code.

2024-01-26 16:30 UTC, skelz0r commented on app/controllers/concerns/transfer_user_account_management.rb
> +  end
Par rapport à mon 1e com: vu que tu l'utilises ici, le remonter là où est défini namespace (ou utiliser directement namespace ?)

2024-01-26 16:30 UTC, skelz0r commented on app/interactors/user/notify_datapass_of_token_ownership.rb
> +      "API#{context.api.classify}::UserMailer".constantize
Vis-à-vis de mon 2e commentaire (😅): passer directement namespace fonctionne.

```suggestion
      "#{context.namespace.classify}::UserMailer".constantize
```

2024-01-29 09:33 UTC, Un3x commented on spec/features/transfer_account_spec.rb
> +    visit api_particulier_user_profile_path
bien vu

2024-01-29 09:36 UTC, Un3x commented
> Fondamentalement c'est presque OK pour moi, mais je me dis que jarter `api` au profit de `namespace` simplifie un peu le code.
> 
> Pour la redondance des tests j'entends faudra potentiellement résoudre ça.

J'ai opté pour un partage de la méthode Api.
J'ai fais ca dans un commit à part étant donné qu'il y avait pas mal d'autres endroits dans le code qui pouvaient être clean avec ce changement aussi.

2024-01-29 09:41 UTC, skelz0r commented
Je trouve ton choix étrange, `namespace` fonctionne mieux et sans rajouter de code

2024-01-29 10:38 UTC, Un3x commented
Ok d'acc je passe sur namespace, ca me semblait plus pertinent niveau métier mais ca me va.

2024-01-29 10:45 UTC, skelz0r commented
> Ok d'acc je passe sur namespace, ca me semblait plus pertinent niveau métier mais ca me va.

On peut aussi full rename `namespace` en `api`. Fondamentalement `api` c'est `API Entreprise` ou `API Particulier`.
Tu peux aussi faire un alias.

2024-02-05 09:04 UTC, Un3x commented
Du coup c'est ok le merge ?

2024-02-05 09:05 UTC, skelz0r commented
Go

2024-02-05 09:36 UTC, merged