Api 2204 mails formulaire prolongation
etalab/admin_api_entreprise pull request #1473
Opened 2024-02-23 10:17 UTC by DorineLam

2024-02-23 10:27 UTC, DorineLam commented
@Un3x voici une première version des mails (fait que pour API Entreprise pour l'instant)
Est-ce que j'attends que tu structures tout ça  avant de continuer ? Je pense à : 
- Mettre dans le bon dossier
- Mettre les bons alias (Actuellement j'ai laissé autorization_request partout)
- Dupliquer pour API Particulier

2024-03-01 14:25 UTC, DorineLam reviewed
@Un3x j'ai fini normalement, 

- J'ai retiré le template du mail demande_valide_to_editeur
- J'ai ajouté le template brouillon en attente

2024-03-01 14:25 UTC, DorineLam commented on app/mailers/api_entreprise/authorization_request_mailer.rb
> +    update_embarquement_brouillon_en_attente
@Un3x J'ai donc ajouté le template du mail "brouillon en attente", mais je ne me suis pas occupée du fichier webhook

2024-03-04 15:37 UTC, Un3x commented
Vu qu'on a fait pas mal d'aller retour avec Dorine sur cette PR, j'ai squash les commits parce que c'était une galère à lire avec plein d'aller et retour.

Fondamentalement il y a 2 élément important : 
- La modification du context de l'organiser pour savoir si on est dans un flow d'update
- La modification de la configuration des emails liés aux webhooks pour faire la diff entre les template d'update ou non et l'impact dans le manager d'email.

Le reste c'est du templating, et des tests.

2024-03-04 15:53 UTC, Samuelfaure commented
J'attends que ça sorte du draft pour review

2024-03-04 16:35 UTC, Samuelfaure requested changes
Ya 2 trucs qui me chiffonnent un peu, je suis pas certain que faire mieux soit possible facilement mais je challenge tout de même

2024-03-04 16:35 UTC, Samuelfaure commented on app/interactors/datapass_webhook/find_or_create_authorization_request.rb
> +    !context.reopening || (context.reopening && %w[validate_application validate].include?(context.event))
imo ça devrait peut-être être dans la couche modèle ça

2024-03-04 16:35 UTC, Samuelfaure commented on app/interactors/datapass_webhook/schedule_authorization_request_emails.rb
> +  end
Douloureux à lire ici, possible de rajouter des méthodes pour un peu de sucre syntaxique?

2024-03-04 16:43 UTC, Un3x commented on app/interactors/datapass_webhook/find_or_create_authorization_request.rb
> +    !context.reopening || (context.reopening && %w[validate_application validate].include?(context.event))
Ouais alors, C'est effectivement une questions long shot.
Le truc c'est que nous on a pas vraiment à savoir si c'est une réouverture ou pas.
Techniquement ailleurs dans le code on se base sur le fait que l'authorization_request a dejà été validée ou non, mais c'est parce qu'on est AVANT l'update des données de l'authorization request.
Ici, on est après l'update, donc j'ai aucun moyen de savoir, c'est pour ca que je le passe via le contexte.

À voir, peut être que datapass reborn pourra mettre à jour sa payload de son webhook pour nous filer l'info sinon ? Ce serait le mieux IMO

2024-03-04 16:48 UTC, Un3x commented on app/interactors/datapass_webhook/find_or_create_authorization_request.rb
> +    !context.reopening || (context.reopening && %w[validate_application validate].include?(context.event))
À voir si ces mails n'ont pas tout simplement vocation a être géré dans datapass plutot que chez nous.

2024-03-04 16:51 UTC, Un3x commented on app/interactors/datapass_webhook/schedule_authorization_request_emails.rb
> +  end
fixed

2024-03-04 17:12 UTC, Samuelfaure commented on app/interactors/datapass_webhook/find_or_create_authorization_request.rb
> +    !context.reopening || (context.reopening && %w[validate_application validate].include?(context.event))
Tu as raison, les mails devraient clairement être coté Datapass et c'est un chantier à moyen-terme. Du coup mergeons comme ça.

2024-03-04 17:16 UTC, Samuelfaure commented on app/interactors/datapass_webhook/schedule_authorization_request_emails.rb
> +  end
```suggestion
  def with_a_reopening_template?(email_config)
    !email_config['on_update'].nil? && email_config['on_update']
  end

  def with_a_standard_template?(email_config)
    email_config['only_on_update'].present?
  end
```

(note que j'ai inversé l'ordre des méthodes pour respecter l'ordre d'apparition)

2024-03-04 17:18 UTC, Samuelfaure commented on app/interactors/datapass_webhook/schedule_authorization_request_emails.rb
> +  end
```suggestion

  def with_a_standard_template?(email_config)
    email_config['only_on_update'].present?
  end
```

+ bouge la méthode sous `with_a_reopening_template?` pour respecter l'ordre d'apparition

2024-03-04 17:20 UTC, Samuelfaure commented on app/interactors/datapass_webhook/schedule_authorization_request_emails.rb
> +  end
```suggestion
  def with_a_reopening_template?(email_config)
     email_config['on_update']
  end
```

2024-03-04 17:28 UTC, skelz0r commented on app/interactors/datapass_webhook/find_or_create_authorization_request.rb
> +    !context.reopening || (context.reopening && %w[validate_application validate].include?(context.event))
Pour moi on gère tout ou rien niveau email, niveau UX pour l'usager ça risque d'être brainfuck si on a des emails totalement différents.

2024-03-04 21:09 UTC, Samuelfaure commented on app/interactors/datapass_webhook/find_or_create_authorization_request.rb
> +    !context.reopening || (context.reopening && %w[validate_application validate].include?(context.event))
Ouais quand on migre sur datapass on vire ici.

2024-03-05 09:55 UTC, merged