Features/classic rails app
etalab/admin_api_entreprise pull request #150
Opened 2021-09-03 16:32 UTC by brindu

### Contenu de la PR 

Première étape de la refonte de l'outil d'administration / dashboard : migration de l'appli Rails anciennement en mode API ONLY vers du Rails classique (views and all).

D'après ce qui est recommandé, pour revert le mode API ONLY le procédé c'est de relancer `rails new` dans le repo des sources. Pour chaque fichier existant j'ai mergé manuellement les conflits, ça concerne surtout les fichiers de configuration. 

Les tests sont au vert et les vues sont en place (testé en accédant à _localhost:3000_).

2021-09-06 12:27 UTC, skelz0r requested changes
Bon globalement c'est juste un setup donc modulo les quelques remarques rien de plus à dire.

Quelques points en plus (dont le premier bloquant)

1. Quid du déploiement ? Y'a des assets à compiler maintenant, faut que ça soit présent dans le fichier
2. Vu qu'on a du webpacker maintenant (trop bien !....), imo faudrait mettre un Procfile pour le dev:
    ```
    web: bundle exec puma -C config/puma.rb
    worker: bundle exec sidekiq -v
    webpacker: ./bin/webpack-dev-server
    ```
3. Quid de la concurrence avec vue ? La config actuelle va fonctionner comment niveau nginx ? Comment on fait vivre les 2 apps ?

2021-09-06 12:27 UTC, skelz0r commented on Gemfile
> +  gem 'selenium-webdriver'
au lieu de selenium-webdriver je propose de mettre apparition https://github.com/twalpole/apparition -> c'est 100x plus robuste + ça marche sans aucune config sur du CI + c'est l'héritier de capybara-webkit

2021-09-06 12:27 UTC, skelz0r commented on Gemfile
> +  gem 'webdrivers'
a flipper si il y a apparition

2021-09-06 12:27 UTC, skelz0r commented on app/assets/stylesheets/application.css
> +/*
A rename en scss ici

2021-09-06 12:27 UTC, skelz0r commented on config/application.rb
> +require "rails/all"
Je suis tiraillé sur le fait de load action_mailbox, active_storage, action_text (entre autres), imo laissons comme ça on clean après.

2021-09-06 12:27 UTC, skelz0r commented on spec/concepts/user/operation/transfer_ownership_spec.rb
> +        expect(old_owner.reload.jwt_api_entreprise).to be_empty
très étrange que ça plante ça

2021-09-06 13:42 UTC, hugolepetit reviewed
Rien a raconter la dessus j ai pas encore remis le nez suffisamment dans webpacker pour etre competent. Je verrai a l'usage quand je vais refaire des vues.

Je plussoie le changement de driver indique par @skelz0r, selenium ca a jamais ete simple

2021-09-06 13:49 UTC, skelz0r commented
> j ai pas encore remis le nez suffisamment dans webpacker pour etre competent.

tkt @hugolepetit même après 3 ans dedans je comprends toujours rien.

2021-09-07 11:20 UTC, brindu commented
> 1. Quid du déploiement ? Y'a des assets à compiler maintenant, faut que ça soit présent dans le fichier 

Oui clairement il faut aussi update le script de déploiement 👍🏼 Dans cette PR je voulais surtout initier l'environnement de dev, je pense que le déploiement peut attendre un peu, il me faudra me plonger dans webpacker de toute façon. 

> 2. Vu qu'on a du webpacker maintenant (trop bien !....), imo faudrait mettre un Procfile pour le dev:

Ca m'a l'air bien oui, je me rends pas trop compte encore de l'utilisation de webpack/webpacker que l'on aura. 

> 3. Quid de la concurrence avec vue ? La config actuelle va fonctionner comment niveau nginx ? Comment on fait vivre les 2 apps ?

On va en rediscuter, j'étais parti sur une suppression de vue.js.

2021-09-07 11:21 UTC, brindu commented on Gemfile
> +  gem 'selenium-webdriver'
Alright 👍🏼

2021-09-07 11:22 UTC, brindu commented on config/application.rb
> +require "rails/all"
Ok.

2021-09-07 11:22 UTC, brindu commented on spec/concepts/user/operation/transfer_ownership_spec.rb
> +        expect(old_owner.reload.jwt_api_entreprise).to be_empty
Oui ça m'a surpris aussi 🤷🏼‍♂️

2021-09-07 11:59 UTC, skelz0r commented
> > 1. Quid du déploiement ? Y'a des assets à compiler maintenant, faut que ça soit présent dans le fichier
> 
> Oui clairement il faut aussi update le script de déploiement 👍🏼 Dans cette PR je voulais surtout initier l'environnement de dev, je pense que le déploiement peut attendre un peu, il me faudra me plonger dans webpacker de toute façon.

Pour le coup non je pense pas que ça puisse attendre, si on merge on n'aura pas une app déployable. Par contre ça me semble pas si compliqué: https://github.com/rails/webpacker/blob/master/docs/deployment.md#deployment

Premier paragraphe:

> Webpacker hooks up a new webpacker:compile task to assets:precompile, which gets run whenever you run assets:precompile. If you are not using Sprockets webpacker:compile is automatically aliased to assets:precompile. Remember to set NODE_ENV environment variable to production during deployment or when running the rake task.

2 approches:

1. Compilation sur le serveur: https://github.com/mina-deploy/mina-docs/blob/master/source/tasks/rails_assets_precompile.md + NODE_ENV + installation de node
2. Compilation en local: faut scp derrière du coup.

> > 2. Vu qu'on a du webpacker maintenant (trop bien !....), imo faudrait mettre un Procfile pour le dev:
> 
> Ca m'a l'air bien oui, je me rends pas trop compte encore de l'utilisation de webpack/webpacker que l'on aura.

Y'a juste besoin de mettre le code que j'ai mis dans un Procfile et faire `foreman run` et c'est fini.

2021-09-08 11:03 UTC, brindu commented
Je me suis débarassé de Webpack dans le dernier commit !

2021-09-08 15:40 UTC, skelz0r commented
@brindu je pense que tu devrais refaire une passe sur ton code, y'a encore du yarn and stuff + y'a encore webpacker dans le Gemfile

2021-09-08 16:34 UTC, skelz0r commented
Je close au profit de https://github.com/etalab/admin_api_entreprise/pull/152 qui a été mergé et review en pair avec @hugolepetit

2021-09-08 16:34 UTC, closed without merging