Feature/api 2773 les emails de webhook a x jours sont systematiquement
etalab/admin_api_entreprise pull request #1718
Opened 2024-11-06 09:08 UTC by Un3x

2024-11-06 10:31 UTC, skelz0r requested changes
cf mes coms

2024-11-06 12:07 UTC, Samuelfaure reviewed
Vu

Mêmes remarques que Loic

2024-11-07 08:56 UTC, Un3x commented on config/datapass_webhooks_particulier.yml
> -  created: &created {}
Alors je l'ai fais sauté parce que cet event était lié uniquement à un template qui a sauté, mais je peux le laisser vide aussi

2024-11-07 09:00 UTC, Un3x commented on config/datapass_webhooks_particulier.yml
> -  created: &created {}
fixed

2024-11-07 09:11 UTC, skelz0r approved these changes

2024-11-07 09:25 UTC, merged