Applying container to all redoc routes
etalab/admin_api_entreprise pull request #1743
Opened 2024-12-05 10:07 UTC by Un3x

2024-12-05 14:31 UTC, JeSuisUnCaillou approved these changes
Yeah, I guess :D

2024-12-05 16:56 UTC, skelz0r requested changes
y'a 2 commits ici : 1 pour le db/schema et le fix css

2024-12-06 06:39 UTC, Un3x commented
> y'a 2 commits ici : 1 pour le db/schema et le fix css

J'suis aller un peu vite ! j'vais ditch le schema :D

2024-12-06 06:58 UTC, skelz0r approved these changes

2024-12-06 09:30 UTC, merged