Partage de jeton via magic link
etalab/admin_api_entreprise pull request #202
Opened 2021-10-13 18:10 UTC by brindu

### Contenu de la PR 

- [x] Modale pour envoyer un magic link vers un jeton d'accès 
- [x] Récupération du jeton depuis un magic link 
- [x] Cacher les boutons / liens pour le destinataire non authentifié du magic link

2021-10-14 11:56 UTC, skelz0r requested changes
Cf mes coms.

Pour les i18n oubliés je vais ajouter une gem pour checker ça que j'utilise un peu partout sur mes projets ça évitera d'oublier

2021-10-14 11:56 UTC, skelz0r commented on app/controllers/public_token_magic_links_controller.rb
> +  def show
http://localhost:3000//tokens/show_magic_link

=> undefined method `+' for nil:NilClass

2021-10-14 11:56 UTC, skelz0r commented on app/controllers/public_token_magic_links_controller.rb
> +      render 'jwt_api_entreprise/index'
Je rendrais une vue spécifique qui embed le show comme il faut, en mettant potentiellement des disclaimers (genre durée de validité du magic link)

2021-10-14 11:56 UTC, skelz0r commented on config/routes.rb
> +  get 'tokens/show_magic_link', to: 'public_token_magic_links#show', as: :token_show_magic_link
J'aurais mis l'id dans l'url, en mode `/public/tokens/:id`

2021-10-14 11:56 UTC, skelz0r commented on app/controllers/restricted_token_magic_links_controller.rb
> +    if send_magic_link.success?
les 2 messages ne s'affichent pas chez moi
<img width="1278" alt="Screen Shot 2021-10-14 at 13 38 59" src="https://user-images.githubusercontent.com/1279968/137311082-03a8314d-0286-46d6-88c7-d0a61472943c.png">
<img width="1260" alt="Screen Shot 2021-10-14 at 13 38 39" src="https://user-images.githubusercontent.com/1279968/137311086-f9bc7dca-aab6-4fcf-b61f-bdf4d81c06a9.png">

2021-10-14 11:56 UTC, skelz0r commented on config/routes.rb
> +  get 'tokens/show_magic_link', to: 'public_token_magic_links#show', as: :token_show_magic_link
En fait je me rends compte qu'ici on doit à minima être rétro-compatible avec l'url de l'email et mettre du coup `/magic_link` => on peut dédoubler l'url ici.

2021-10-14 11:56 UTC, skelz0r commented on spec/features/create_magic_link_spec.rb
> +    click_button dom_id(token, :modal_button)
Vu qu'il n'y a pas de JS activé je pense que tu n'as pas besoin de cette ligne.

Par contre, je pense que ça pourrait être pas mal d'introduire un test en js pour vérifier que la modale fonctionne.

Ça donnerait un truc du style:

```ruby
subject do
    visit user_tokens_path
    click_button dom_id(token, :modal_button) if javascript_driver?
    within("#" + dom_id(token, :magic_link)) do
      fill_in 'email', with: email
      click_button
    end
  end

  describe "with js activate", js: true do
    it 'works'
  end
```

à la limite tu peux juste vérifier que le click button ouvre la modale aussi si on a pas envie de se faire chier

2021-10-14 11:56 UTC, skelz0r commented on spec/features/show_token_from_magic_link_spec.rb
> +  context 'when the magic link token does not exist' do
a la lumière de mon commentaire sur le controller, imo il faut tester `magic_token = nil`

2021-10-14 11:56 UTC, skelz0r commented on spec/helpers/feature_helper.rb
> +  include ActionView::RecordIdentifier
savage 😅

j'avoue pas con

2021-10-14 11:56 UTC, skelz0r commented on spec/helpers/feature_helper.rb
> +  include ActionView::RecordIdentifier
j'aurais fait un commit à part pour ça par contre pour le contexte

2021-10-14 16:35 UTC, brindu commented on app/controllers/restricted_token_magic_links_controller.rb
> +    if send_magic_link.success?
Yep j'avais pas renommé les clés après renommage des contrôleurs, c'est réglé 👍🏼

2021-10-14 16:39 UTC, brindu commented on spec/features/create_magic_link_spec.rb
> +    click_button dom_id(token, :modal_button)
Je peux faire ça, je suis encore frais avec les tests du JS en quoi ce que tu proposes permet de vérifier que la modale fonctionne ?

2021-10-18 14:59 UTC, skelz0r requested changes
Des petits trucs mineur principalement d'UX.

Merge direct après correction.

2021-10-18 14:59 UTC, skelz0r commented on config/locales/fr.yml
> +        title: Le jeton a été transféré avec succès.
On pourrait rappeler l'email ici (c'est mieux niveau UX)

2021-10-18 14:59 UTC, skelz0r commented on config/locales/fr.yml
> +        title: Une erreur est survenue lors du transfert du jeton.
Vu que la seule vraie erreur est un email non-valide, je pense qu'on pourrait préciser + mettre un truc du genre "si l'erreur persiste merci de contacter support@"

2021-10-18 14:59 UTC, skelz0r commented on app/views/public_token_magic_links/show.html.erb
> +<h2>Tokens de l'organisation</h2>
C'est pas logique je trouve de mettre ça, imo flip it ça sera plus clair

2021-10-18 14:59 UTC, skelz0r commented on config/routes.rb
> +  get '/magic_link', to: 'public_token_magic_links#show', as: :token_show_magic_link
C'est un peu legacy + pas augmentable cette route (demain si on veut partager d'autres ressources ça sera brainfuck niveau route).

Je laisserai ça cependant pour assurer la rétro avec la stack actuelle, mais je ferai un truc du genre `get '/public/tokens/:token` en plus pour après migrer là dessus

2021-10-18 14:59 UTC, skelz0r commented on config/locales/fr.yml
> +        title: Une erreur est survenue à la récupération du jeton.
Est-ce qu'on peut préciser un peu ici ? Le must serait de pouvoir préciser que le lien est périmé si c'est un vrai token, mais dans un premier temps pour faire kiss on peut préciser ("le jeton n'est peut-être pas valide ou le lien est peut-être expiré (durée de validité d'un lien = 24h), re-demandez un accès" un truc du genre).

2021-10-20 10:52 UTC, brindu commented
@skelz0r les trois derniers commits correspondent aux changements de tes dernières remarques si tu veux jeter un oeil. 

> Merge direct après correction.

Je merge

2021-10-20 10:53 UTC, merged