Page de statistiques
etalab/admin_api_entreprise pull request #216
Opened 2021-10-28 13:02 UTC by brindu

### Contenu de la PR

Page de stats d'utilisation des jetons sur le modèle de l'existant. 

Je n'ai pas repris la volumétrie des dix dernières minutes volontairement car le concept a changé en début d'année et le chiffre affiché n'est plus relevant. 

@skelz0r je te laisse juger si on peut ajouter du Hotwire quelque part :)

2021-11-02 11:30 UTC, brindu commented on spec/features/token_stats_spec.rb
> +  context 'when Watchdoge works' do
Yes c'est parce qu'on va migrer la partie Watchdoge plus tard que je me suis pas pris la tête avec l'implémentation.  Faudra revoir ça dans tous les cas à ce moment là, même l'interface de la classe va changer imo à ce moment là je pense pas qu'il y ait un gain immédiat à refactor et stub la classe et non le call HTTP.

2021-11-02 11:45 UTC, brindu commented
C'est rebase et les specs sont au vert ! 

J'ai resolve tes remarques vis à vis de la gestion des erreurs, j'ai juste pas changé le stub du call HTTP en stub de classe je pense pas que ça vaille le coup vu que l'implémentation sera à revoir soon. 

OK pour les frames, ça arrivera peut être plus tard du coup.

2021-11-08 08:37 UTC, skelz0r requested changes
Quelques retours/détails, tu peux fixer/merge imo.

2021-11-08 08:37 UTC, skelz0r commented on app/views/jwt_api_entreprise/stats.html.erb
> +  </div>
```suggestion
    <div class="fr-col-12 fr-pb-2w">
      <div class="fr-card fr-card--horizontal fr-card--no-arrow">
        <div class="fr-card__body">
          <h4 class="fr-card__title">
            <%= t('.title', title: @token.displayed_subject) %>
  
            <span class="fr-text--sm fr-m-0 pull-right">
              <%= link_to t('.links.user_tokens'), user_tokens_path, id: :user_tokens_link, class: %w(fr-link fr-link--sm fr-fi-arrow-right-line fr-link--icon-right) %>
            </span>
          </h4>
  
          <div class="fr-card__desc">
            <ul>
              <li>
                <span><%= t('.details.internal_id', id: @token.id) %></span>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
```

indentation

2021-11-08 08:37 UTC, skelz0r commented on app/views/jwt_api_entreprise/stats.html.erb
> +  <div class="fr-col-12 fr-pb-2w">
Idem ici, problème d'indentation (je peux pas faire le commentaire de bloc c'est trop gros)

2021-11-08 08:37 UTC, skelz0r commented on app/views/jwt_api_entreprise/stats.html.erb
> +</div>
```suggestion
```

je pense que cette div est en trop

Pour en être sûr fix déjà tous les problèmes d'indentation (ton IDE ne le fait pas tout seul ?)

2021-11-08 08:37 UTC, skelz0r commented on spec/features/token_stats_spec.rb
> +    describe 'calls rate' do
alors ce test passe, mais le bloc div est vide: c'est censé être quoi ? Pour moi il faut le laisser en pending si c'est encore en WIP sinon c'est clairement un faux positif.

2021-11-08 10:59 UTC, brindu commented on app/views/jwt_api_entreprise/stats.html.erb
> +</div>
> ton IDE ne le fait pas tout seul ? 

A 95% je dirai, parfois j'ai droit à des comportements chelous, genre ça (ou alors il y a toujours un soucis de balise quelque part dans ce cas précis) : 

<img width="564" alt="Capture d’écran 2021-11-08 à 11 50 01" src="https://user-images.githubusercontent.com/4283958/140729877-417be3a6-e9c9-4acc-96a2-2a81c7ae5c71.png">

2021-11-08 11:01 UTC, brindu commented on spec/features/token_stats_spec.rb
> +    describe 'calls rate' do
> Je n'ai pas repris la volumétrie des dix dernières minutes volontairement car le concept a changé en début d'année et le chiffre affiché n'est plus relevant. 

C'était censé être ça, c'est un oubli j'avais juste mis en place le squelette du HTML au début je supprime la la div vide et le test.

2021-11-08 11:25 UTC, brindu commented on app/views/jwt_api_entreprise/stats.html.erb
> +</div>
J'ai passé le HTML de la page dans un validateur, pas d'erreurs en vue aucune idée d'où vient le décalage... C'est fix à la mano.

2021-11-08 11:28 UTC, merged