Flip legacy API mode
etalab/admin_api_entreprise pull request #259
Opened 2021-12-14 17:09 UTC by brindu

### Contenu de la PR 

* Suppression des routes, contrôleurs, serializers, module d'authentification via JWT du mode API qui alimentait l'ancien dashboard Vue.js (à l'exception du webhook datapass) 
* Interactors au profit de TRB (toutes les opérations ont été supprimé) 
* Suppression des dépendances (trb, reform, dry-validation, ...) ; j'ai uniquement gardé Pundit que l'on devrait utiliser imo

2021-12-15 14:45 UTC, skelz0r requested changes
Ça manque d'organizer :p 

Y'a une route que t'as supprimée qui ne me semble louche.

2021-12-15 14:45 UTC, skelz0r commented on app/controllers/api_controller.rb
> +class APIController < ActionController::API
On pourrait limite le jeter et faire hériter direct `API::DatapassWebhooksController` de `ActionController::API` mais c'est du détail

2021-12-15 14:45 UTC, skelz0r commented on app/interactors/token/create_magic_link.rb
> +class Token::CreateMagicLink < ApplicationInteractor
Cette classe n'est pas bien nommée: elle crée ET envoie un magic pour un jeton. Cela pourrait être un organizer:

```ruby
# not sure du premier nom .. DeliverMagicLinkToToken peut être mieux
class Token::DeliverMagicLink < ApplicationOrganizer
  organize Token::CreateMagicLink,
           Token::SendEmailWithMagicLink
end
```

2021-12-15 14:45 UTC, skelz0r commented on app/interactors/token/notify_expiration.rb
> +class Token::NotifyExpiration < ApplicationInteractor
Cette classe est mal nommée, `SendExpirationNoticesForTokens` (ou `Token::SendExpirationNotices` si on veut garder le namespace) est mieux imo.

2021-12-15 14:45 UTC, skelz0r commented on app/interactors/user/transfer_account.rb
> +class User::TransferAccount < ApplicationInteractor
Ici il faut un organizer aussi imo:

```ruby
class User::TransferAccount
  organize FindOrCreateUser,
           TransferTokens,
           NotifyUserOfTokenTransfer
end
```
end

2021-12-15 14:45 UTC, skelz0r commented on config/routes.rb
> -  get '/magic_link', to: 'public_token_magic_links#show', as: :token_show_magic_link_legacy
Pourquoi ? Ça me semble être un controller valide, si ça passe les tests imo il faudrait rajouter un nouveau test pour ce comportement.

2021-12-15 14:45 UTC, skelz0r commented on spec/interactors/user/transfer_account_spec.rb
> +        expect(target_user.jwt_api_entreprise_ids.sort).to eq(transfered_jwt_ids.sort)
```suggestion
        expect(target_user.jwt_api_entreprise_ids).to contain_exactly(*transfered_jwt_ids)
```

un truc du genre (plutôt qu'un commentaire)

2021-12-15 14:45 UTC, skelz0r commented on spec/models/user_spec.rb
> +    describe '#email' do
Franchement ce genre de tests ça ne sert à rien imo, mais bon..

2021-12-29 09:37 UTC, skelz0r commented
Je reprend la main

2021-12-29 10:12 UTC, skelz0r commented on config/routes.rb
> -  get '/magic_link', to: 'public_token_magic_links#show', as: :token_show_magic_link_legacy
J'ai eu ma réponse dans le commit message

2021-12-29 10:33 UTC, skelz0r commented
Les changelogs par rapport à ta version @brindu : 

* J'ai commit le Gemfile.lock
* J'ai refactor tes N interactors en organizers, tout en gardant les tests seulement sur les organizers (si on repasse sur les interactors on fera des tests imo)
* J'ai introduit un dossier `organizers`

Vu que c'est green et que j'en ai besoin pour avancer je merge.

2021-12-29 10:33 UTC, merged

2022-01-04 11:05 UTC, brindu commented on app/interactors/user/find_or_create.rb
> +class User::FindOrCreate < ApplicationInteractor
Je trouve que le naming est pas opti ici : 
* l'implem est spécifique au transfert de compte notamment les naming `target_user` et `current_owner`
* il y a déjà une implem "FindOrCreate" _user_ dans la gestion des webhooks datapass et cet interactor ne pourrait pas être réutilisé. 

C'est du détail @skelz0r, je te laisse créer une issue si tu penses que ça vaut la peine ne serait-ce que de rename la classe en `User::FindOrCreateNewOwner` ou quelque chose du genre.

2022-01-04 11:20 UTC, skelz0r commented on app/interactors/user/find_or_create.rb
> +class User::FindOrCreate < ApplicationInteractor
En effet j'ai fait des organizers/interactors pour ranger ça de manière atomique sans vraiment réfléchir, t'as raison faut renommer.