Introduce FAQ page
etalab/admin_api_entreprise pull request #373
Opened 2022-03-31 14:40 UTC by skelz0r

* [x] Reindex sur la CI
* [x] Ouvrir/fermer les résultats
* [x] Finir d'implémenter les FAQs (contenu https://github.com/etalab/admin_api_entreprise/issues/357 )
* [x] Enhance le design
* [x] FIXER si il n'y a pas de résultat -> tout cacher
* [ ] ML car relou ? Cacher le titre de la rubrique si pas de résultat
* [x] Markdown: gérer les images et liens
* [x] Markdown: citations
* [x] Markdown: liens
* [x] Marlkdown: table
* [ ] Review

2022-04-05 10:18 UTC, DorineLam commented
Salut @skelz0r, 
Pour le contexte, j'ai ajouté des titres intermédiaires car la nouvelles FAQ contient bien plus de questions (contenu qui était auparavant sur d'autres pages). Le nombre de question pourrait encore augmenter.
On pourrait remettre en cause cette archi et se dire qu'on crée de nouvelles pages, et que la FAQ n'est qu'une porte d'entrée, donc moins de questions ... C'est possible mais ça n'est à mon avis pas la bonne solution pour l'utilisateur, car pour le coup, j'ai pas assez de contenu, ça va faire beaucoup de clics. Et plus, c'est relou à gérer pour nous (Car création de deux contenus (page +bloc FAQ)).

Faire des catégories, cela permet également d'alléger la tournure des questions en dessous, et de limiter les répétitions. Exemple : "demande d'habilitation" => "_Quelles infos me seront demandées ?_" Plutôt que "_Quelles informations me seront demandées dans ma demande d'habilitation ?_"

**Le parti pris est donc : une FAQ, qui pour plus de lisibilité voit son contenu classé dans des sous-parties.** C'est en plus une structure assez répandue. 

En somme, le problème ne vient pas, à mon sens, de l'archi de la nouvelle page, mais des conséquences de la recherche. J'imagine que si tu m'as envoyé ces messages, c'est que tu es probablement contraint dans ce que tu peux afficher ou non ...
Voici toutefois différentes idées que j'ai en tête : 
- Option 1, la meilleure : Quand aucune question d'une catégorie ressort. La catégorie est cachée. C'est exactement ce que l'on fait dans la doc générale actuellement => Tu peux tester ici avec le mot jeton https://entreprise.api.gouv.fr/doc/?entreprise.api.gouv.fr_documentation%5Bquery%5D=jeton
- Option 2, si la 1 n'est pas faisable techniquement, quand aucune question d'une catégorie ressort, on affiche le terme "Aucun résultat"
- Option 3, en dernier recours, la liste des questions qui correspondent à la recherche de l'utilisateur est affiché dans un volet qui apparaît sous la barre de recherche.

2022-04-05 10:21 UTC, skelz0r commented
L'option 1 dont tu parles est clairement faisable, c'est mon option 2., ce qui implique de ne pas ordonner par pertinence pour garder l'ordre des catégories.

On est d'accord sur ce point donc ?

2022-04-05 10:22 UTC, skelz0r commented
(et oui en effet c'est comme ça dans la doc générale actuellement)

2022-04-05 10:44 UTC, DorineLam commented
On est d'accord, Go pour ton option 2 (Option 1 de ma réponse) !

2022-04-06 14:38 UTC, DorineLam commented
> @DorineLam autre question: on ouvre bien les résultats si il y a une recherche ?

Oui ! :) comme ça on voit bien où c'est surligné

2022-04-08 12:09 UTC, skelz0r commented
@DorineLam tu peux checker ici: https://sandbox.dashboard.entreprise.api.gouv.fr/faq

Il manque un point: cacher le titre de la rubrique. C'est un peu chiant à faire en l'état..

2022-04-08 12:52 UTC, DorineLam commented
@skelz0r Merci 🤩 c'est super de voir les choses se concrétiser ! 
Mes retours :
- [Problème de recherche] Quand je fais une recherche, [volumétrie](https://sandbox.dashboard.entreprise.api.gouv.fr/faq?FAQEntry[query]=volum%C3%A9trie) les questions qui ne correspondent pas à la recherche restent affichées. Ce qui est bizarre, c'est que ça fonctionne très bien quand je mets "jeton"...
- [Responsive] quand je réduis l'écran en dessous de 760pixels environ, le menu des catégories en sidebar disparaît mais la colonne reste vide et prend de la place, c'est étonnant que le comportement responsive de ce composant est censé être celui-ci : https://gouvfr.atlassian.net/wiki/spaces/DB/pages/258998801/Menu+lat+ral+-+Side+menu#Responsive
- [Graphisme et couleurs] Quand est-ce qu'on pourra mettre le fond blanc et le main fond en dégradé ? C'est moins important mais j'aimerais que ça passe pas à la trappe, car c'est aussi un confort de lecture.


Je m'aperçois qu'il va falloir que je modifie quelques éléments dans le markdown, car il y a des problèmes d'affichage de contenu. Je vais me charger de cette partie et voir jusqu'où je peux aller.

2022-04-08 12:56 UTC, skelz0r commented
> [Problème de recherche] Quand je fais une recherche, [volumétrie](https://sandbox.dashboard.entreprise.api.gouv.fr/faq?FAQEntry%5Bquery%5D=volum%C3%A9trie) les questions qui ne correspondent pas à la recherche restent affichées. Ce qui est bizarre, c'est que ça fonctionne très bien quand je mets "jeton"...

En effet y'a un bug c'est étrange je check.

> [Responsive] quand je réduis l'écran en dessous de 760pixels environ, le menu des catégories en sidebar disparaît mais la colonne reste vide et prend de la place, c'est étonnant que le comportement responsive de ce composant est censé être celui-ci : https://gouvfr.atlassian.net/wiki/spaces/DB/pages/258998801/Menu+lat+ral+-+Side+menu#Responsive

J'ai pas du tout vérifié en responsive j'avoue, et pas impossible que j'ai oublié de mettre des classes je check.

> [Graphisme et couleurs] Quand est-ce qu'on pourra mettre le fond blanc et le main fond en dégradé ? C'est moins important mais j'aimerais que ça passe pas à la trappe, car c'est aussi un confort de lecture.

On parle bien du layout global que tu as designé pour toutes les pages ? Si oui je ferai ça à part imo vu que ça n'a pas grand chose à voir avec la FAQ.

2022-04-08 12:59 UTC, skelz0r commented
C'est réglé pour la volumétrie, c'était un souci d'indexation.

2022-04-08 13:00 UTC, DorineLam commented
Ok pour le fond, c'est effectivement le layout global, qui n'a pas forcement la même couleur selon les pages. Ok pas de soucis pour traiter ça plus tard.

2022-04-08 13:02 UTC, DorineLam commented
Pour modifier les éléments markdowns ça se passe où ? J'ai pas trouvé dans les fichiers modifiés.
Je m'interroge aussi sur comment pouvoir utiliser des composants un peu plus complexe comme les [highlights](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/223019199/Mise+en+exergue+-+Highlight)

2022-04-08 13:08 UTC, skelz0r commented
> Pour modifier les éléments markdowns ça se passe où ? J'ai pas trouvé dans les fichiers modifiés.

Tous les wordings sont dans `config/locales`, là t'as un fichier `faq_entries.fr.yml`

> Ok pour le fond, c'est effectivement le layout global, qui n'a pas forcement la même couleur selon les pages. Ok pas de soucis pour traiter ça plus tard.

Btw je l'ai pas fait à l'origine parce que ça me semblait assez compliqué de faire un layout en mode "lettre" couplé avec un grid système, j'avais vite fait essayer mais c'était le bordel (i.e. le grid fonctionnait pas). Faudra que je me repenche dessus.

> Je m'interroge aussi sur comment pouvoir utiliser des composants un peu plus complexes comme les [highlights](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/223019199/Mise+en+exergue+-+Highlight)

imo le plus simple est de définir un ensemble d'éléments graphique que tu veux appliquer en fonction des balises HTML de base utilisables avec du markdown.

exemple: les blockquotes (citation), utilisé la classe `fr-highlight`)

2022-04-08 13:12 UTC, DorineLam commented
> > Pour modifier les éléments markdowns ça se passe où ? J'ai pas trouvé dans les fichiers modifiés.
> 
> Tous les wordings sont dans `config/locales`, là t'as un fichier `faq_entries.fr.yml`

OK je vais tester :)

> > Ok pour le fond, c'est effectivement le layout global, qui n'a pas forcement la même couleur selon les pages. Ok pas de soucis pour traiter ça plus tard.
> 
> Btw je l'ai pas fait à l'origine parce que ça me semblait assez compliqué de faire un layout en mode "lettre" couplé avec un grid système, j'avais vite fait essayer mais c'était le bordel (i.e. le grid fonctionnait pas). Faudra que je me repenche dessus.

OK, s'il faut penser les choses un peu différemment, je peux aussi peut-être adapter les choses, on en rediscute quand tu t'y pencheras
> > Je m'interroge aussi sur comment pouvoir utiliser des composants un peu plus complexes comme les [highlights](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/223019199/Mise+en+exergue+-+Highlight)
> 
> imo le plus simple est de définir un ensemble d'éléments graphique que tu veux appliquer en fonction des balises HTML de base utilisables avec du markdown.
> exemple: les blockquotes (citation), utilisé la classe `fr-highlight`)

Oui c'est effectivement bien mieux. Je te fais une liste ? avec l'élément markdown et le composant que j'aimerais avoir en face ? je me demande s'il n'y a pas que les highlights d'ailleurs

2022-04-08 13:15 UTC, skelz0r commented
> OK, s'il faut penser les choses un peu différemment, je peux aussi peut-être adapter les choses, on en rediscute quand tu t'y pencheras

Je retesterai avant dtf, c'était juste pour le contexte histoire que tu l'aies en tête.

> Oui c'est effectivement bien mieux. Je te fais une liste ? avec l'élément markdown et le composant que j'aimerais avoir en face ? je me demande s'il n'y a pas que les highlights d'ailleurs

Yes je veux bien !

2022-04-08 15:37 UTC, DorineLam commented
Liste des éléments markdowns associés aux composants du DSFR : 

## Les citations markdown utilisent le composant `mise en exergue`
>Citation markdown.

La syntaxe par défaut affiche le [composant par défaut ](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/223019199/Mise+en+exergue+-+Highlight#Structure
) `fr-highlight`: 
<img width="601" alt="Capture d’écran 2022-04-08 à 17 08 25" src="https://user-images.githubusercontent.com/46896006/162470553-99b6efeb-5613-4fd2-813a-fc8b8a038a56.png">

La taille du texte de la mise en exerge est identique au corps de texte (taille MD).

**Il faudrait créer des variantes :**
Le DSFR ne propose pas de pouvoir modifier la couleur du texte, ce serait pourtant assez utile dans certains cas.

- Mise en exergue pour un contenu qui exige de l'attention : 
La barre de gauche est en red-marianne-main-472
Le texte est en red-marianne-700
<img width="690" alt="Capture d’écran 2022-04-08 à 17 16 05" src="https://user-images.githubusercontent.com/46896006/162472028-b1128951-13f7-40f1-993f-0a550121639f.png">

- Mise en exergue pour un contenu de type exemple : 
La barre de gauche est en gray-850
Le texte est en grey-425
<img width="735" alt="Capture d’écran 2022-04-08 à 17 18 53" src="https://user-images.githubusercontent.com/46896006/162473535-448b03a9-b752-4d04-9c23-31d40eb42349.png">

## Les liens 

Le lien standard markdown `[libelle](URL )` utilise le composant `Lien au fil du texte`
 => https://gouvfr.atlassian.net/wiki/spaces/DB/pages/217284725/Liens+-+Links#Lien-au-fil-du-texte
Ce qui est bizarre c'est que dans la doc, il est présenté comme étant souligné uniquement par hover, j'espère que ce n'est pas le cas. Autrement, je préfère simplement qu'on souligne.

Le lien markdown avec `target="_blank"` utilise le composant `Lien externe`
=> https://gouvfr.atlassian.net/wiki/spaces/DB/pages/217284725/Liens+-+Links#Lien-externe
Idem ici, il faut vraiment que le lien soit souligné. L'autre élément c'est l'ajout du picto "vers l'extérieur".

Il me faudrait pouvoir ajouter une clé pour créer deux variantes : 

- Le [lien simple](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/217284725/Liens+-+Links#Lien-simple) avec ajout du picto que je peux sélectionner
- Le [bouton](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/217284660/Boutons+-+Buttons#Bouton-primaire), avec le choix du type de bouton (fond bleu ou fond blanc) et le choix du picto

## Les tableaux markdown utilisent le composant `Tableau` 
=> https://gouvfr.atlassian.net/wiki/spaces/DB/pages/312016971/Tableau+-+Table#Tableau

2022-04-11 08:34 UTC, Samuelfaure reviewed
Y'a une variable qui me semble avoir été mal nommée par accident

Sinon les chaines de méthodes un peu longues je me demande si ça vaut pas la peine de les clarifier

Sinon ça semble bien

2022-04-11 08:34 UTC, Samuelfaure commented on app/controllers/faq_controller.rb
> +    @faq_entries_grouped_by_entries = FAQEntry.grouped_by_categories
Hum, c'est probablement une typo ici non? (entries grouped by entries)

2022-04-11 08:34 UTC, Samuelfaure commented on app/models/concerns/active_model_algolia_searchable.rb
> +          Array.wrap(values).include?(entry.public_send(key))
Pas super méga clair ici, on comprend mais faut réfléchir

2022-04-11 08:34 UTC, Samuelfaure commented on app/models/faq_entry.rb
> +            category: category[:name]
Pareil ici, y'a une longue chaine de méthodes et c'est ptetre ma gueule de bois post-elections mais j'ai du mal

2022-04-11 08:35 UTC, skelz0r commented on app/controllers/faq_controller.rb
> +    @faq_entries_grouped_by_entries = FAQEntry.grouped_by_categories
Oui clairement y'a une typo 😅 Je corrige

2022-04-11 08:37 UTC, Samuelfaure commented on app/assets/javascripts/controllers/algolia_search_with_accordion_controller.js
> +      _updateResults(controller, event) {
Cette méthode est quand même super longue... ça vaut pas le coup de factoriser?

2022-04-11 08:46 UTC, skelz0r commented on app/models/faq_entry.rb
> +            category: category[:name]
Là je vois pas, c'est quand même assez straightforward par rapport à l'implémentation du YAML, t'as une propal ?

2022-04-11 08:48 UTC, skelz0r commented on app/assets/javascripts/controllers/algolia_search_with_accordion_controller.js
> +      _updateResults(controller, event) {
Ouais je peux break en effet

2022-04-11 10:24 UTC, Samuelfaure commented on app/models/faq_entry.rb
> +            category: category[:name]
Je pense que la propal c'est que je boive un gros café et me concentre 2 secondes

En vrai si ça te parait clair tu peux laisser :smile:

2022-04-12 07:35 UTC, DorineLam commented
@skelz0r j'ai repéré un autre élément d'interface utilisateur qui est assez gênant : 
Quand on a ouvert le contenu d'une des questions d'une des catégories, et qu'on ouvre ensuite une autre question, dans la même catégorie, l'écran "saute". 
L'utilisateur n'est pas conduit vers le haut du contenu de la seconde question. 

Cet effet est du au fait que le comportement actuel, referme la question précédente, dont le contenu n'a pas forcément la même taille... et de fait le scroll effectué est décalé par rapport à la seconde question. D'où cette impression que la page "saute".

Est-il possible : 
- Soit de régler le scroll (c'est plutôt une bonne chose en effet de fermer les questions) ?
- Soit de ne plus fermer les questions ?

2022-04-12 07:39 UTC, skelz0r commented
> Est-il possible :
> 
> Soit de régler le scroll (c'est plutôt une bonne chose en effet de fermer les questions) ?
> Soit de ne plus fermer les questions ?

Le 1. c'est le DSFR, je peux pas vraiment modifier imo (et honnêtement je pense que c'est pas prévu pour accueillir autant de texte
Pour le 2. je pense que c'est faisable, faudrait que je creuse

Par contre @DorineLam j'ai tout réécrit en local pour fixer les tableaux and stuff du coup là je vais devoir force push ta modif.

2022-04-12 07:39 UTC, skelz0r commented
(et en fait ta modif est déjà prise en compte dans ma réécriture)

2022-04-12 07:41 UTC, skelz0r commented
> > Est-il possible :
> > Soit de régler le scroll (c'est plutôt une bonne chose en effet de fermer les questions) ?
> > Soit de ne plus fermer les questions ?
> 
> Le 1. c'est le DSFR, je peux pas vraiment modifier imo (et honnêtement je pense que c'est pas prévu pour accueillir autant de texte Pour le 2. je pense que c'est faisable, faudrait que je creuse
> 
> Par contre @DorineLam j'ai tout réécrit en local pour fixer les tableaux and stuff du coup là je vais devoir force push ta modif.

Je confirme que le 2. c'est possible, et le 1. y'a le même "bug" sur https://gouvfr.atlassian.net/wiki/spaces/DB/pages/312082509/Accord+on+-+Accordion 🤷

2022-04-12 07:53 UTC, DorineLam commented
> Par contre @DorineLam j'ai tout réécrit en local pour fixer les tableaux and stuff du coup là je vais devoir force push ta modif.

OK 🙌 mais ça veut dire que du markdown "simple" ne fonctionne pas ? Parce que j'ai effectivement vu le fichier dans config... le fichier n'a plus le même aspect, avec notamment des ajouts de sauts de ligne... Ce qui est assez complexe à gérer de mon côté car j'ai pas de vue sur le résultat et pas de  nomenclature non plus.
Intéressée de pouvoir en discuter avec toi après le point équipe, afin qu'on se synchronise et qu'on ne s'inflige pas mutuellement du travail en plus qui pourrait peut-être être évité 😊

> Je confirme que le 2. c'est possible, et le 1. y'a le même "bug" sur https://gouvfr.atlassian.net/wiki/spaces/DB/pages/312082509/Accord+on+-+Accordion 🤷

Oui c'est pas terrible d'avoir laissé ça dans le DSFR ... 🤔 Je pense qu'ergonomiquement c'est mieux donc de mettre en place le 2. On reviendra peut-être en arrière si le DSFR fixe l'UI ultérieurement. Merci

2022-04-12 07:57 UTC, skelz0r commented
A priori maintenant c'est du markdown simple, je suis allé creuser la spec (dégueu) du YAML pour que ça soit iso avec Github Flavored Markdown.

Pour ce qui est des itérations, dès que c'est fonctionnel je mergerai, dtf cette page n'est pour le moment pas public donc imo le mieux c'est de procéder de cette façon comme ça tu pourras itérer sans mon intervention.

Comme tu peux voir dans la todo il reste encore des choses à régler fonctionnellement, donc changer le contenu à ce stade est contre-productif.

2022-04-12 17:17 UTC, skelz0r commented
C'est dispo ici: https://sandbox.dashboard.entreprise.api.gouv.fr/faq

2022-04-13 08:22 UTC, Samuelfaure commented on app/models/concerns/active_model_algolia_searchable.rb
> +    private_class_method :values_includes_entry_attribute?
Du coup c'est quoi l’intérêt de mettre cette méthode en privé de cette façon?

2022-04-13 08:28 UTC, skelz0r commented on app/models/concerns/active_model_algolia_searchable.rb
> +    private_class_method :values_includes_entry_attribute?
Pour une méthode de classe dans un ActiveSupport::Concern c'est une des façons pour définir une méthode de classe privée (j'en ai déduis ça en lisant le code source).

A priori on peut faire autrement : https://api.rubyonrails.org/v6.1.4/classes/ActiveSupport/Concern.html#method-i-class_methods (mais je suis pas sûr que ça fonctionne en nested inclusion)

2022-04-13 09:38 UTC, DorineLam commented
@skelz0r merci pour le document de synthèse de la nomenclature markdown/dsfr 
C'est hyper clair, sauf deux éléments à la fin : 

- Pour les images, il faut que j'ajoute l'image dans un dossier, tu donnes en exemple `app/assets/images` est-ce que ce sera toujours dans ce dossier ?
- La partie "routes" n'est pas très claire pour moi, mais ce n'est pas bloquant du tout à ce stade. 

Je n'ai pas pu ouvrir la sandbox ... "The page you were looking for doesn't exist."

2022-04-13 09:43 UTC, skelz0r commented
> * Pour les images, il faut que j'ajoute l'image dans un dossier, tu donnes en exemple `app/assets/images` est-ce que ce sera toujours dans ce dossier ?

Oui toujours, tu peux ranger par dossier aussi, faudra juste mettre le chemin relatif. Par exemple si c'est dans `app/assets/images/faq/image1.png` il faudra mettre `<%= image_path('faq/image1.png') %>`

> * La partie "routes" n'est pas très claire pour moi, mais ce n'est pas bloquant du tout à ce stade.

Ouais en effet c'est pas ultra clair, surtout que ça demande que tu fasses tourner la stack. En gros dès que t'as tout installé tu lances `rails routes` et ça te sort un truc du genre (j'ai mis juste quelques exemples):

```
                           Prefix Verb     URI Pattern                                    Controller#Action
                     user_profile GET      /profile(.:format)                             users#profile
                      user_tokens GET      /profile/tokens(.:format)                      jwt_api_entreprise#index
              search_attestations POST     /profile/attestations/search(.:format)         attestations#search
                     attestations GET      /profile/attestations(.:format)                attestations#index
                  new_attestation GET      /profile/attestations/new(.:format)            attestations#new
          token_create_magic_link POST     /tokens/:id/create_magic_link(.:format)        restricted_token_magic_links#create
                      token_stats GET      /tokens/:id/stats(.:format)                    jwt_api_entreprise#stats
                            token GET      /tokens/:id(.:format)                          jwt_api_entreprise#show
                   token_contacts GET      /tokens/:id/contacts(.:format)                 contacts#index
            token_show_magic_link GET      /public/tokens/:token(.:format)                public_token_magic_links#show
      user_transfer_account_index POST     /users/:user_id/transfer_account(.:format)     transfer_user_account#create
        new_user_transfer_account GET      /users/:user_id/transfer_account/new(.:format) transfer_user_account#new
           authorization_requests GET      /authorization_requests(.:format)              authorization_requests#index
                        endpoints GET      /endpoints(.:format)                           endpoints#index
                 endpoint_example GET      /endpoints/*uid/example(.:format)              endpoints#example
                         endpoint GET      /endpoints/*uid(.:format)                      endpoints#show
```

Et de là, pour référencer par exemple le catalogue: `endpoints_path`, pour référencer une page de catalogue: `endpoint_path(uid: 'insee/unites_legales_diffusibles')`

Le routing est expliqué sur ce lien : https://guides.rubyonrails.org/routing.html (mais c'est un peu techos)

Je pense qu'en pratique je mettrai les principales, et tu copie/collera la logique pour linker vers les bonnes pages. L'avantage c'est qu'on est sûr que les liens seront toujours valides.

> Je n'ai pas pu ouvrir la sandbox ... "The page you were looking for doesn't exist."

Je re-déploie et te ping pour checker.

2022-04-13 09:50 UTC, skelz0r commented
@DorineLam tu peux check https://sandbox.dashboard.entreprise.api.gouv.fr/faq

2022-04-13 10:04 UTC, DorineLam commented
> @DorineLam tu peux check https://sandbox.dashboard.entreprise.api.gouv.fr/faq

Ça m'a l'air vraiment pas mal ! C'est bien mieux que les questions ne se referment pas.
J'aimerais faire quelques modifs dans le fichier du contenu (notamment mettre le bon schéma et la bonne couleur de hghlights.)
Est-ce que je peux faire un commit ?

2022-04-13 10:08 UTC, skelz0r commented
> J'aimerais faire quelques modifs dans le fichier du contenu (notamment mettre le bon schéma et la bonne couleur de hghlights.)
> Est-ce que je peux faire un commit ?

Comme je disais plus haut je pense que c'est mieux que je merge quand fonctionnellement c'est OK, et de là tu pourras ouvrir une nouvelle PR.

J'attends donc un go de @Samuelfaure ou @brindu pour merger (je sais pas si pour toi Samuel c'est OK vu que tu n'as ni approved ni denied).

2022-04-13 10:09 UTC, skelz0r commented
> Comme je disais plus haut je pense que c'est mieux que je merge quand fonctionnellement c'est OK, et de là tu pourras ouvrir une nouvelle PR.

Surtout qu'en pratique c'est pas vraiment "live" pour les gens, donc on a le temps de fine-tuner le contenu (notamment les liens manquants des pages manquantes, que j'ajouterai au fur et à mesure que c'est implémenté).

2022-04-13 14:50 UTC, Samuelfaure requested changes
J'ai fait une première passe mais y'a encore certains fichiers que j'ai écrémé (hello 200 lignes de javascript)

Je finis demain matin sauf si Alexandre passe avant

(je met en Request Changes pour bien dire que je ne valide pas encore)

2022-04-13 14:50 UTC, Samuelfaure commented on app/assets/javascripts/controllers/algolia_search_with_accordion_controller.js
> +        var credentials = document.querySelector("body");
Bon  c'est du détail mais cet var est mal nommée, si j'ai bien compris tu selectionnes tout le body et tu filtres au moment du return mais du coup ici ça devrait etre 'body' pas 'credentials'

2022-04-13 14:50 UTC, Samuelfaure commented on app/views/layouts/application.html.erb
> +    data-algolia-search-key="<%= Rails.application.credentials.algolia_search_api_key %>"
Tu préfères pas la notation `Rails.credentials[:algolia_search_api_key]` ?

2022-04-13 14:50 UTC, Samuelfaure commented on docs/tech-algolia.md
> +à moindre coup (sur du contenu de tout façon statique / open-source).
```suggestion
à moindre coup (sur du contenu de toute façon statique / open-source).
```

2022-04-13 14:50 UTC, Samuelfaure commented on docs/tech-algolia.md
> +données critiques, elles sont accessibles directement.
A lire ce paragraphe un noob de rails pourrait penser que toutes les clefs de production ne sont pas critiques, peut-être repréciser un peu

2022-04-13 15:11 UTC, skelz0r commented on app/views/layouts/application.html.erb
> +    data-algolia-search-key="<%= Rails.application.credentials.algolia_search_api_key %>"
Moi oui, rails non:

```
3.1.1 (main):0 > Rails.credentials
NoMethodError: undefined method `credentials' for Rails:Module
```

2022-04-14 07:03 UTC, skelz0r commented on app/assets/javascripts/controllers/algolia_search_with_accordion_controller.js
> +        var credentials = document.querySelector("body");
Une variable mal nommée n'est clairement pas du détail ;)

2022-04-14 07:06 UTC, skelz0r commented on docs/tech-algolia.md
> +données critiques, elles sont accessibles directement.
J'ai clarifié

2022-04-14 07:10 UTC, skelz0r commented
@Samuelfaure ok thx, j'ai corrigé tes 2/3 remarques.

Pour la lecture du code js, te fait pas trop chier imo, ce qui est important c'est que ça soit fonctionnel (y'a un test pour ça) que la config UI/UX soit OK, et que le code soit pas imbitable (mission quasi impossible, c'est du js ;p)

Si tu commences à te plonger dans chaque détail de la lib algolia t'es pas sorti non plus

2022-04-14 08:56 UTC, Samuelfaure approved these changes

2022-04-14 08:57 UTC, Samuelfaure commented
Green across the board :+1:

2022-04-14 09:40 UTC, skelz0r commented
ÇA PART EN PROD

2022-04-14 09:40 UTC, merged