Features/cross product jwt
etalab/admin_api_entreprise pull request #469
Opened 2022-05-12 17:00 UTC by Haelle

Pré-requis ; merger : https://github.com/etalab/siade/pull/103

Différents chantiers sont faits dans cette PR (attention les rebase...) : 
- renommage de `JwtAPIEntreprise` en `Token`
- renommage de `Role` en `Scope`
- on ne met plus le user UUID dans la payload des JWT
- on ajoute le UUID d'API Particulier dans la payload des JWT
- Ajout des scopes API Particulier à la bdd

Chacun dans un commit séparé

Question ❓:  pour les `Scope` j'ai ajouté une contrainte sur le nouveau champ `api` mais aussi sur les anciennes colonnes. J'ai mis ceinture et bretelle avec une validation ActiveRecord et une contrainte Postgres. On garde les deux ?

2022-05-12 17:04 UTC, skelz0r commented
> Question ❓: pour les `Scope` j'ai ajouté une contrainte sur le nouveau champ `api` mais aussi sur les anciennes colonnes. J'ai mis ceinture et bretelle avec une validation ActiveRecord et une contrainte Postgres. On garde les deux ?

On fait toujours les 2: contrainte hard pour l'intégrité, contrainte soft pour les jolis messages du framework.

Je relirai demain.

2022-05-13 05:39 UTC, Samuelfaure commented
J'aimais bien "roles" mais tant pis "scope" ça fait le taff

Pourquoi on ne met plus le user UUID mais en revanche on ajouter l'UUID API particulier?

2022-05-13 09:57 UTC, Haelle commented
@Samuelfaure on a viré le UID qui était le UUID du user, mais maintenant un jeton peut changer de propriétaire, donc ça n'a plus de sens.

Pour le nommage UUID API Particulier, c'est le jeton côté API Part qui est un UUID. On peut mettre `token_api_particulier`. Je ne voulais pas que ça soit trop explicite si quelqu'un ouvre le JWT, mais en fait je pense qu'on sen moque

2022-05-13 10:21 UTC, skelz0r requested changes
Y'a 3 gros points à tacler pour moi:

1: L'ajout du champ `api` dans le modèle Scope est un peu léger. Pour moi il faut aussi faire en sorte qu'un jeton soit associé à une API et que les rôles associés soit exclusivement de la même API.

2: Concernant les enhancements sur la payload du jeton: on fait ce qu'on veut ici, donc imo on devrait appliquer un bon gros compact sur notre jeton pour exclure les clés vides. Au passage `uid_particulier` est peut-être un poil générique, maybe `external_uid` ..? 
Ou sinon "extra_info" et tu colles le `api_particulier_uid` là dedans (un peu comme ce que fait le protocole OAuth), comme ça on ajoute ça dans notre table de jetons et basta plus besoin de faire des champs and stuff.

3: Les scopes pour moi devraient être en dur quelque part plutôt que dans une migration.

Quelques points supplémentaires:

* Le renaming de JwtAPIEntrepriseMailer en TokenMailer est à surveiller pour la MeP (je pense que c'est "safe" but still)

2022-05-13 10:32 UTC, Haelle commented on app/models/token.rb
> -      uid: user ? user.id : nil,
Ceci ne fonctionne pas en production côté siade ça plante. Je vais donc corriger ça d'abord côté siade

2022-05-13 12:22 UTC, skelz0r commented on app/models/token.rb
> -      uid: user ? user.id : nil,
imo on devrait laisser. Le user existe forcément non ? Ça nous permet aussi d'avoir une trace si par exemple le jeton est transféré et que la personne fait n'importe quoi.

2022-05-16 13:46 UTC, skelz0r commented on app/models/token.rb
> -      uid: user ? user.id : nil,
Dans ce cas là faudrait le tracker non ?

2022-05-16 14:10 UTC, Haelle commented on app/models/token.rb
> -      uid: user ? user.id : nil,
c'est pas urgent.

Fondamentalement, je ne fais pas de changement si j'ai pas une trace écrite, c'est une forme de traçabilité. 

Mais oui à terme ça serait bien qu'on garde une trace de ça oui.

2022-05-17 12:30 UTC, Haelle commented
> 1: L'ajout du champ `api` dans le modèle Scope est un peu léger. Pour moi il faut aussi faire en sorte qu'un jeton soit associé à une API et que les rôles associés soit exclusivement de la même API.

Je pensais voir ça au niveau de l'interactor dans une [seconde PR](https://3.basecamp.com/4318089/buckets/27091287/todos/4921294845) lorsqu'on travaillerait à l'intégration du webhook Datapass. Là tu sous-entend de mettre la vérification en ActiveRecord ?
 
> 2: Concernant les enhancements sur la payload du jeton: on fait ce qu'on veut ici, donc imo on devrait appliquer un bon gros compact sur notre jeton pour exclure les clés vides. Au passage `uid_particulier` est peut-être un poil générique, maybe `external_uid` ..? Ou sinon "extra_info" et tu colles le `api_particulier_uid` là dedans (un peu comme ce que fait le protocole OAuth), comme ça on ajoute ça dans notre table de jetons et basta plus besoin de faire des champs and stuff.

- [ ] Le compact n'avait pas de sens avant aujourd'hui, donc oui on peut l'ajouter
- [ ] renommer `uid_particulier` en `extra_info->api_particulier_uid` ça pourrait servir à autre chose

> 3: Les scopes pour moi devraient être en dur quelque part plutôt que dans une migration.

On peut en faire une tâche Rake ? WDYT ?

>     * Le renaming de JwtAPIEntrepriseMailer en TokenMailer est à surveiller pour la MeP (je pense que c'est "safe" but still)

Dtf je vais livrer en sandbox1 avant

2022-05-17 16:21 UTC, Haelle commented on db/migrate/20220512145924_add_api_to_scopes.rb
> +    change_column_null(:scopes, :name, false)
oui c'est safe, j'ai vérifié

2022-05-18 07:58 UTC, skelz0r commented
> > 1: L'ajout du champ `api` dans le modèle Scope est un peu léger. Pour moi il faut aussi faire en sorte qu'un jeton soit associé à une API et que les rôles associés soit exclusivement de la même API.
> 
> Je pensais voir ça au niveau de l'interactor dans une [seconde PR](https://3.basecamp.com/4318089/buckets/27091287/todos/4921294845) lorsqu'on travaillerait à l'intégration du webhook Datapass. Là tu sous-entend de mettre la vérification en ActiveRecord ?

Oui, voir même en SQL si possible (mais ça me semble un peu relou à faire).

> > 3: Les scopes pour moi devraient être en dur quelque part plutôt que dans une migration.
> 
> On peut en faire une tâche Rake ? WDYT ?

Bof, imo go le mettre dans le modèle Scope direct

2022-05-18 13:12 UTC, Haelle commented
> > Je pensais voir ça au niveau de l'interactor dans une [seconde PR](https://3.basecamp.com/4318089/buckets/27091287/todos/4921294845) lorsqu'on travaillerait à l'intégration du webhook Datapass. Là tu sous-entend de mettre la vérification en ActiveRecord ?
> 
> Oui, voir même en SQL si possible (mais ça me semble un peu relou à faire).

J'ai fais des trigger/procédure stockée en masse ça se fait très bien, mais c'est MORT ! ☠

> > On peut en faire une tâche Rake ? WDYT ?
> 
> Bof, imo go le mettre dans le modèle Scope direct

?! Donc on jette la table et on met tout en dur dans la classe (ou un autre fichier) ?

2022-05-18 13:15 UTC, skelz0r commented
Pour les scopes non, mais fondamentalement c'est intrinsèque au modèle, donc si c'est stocké quelque part je le mettrai là dedans avec une constante/méthode.

2022-05-18 13:29 UTC, skelz0r commented
> Qui ne serait utilisé que dans la migration du coup ?!

Dans un premier temps oui, mais après ça peut vivre ailleurs. Juste mon point là c'est que c'est de l'info importante, et là ca vit dans une migration ce que je trouve pas ouf. Mais après c'est pas critique.

2022-05-25 09:32 UTC, Samuelfaure commented
Repingez moi après les changements + rebase pour une nouvelle review

2022-05-25 09:33 UTC, Samuelfaure requested changes
Repingez moi après les changements + rebase pour que je relise

2022-05-25 09:39 UTC, Samuelfaure commented on app/models/token.rb
> -      uid: user ? user.id : nil,
Mes 2 centimes: @Haelle a raison point de vue technique, mais peut-être que laisser une trace indélébile du premier "responsable" du token peut mettre une certaine pression pour que les users fassent pas n'importe quoi avec ?

Genre "y'a ton nom gravé dans ce token, si il se retrouve dans la nature on saura immédiatement et sans ambages à qui il appartenait". Et être certain que le demandeur soit au courant.

Bref, j'ai pas d'avis tranché sur la question mais je pose ça là.

2022-06-06 15:50 UTC, Haelle commented
Pas mal de modifications depuis le dernier commit : 
- [X] commit qui vire l'UID du propriétaire du jeton supprimé (force pushed)
- [X] ajouter une clef 'extra_info' au jeton
  - qui sera renseigné avec 'api_particulier_uid' dans une prochaine PR (webhook Datapass)
- [X] ajouter un comptact dans la payload
- [X] mettre la liste des scopes en dur dans le modèle
  - [X] avec une seed
  - [X] mettre à jour la migration
  - [X] validate data/scopes files with specs !
- [X] rename migrations for easy ordering... (and easy rollback in case of deploy failure)
- [X] un jeton ne peut avoir des droits que sur une seule API
- [X] Rubocop fixes (j'ai pas compris pourquoi ces erreurs apparaissent maintenant ?!)

2022-06-06 17:21 UTC, Samuelfaure commented
Je review demain matin

2022-06-07 07:50 UTC, Haelle commented
@Samuelfaure @skelz0r vous pouvez ne regarder que les nouveaux commits, les autres n'ont pas bougés (sauf le commit supprimé) et ils sont bien séparé je pense

2022-06-07 08:30 UTC, Samuelfaure requested changes
Quelques remarques de style, mais 2 points bloquants :

- Pas le bon fichier YAML loadé à un moment
- La migration qui dépend d'un fichier externe ça me parait une source de gros problèmes potentiels

2022-06-07 08:30 UTC, Samuelfaure commented on app/models/token.rb
> +      extra_info:,
Je suis pas fan du tout du naming :sweat_smile: "extra info" c'est quand même ultra méga générique.

"meta" peut-être?... Pour le moment y'a que l'UID particulier dedans? d'ailleurs ça vaut vraiment la peine de se faire chier à le ranger là au final?..

2022-06-07 08:30 UTC, Samuelfaure commented on spec/models/scope_spec.rb
> +    it 'validates scopes for API Particulier' do
Faudrait pas aussi tester genre le nombre de scopes par hasard? Quitte à devoir MaJ si on en rajoute.

Je sais pas donc je pose la question innocemment.

2022-06-07 08:52 UTC, skelz0r commented on app/interactors/datapass_webhook/extract_mailjet_variables.rb
> +  def add_token_roles
Je suis d'accord, et pour moi ce n'est pas un détail, il faut le garder pour comprendre qu'au sein de notre application on manipule bien des scopes, dans le `context.mailjet_variables` il s'agit de l'environnement mailjet, qui a ses propres variables.

2022-06-07 08:53 UTC, skelz0r commented on app/models/token.rb
> +    payload.compact
Je suis pas sûr du compact ici. D'ailleurs le extra_info je mettrais un hash vide par défaut pour éviter tout potentiel problème.

2022-06-07 08:57 UTC, skelz0r commented on db/migrate/20220512160223_add_api_particulier_scopes.rb
> +    YAML.load_file(Rails.root.join('config/data/scopes/particulier.yml'))
Y'a 0 raison de run une migration dès que celle-ci est passée. Ce n'est donc pas un problème pour moi.

Par contre celle-ci doit être réversible: il faut un down où on fait un `destroy` des scopes d'API Particulier.
Et si on veut être vraiment safe: on peut faire un `find_or_create_by(hash)` dans le `#up`

2022-06-07 09:01 UTC, skelz0r commented on db/schema.rb
> +ActiveRecord::Schema[7.0].define(version: 2022_06_06_163450) do
Honnêtement je ne comprends pas à quoi cela sert. ActiveRecord::Migration trouve comme un grand les migrations à faire tourner, je n'ai jamais eu besoin de faire ce genre de manipulation.

Par contre un truc me chiffone, c'est de voir autant de changements dans le schema.rb. Chaque fichier de migration introduit dans un commit doit être accompagné de sa modification de schema. Ici si je comprends bien ce n'est pas le cas et des fichiers de migration sont dans des commits sans changement de schema ? Ce n'est donc plus atomique.

2022-06-07 10:14 UTC, Haelle commented on app/models/token.rb
> +      extra_info:,
et `extra_info` c'est un JSON `object` par une `string`

2022-06-07 10:18 UTC, Haelle commented on db/schema.rb
> +ActiveRecord::Schema[7.0].define(version: 2022_06_06_163450) do
Oui je confirme que `ActiveRecord` gère très bien ce genre de situation mais dans ce cas précis le rollback se passe TRÈS mal si on doit le faire.

La dernière migration manipule une table qu'ici je renomme... Donc rollback la dernière migration est impossible puisque `ActiveRecord` rollback chronologiquement et pas dans l'ordre dans lequel elles ont été ajoutée. Pour moi c'est essentiel de les renommer.

Par contre je suis d'accord que je peux faire un commit unitaire pour chaque migration, j'avais juste eu la flemme.

2022-06-07 10:20 UTC, skelz0r commented on db/schema.rb
> +ActiveRecord::Schema[7.0].define(version: 2022_06_06_163450) do
Ok soit.

> Par contre je suis d'accord que je peux faire un commit unitaire pour chaque migration, j'avais juste eu la flemme.

imo le mieux est de tout bundle dans une seule migration comme ça c'est "safe"

2022-06-07 16:45 UTC, Haelle commented
Seuls 2 commits ont été ajouté le reste c'est un rebase où j'ai viré toutes les occurrences aux migrations et au `schema.rb` afin que le commit avec la migration soit le seul à potentiellement manipuler la base.

2022-06-08 14:03 UTC, brindu requested changes
J'ai commencé à tagger tous les endroits où le terme "JWT" est encore présent et j'ai abandonné avant la moitié de la review. 

Il manque une bonne grosse passe de ag/find (pour les noms de fichiers) et de sed s/jwt/token/ partout.

2022-06-09 17:21 UTC, Haelle commented
@brindu j'ai resolve toutes les commentaires, c'était soit outdated avec le dernier commit soit le fichier avait été renommé.

2022-06-09 17:23 UTC, Haelle commented on config/data/scopes/entreprise.yml
> +  code: "certificat_agence_bio"
ça a été débattu et dans un premier temps on va maintenir ainsi. L'objectif serait de supprimer la table de configuration mais on ne pourrait plus accéder aux infos dans Metabase.

Mais oui c'est un peut contradictoire

2022-06-09 17:24 UTC, Haelle commented on db/migrate/20220607155825_migrate_to_cross_product_jwt.rb
> +    YAML.load_file(Rails.root.join('config/data/scopes/particulier.yml'))
il y a aussi un fichier de conf pour API Entreprise et ils sont tous les deux utilisés pour générer des seeds.

Ce qui fait foi en production c'est la BDD

2022-06-13 13:32 UTC, skelz0r commented on app/interactors/retrieve_token_stats.rb
> +    "https://dashboard.entreprise.api.gouv.fr/api/watchdoge/stats/token_usage/#{context.token_id}"
```suggestion
    "https://dashboard.entreprise.api.gouv.fr/api/watchdoge/stats/jwt_usage/#{context.token_id}"
```

Il s'agit de watchdoge

2022-06-13 13:34 UTC, skelz0r commented on app/lib/seeds.rb
> +    token.update(scopes:)
```suggestion
    token.update!(scopes:)
```

Sur des seeds on veut un shebang pour raise une erreur (et éviter les fails silencieux)

2022-06-13 13:38 UTC, skelz0r commented on app/models/contact.rb
Legacy ici à flip.

2022-06-13 13:39 UTC, skelz0r commented on app/models/user.rb
> +  has_many :token, through: :authorization_requests
Je suis peu fan du singularize ici. imo faut pluralize

```suggestion
  has_many :tokens, through: :authorization_requests
```

2022-06-13 13:43 UTC, skelz0r commented
J'ai review la couche modèle/métier (les tests and stuff sur du mass renaming pas vraiment d'intérêt).

Modulo le `has_many :token` qui est brainfuck et qui devrait être renommé en `has_many :tokens` c'est ok pour moi (sous réserve que tu aies testé la méga migration comme indiqué dans mon commentaire ofc).

2022-06-13 14:03 UTC, Haelle commented on app/mailers/user_mailer.rb
> +    @authorization_requests_ids = user.token.pluck(:authorization_request_id).map(&:to_i)
étrange en effet, du coup je vais faire la même chose sur les scopes

2022-06-13 14:07 UTC, Haelle commented on app/policies/user_policy.rb
> +  attr_reader :token_user
ça serait plutôt `user`, c'est le user qui est dans le JWT, le UUID. Je vais creuser l'usage de cette policy... je ne comprend pas à quoi ça sert...

2022-06-13 14:08 UTC, Haelle commented on db/migrate/20220607155825_migrate_to_cross_product_jwt.rb
> +class MigrateToCrossProductJwt < ActiveRecord::Migration[7.0]
oui moi aussi elle me fait peur, je compte over tester. C'est testé en local, je compte tester en sandbox avec un dump de production (~24h de logs)

2022-06-13 16:21 UTC, Haelle commented on app/policies/user_policy.rb
> +  attr_reader :token_user
dead code, burnt 🔥

2022-06-13 17:18 UTC, Haelle commented
rebased avec les derniers commits (les 4 derniers commits sont dû à la dernière review)

2022-06-15 09:25 UTC, Haelle commented
rebased

2022-06-16 10:23 UTC, brindu approved these changes

2022-06-16 12:17 UTC, merged