Draft: Page Cas d'usages
etalab/admin_api_entreprise pull request #514
Opened 2022-06-06 15:19 UTC by Samuelfaure

Il manque les liens corrects et c'est prêt pour review (ping @DorineLam faudra qu'on voit ça ensemble)

![image](https://user-images.githubusercontent.com/14159757/172191099-54d851ef-ed09-440d-8c7e-aa88121998c6.png)

2022-06-07 16:21 UTC, DorineLam reviewed
Merci @Samuelfaure 
Deux modifications : 
- Mettre la typo chapô pour le texte de description en intro 
- Est-il possible de réduire la taille des illustrations (laisser une plus grosse marge, et donc une plus grande surface de fond)

2022-06-08 09:05 UTC, Samuelfaure commented
C'est pas mal comme ça en effet 
![image](https://user-images.githubusercontent.com/14159757/172577826-d17e9351-b40b-485f-8a07-b04cfcc39f0b.png)

2022-08-03 13:19 UTC, Samuelfaure commented
![image](https://user-images.githubusercontent.com/14159757/182617857-95bcfc93-4110-4b70-abd6-d5cc20c30c25.png)

2022-08-03 13:20 UTC, Samuelfaure commented
@DorineLam Je te met la branche en sandbox

2022-08-03 14:09 UTC, DorineLam commented
@Samuelfaure Merci ! Voici mes retours : 

- Les boutons de l'en-tête "demander un accès" "liste des api utiles" ne fonctionnent pas.

- Les blocs des fiches cas d'usage qui ne sont pas en blancs ne ressortent pas du fond de page. Peux-tu essayer `background-alt-grey`?  j'ai testé dans mon navigateur, ça ne marche pas je ne sais pas pq. 

- Le bouton "Voir directement toutes les API utiles dans le catalogue avec leur documentation" ne fonctionne pas.

- Est-ce que le tableau des données est connecté directement aux cas d'usage ? je ne pense pas parce que c'est les anciens noms ^^

- Lettre d'information : le composant est ici :https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/lettre-d-info-et-reseaux-sociaux partie "Mise en avant de la lettre d’information" et doit se situer juste au dessus du footer dont il est solidaire.
<img width="738" alt="Capture d’écran 2022-08-03 à 16 08 54" src="https://user-images.githubusercontent.com/46896006/182629270-e0d4801b-aa08-4fb2-9e22-4e46696e0d85.png">

2022-08-04 06:51 UTC, Samuelfaure commented
> Est-ce que le tableau des données est connecté directement aux cas d'usage ? je ne pense pas parce que c'est les anciens noms ^^

Pour le moment non, il faut que je refasse entièrement les tableaux pour ça ^^ Je pense pouvoir faire ça aujourd'hui

2022-08-04 09:56 UTC, Samuelfaure commented
@DorineLam 

Concernant:

> Les blocs des fiches cas d'usage qui ne sont pas en blancs ne ressortent pas du fond de page. Peux-tu essayer background-alt-grey? j'ai testé dans mon navigateur, ça ne marche pas je ne sais pas pq.

Le background est déjà en background-alt-grey, je te laisse choisir une autre couleur pour les pages grises :)

2022-08-04 10:43 UTC, Samuelfaure commented
Je repasse en draft le temps de finir les taches de Dorine

2022-08-04 14:09 UTC, Samuelfaure commented
@DorineLam OK demandes faites, je push en sandbox

2022-08-04 15:00 UTC, skelz0r commented on app/models/endpoint.rb
> +    :anchor_openapi_path,
C'est déjà le taff de `Endpoint#tag_for_redoc` pourquoi avoir doubler ici ?

2022-08-04 15:01 UTC, skelz0r commented on app/views/pages/cas_usage.html.erb
> +        <%= image_tag("home/pictos/#{@cas_usage_tag}.svg", alt: @cas_usage_tag) %>
ce picto (et tous les autres da la page) ne sont pas bien placé -> `cas_usages/pictos` et non `home/pictos`

2022-08-04 15:02 UTC, skelz0r commented on app/models/endpoint.rb
> +    :use_cases_info,
Pourquoi avoir ajouté cette variable si elle est vide partout ?

2022-08-04 15:08 UTC, skelz0r commented on app/models/endpoint.rb
> +  def providers_as_records
C'est peu élégant, je changerai le constructeur pour affecter les providers de la fiche dans `provider_uids`, et faire une méthode `providers`:

```ruby
def providers
  Provider.filter_by_uid(provider_uids)
end

# Dans provider.rb

def self.filter_by_uid(uids)
  self.all.select do |provider|
    uids.include?(provider.uid)
  end
end
```

2022-08-04 15:10 UTC, skelz0r commented on app/models/endpoint.rb
> +  def provider_names
Le nom de cette méthode ne me semble pas correct.

Et dtf je pense qu'il serait mieux de faire ce join dans la vue.

Donc au choix:

1. Changer le nom en `provider_names_joined_with_ampersand`
2. Faire le join dans la vue

Pour moi la 2. >> 1.

2022-08-04 15:12 UTC, skelz0r commented on app/views/pages/cas_usage/_others.html.erb
> +  <% ["marches_publics", "subventions", "formulaire", "fraude"].reject { |item| item == current_use_case }.each do |use_case| %>
Cet array devrait être instancié dans le controller à l'aide du I18n: `I18n.t('cas_usages', raise: true).keys`

2022-08-04 15:12 UTC, skelz0r commented on app/views/pages/cas_usages.html.erb
> +    <div class="fr-card fr-enlarge-link">
ici clairement on veut faire une boucle avec `I18n.t('cas_usages', raise: true).keys`

2022-08-04 19:16 UTC, Samuelfaure commented on app/models/endpoint.rb
> +    :use_cases_info,
Dorine va la remplir^^

2022-08-04 19:31 UTC, skelz0r commented on app/models/endpoint.rb
> +    :use_cases_info,
Mais du coup je ne comprends pas à quoi cela fait référence: pour le moment c'est référencé dans `app/views/pages/cas_usage/_list-api.html.erb`, ça serait donc en toute logique lié un seul cas d'usage.

Si c'est le cas il y a 2 options: 1. soit le mettre dans le Endpoint (sous la forme d'un object `cas_usage_uid` => `string`), 2. soit dans les wordings de cas d'usage (avec un mapping inverse i.e. `endpoint_uid` => `string`).

Les 2 se défendent, cela dépend du caractère réutilisable de l'information. De ce que je comprends de l'architecture du site à priori ça ne serait qu'à un seul endroit, sur la page du cas d'usage. Si c'est le cas, la 2e option me parait mieux, car on édite dans un seul endroit la page (au lieu d'aller modifier le endpoint pour propager sur un cas d'usage).

2022-08-05 12:27 UTC, DorineLam commented
@Samuelfaure c'est sur sandbox ? Si oui je regarde cet aprem

2022-08-05 16:03 UTC, DorineLam commented
@Samuelfaure les noms des fournisseurs sont toujours les noms courts sur la sandbox, est-ce normal ?

2022-08-08 12:42 UTC, Samuelfaure commented on app/models/endpoint.rb
> +  def providers_as_records
Du coup plutôt que changer le constructeur (ce qui rajoute en complexité) j'ai modifié les fiches pour juste mettre "provider_uids" directement dedans, ça me parait plus correct sémantiquement

2022-08-08 12:43 UTC, skelz0r commented on app/models/endpoint.rb
> +  def providers_as_records
C'est ce que je proposais par "changer le constructeur" ^^

2022-08-08 12:46 UTC, Samuelfaure commented on app/models/endpoint.rb
> +    :use_cases_info,
Plus que ce point à tacler, faut que je check avec @DorineLam si j'ai bien compris son besoin (j'ai un doute):

**Première possibilité:** On veut 1 commentaire par endpoint qui doit être affiché dans toutes les fiches cas d'usage

Dans ce cas, ça fait sens de le mettre sur la fiche endpoint, sinon il faudrait pour chaque fiche cas d'usage dupliquer par nombre d'endpoint

(Si un endpoint correspond à 5 cas d'usage, il faut donc 5 entrées dans les 5 fichiers cas d'usage, il serait plus efficace d'avoir une seule entrée dans 1 fiche enpoint)

**Deuxième possibilité:** On veut 1 commentaire par endpoint ET par fiche cas d'usage

Dans ce cas, ça fait sens de le mettre sur la fiche cas d'usage, puisqu'il faut dupliquer de toute façon pour chaque endpoint

2022-08-08 12:52 UTC, skelz0r commented on app/models/endpoint.rb
> +    :use_cases_info,
Je reste assez convaincu que l'information ne sera de toute façon utilisée que sur la page du cas d'usage, autant tout modifier au même endroit du coup.

2022-08-09 05:59 UTC, DorineLam commented on app/models/endpoint.rb
> +    :use_cases_info,
Concernant le commentaire vide :
C'est effectivement l'option 2 décrite par @skelz0r qui était visée : à savoir un commentaire mis dans le cas d'usage uniquement.

L'idée c'est de contextualiser l'endpoint par rapport au cas d'usage.
À ce stade, je ne pense pas qu'on réutilisera cette info dans la fiche métier ... Mais maintenant que vous l'évoquez ... Je me demande si potentiellement ça peut être intéressant... En donnant des cas très concrêts ... Pour inspirer les prospects.

Mais bon en attendant, je crois vraiment qu'il faut privilégier la 2.

2022-08-09 07:10 UTC, DorineLam commented
@Samuelfaure je suis en train d'entamer une relecture complète des cas d'usage avant qu'on ne pousse en prod.

2022-08-09 07:18 UTC, DorineLam commented
@Samuelfaure ce serait possible d'ajouter une icone à côté de la mention "données protégées" ?
Comme celle-ci :
<img width="216" alt="Capture d’écran 2022-08-09 à 09 18 21" src="https://user-images.githubusercontent.com/46896006/183588302-eae0002c-9fdb-4dd5-8b0e-df6a81ba47af.png">

2022-08-09 07:33 UTC, DorineLam commented
@Samuelfaure c'est où que ça se passe si je veux ajouter les commentaires dans les données du tableau ?

2022-08-09 08:30 UTC, Samuelfaure commented on app/models/endpoint.rb
> +    :use_cases_info,
Ok le moyen de Skelzor était très simple à implémenter au final

2022-08-09 08:41 UTC, Samuelfaure commented
@DorineLam Je viens de push un commit avec une explication dans la doc sur comment faire

2022-08-09 08:55 UTC, Samuelfaure commented
@DorineLam J'ai une critique sur ton nouveau choix d'icone cependant: ça me parait pas accessible pour certains types de daltonisme, cf simulation:

![image](https://user-images.githubusercontent.com/14159757/183608044-65c77b8b-3145-467f-87aa-ad095c456ccb.png)

J'utilise https://www.color-blindness.com/coblis-color-blindness-simulator/

2022-08-09 09:03 UTC, DorineLam commented
> @DorineLam J'ai une critique sur ton nouveau choix d'icone cependant: ça me parait pas accessible pour certains types de daltonisme, cf simulation:

Oui tu as raison, 100%.
Bon je suis embêtée car le point je ne trouve pas ça assez clair ...

J'avais pensé à ça aussi : *️⃣ Un peu comme une astérisque de "facultatif" Qu'en penses-tu ?

2022-08-09 09:04 UTC, Samuelfaure commented
@DorineLam  Ça me parait une bonne idée :+1: Je m'occupe de changer ça

2022-08-09 09:05 UTC, Samuelfaure commented
@DorineLam Problème avec asterisque: Ça me parait pas UTF-8 compliant :thinking:

2022-08-09 09:08 UTC, Samuelfaure commented
OK c'est bon en fait, pushé en sandbox

2022-08-09 09:21 UTC, skelz0r requested changes
Il y a 2 petits trucs:

1. Une seule var d'instance dans le `show` (tout le reste est inférable de l'existant + ça sera plus rails way)
2. Fixer le micmac chelou du `comments_endpoints` (cf mon com sur le README qui simplifie++ le code/l'implémen)

Sinon c'est OK pour moi !

2022-08-09 09:21 UTC, skelz0r commented on app/controllers/cas_usages_controller.rb
> +    @cas_usage_name = I18n.t("cas_usages_entries.#{@cas_usage_tag}.name", raise: true)
Tu le sors avec `data[:name]`  donc pas besoin de le mettre dans une variable d'instance.`

2022-08-09 09:21 UTC, skelz0r commented on app/controllers/cas_usages_controller.rb
> +    @cas_usage_tag = params[:uid]
C'est le `uid` imo pas besoin de le stocker dans une var d'instance.

2022-08-09 09:21 UTC, skelz0r commented on app/controllers/pages_controller.rb
> +  layout 'no_container', only: %i[home cas_usages cas_usage]
tu peux revert ici

2022-08-09 09:21 UTC, skelz0r commented on app/controllers/pages_controller.rb
> +
Tu peux revert ici (chelou que ça soit là btw ..?)

2022-08-09 09:21 UTC, skelz0r commented on docs/wordings.md
> +        - "inpi/modeles": "commentaire à afficher"
```suggestion
      comments_endpoints:
        "insee/etablissements_diffusibles": "commentaire à afficher"
        "inpi/modeles": "commentaire à afficher"
```

comme ça dans le code plus haut:

```
@data[:comments_endpoints][endpoint.uid]
```

2022-08-09 15:33 UTC, Haelle requested changes
Sinon j'ai rien vu d'autre

2022-08-10 07:44 UTC, skelz0r commented
@Samuelfaure ça merge soon du coup ?

2022-08-10 08:21 UTC, DorineLam commented
> @Samuelfaure ça merge soon du coup ?

En attente de mes derniers commits par rapport au contenu :)

2022-08-10 08:23 UTC, skelz0r commented
Y'en a pour longtemps ? Parce que je suis entrain de préparer pour API Particulier et je change l'intégralité de l'archi là. Après c'est du contenu donc ça peut être fait dans une autre PR

2022-08-10 08:28 UTC, skelz0r commented
(d'ailleurs question peut-être con mais pourquoi tu ne fais pas qu'un commit ..?)

2022-08-10 08:58 UTC, DorineLam commented on config/locales/cas_usages_entries.fr.yml
> +          | **Les éditeurs proposant des solutions pour les aides et subventions publiques      |                    [Consulter la liste des éditeurs](<%= cas_usage_path(subventions(anchor: 'users'))
@Samuelfaure peux-tu vérifier ce lien ?

2022-08-10 08:58 UTC, DorineLam commented on config/locales/cas_usages_entries.fr.yml
> +          | **Les éditeurs proposant des solutions pour les marchés publics                     |                    [Consulter la liste des éditeurs](<%= cas_usage_path(marches_publics(anchor: 'user
Et celui-ci ? Objectif renvoyer vers la liste des éditeurs de ces cas d'usage

2022-08-10 08:58 UTC, DorineLam commented
@Samuelfaure modulo la revue des deux liens ci-dessus. C'est bon pour merger de mon côté.

2022-08-10 09:01 UTC, skelz0r commented
> @Samuelfaure modulo la revue des deux liens ci-dessus. C'est bon pour merger de mon côté. Peux-tu me pinguer quand c'est en prod ?

Je prends j'ai besoin de merger ça pour API Particulier.

2022-08-10 09:07 UTC, skelz0r commented
D'ailleurs @Samuelfaure je me rends compte que y'a 0 test 😅

2022-08-10 09:16 UTC, skelz0r commented
@Samuelfaure pour les prochaines faudrait séparer les devs, j'ai voulu rebase c'est pas très bien découpé + y'a une feature (NewsLetter) qui n'a rien à faire au milieu (et entremelé avec des "boyscout" qui ne sont pas vraiment des boyscout)

C'est dommage parce que les messages de commits sont inutiles et du coup l'historique ne sert à rien.

je vais merger comme ça du coup 🤷

2022-08-10 11:13 UTC, merged