V3/javascript anchors
etalab/admin_api_entreprise pull request #583
Opened 2022-06-30 07:53 UTC by Samuelfaure

A la demande de @DorineLam :

- Boutons pour copier les ancres de la FAQ
- En arrivant sur une ancre, ouvre l'accordeon correspondant au contenu

Il reste un peu de CSS à faire pour rendre notre designeuse contente mais prêt pour review

2022-07-01 07:35 UTC, DorineLam approved these changes
@Samuelfaure j'ai pas possibilité de faire tourner la PR en local ... Donc je ne peux qu’approuver les yeux fermés !

2022-07-01 08:12 UTC, skelz0r requested changes
Le split en 3 fichiers ne me semble pas justifié, cf mes commentaires.

2022-07-01 08:12 UTC, skelz0r commented on app/assets/javascripts/utils/generate_anchor_icons.js
> +window.addEventListener('load', function() {
Je transformerai ce utils en controller stimulus.

2022-07-01 08:12 UTC, skelz0r commented on config/initializers/assets.rb
> +  utils/auto_open_accordeon.js
Cf mon com plus haut-> je ne suis pas fan du multi fichiers.

2022-07-01 09:07 UTC, Samuelfaure commented on app/assets/javascripts/utils/generate_anchor_icons.js
> +window.addEventListener('load', function() {
Si tu veux mais je vois pas trop quels avantages à utiliser Stimulus ici?

2022-07-01 09:08 UTC, Samuelfaure commented on app/assets/javascripts/utils/auto_open_accordeon.js
> +window.addEventListener('load', function() {
Ça me semblait pas opti de load du javascript inutile partout mais sans doute je coupe trop les cheveux en 4

2022-07-01 09:10 UTC, skelz0r commented on app/assets/javascripts/utils/generate_anchor_icons.js
> +window.addEventListener('load', function() {
C'est plus propre et réutilisable (typiquement le `bigTitles` où les balises sont hardcodés, on pourra utiliser des stimulus target)

2022-07-01 09:11 UTC, skelz0r commented on app/assets/javascripts/utils/auto_open_accordeon.js
> +window.addEventListener('load', function() {
> Ça me semblait pas opti de load du javascript inutile 

On load TOUT le dsfr, on est pas à 3 lignes prêt imo

2022-07-01 09:42 UTC, Samuelfaure commented
Note: rajouter une notif au click du lien

2022-07-13 14:25 UTC, Samuelfaure commented
Ok je relis demain matin et ce sera prêt

2022-07-17 08:48 UTC, Samuelfaure commented
Ok ça me semble légit. Depuis la dernière review y'a eu:: 
- ajout de tooltip

2022-07-18 13:40 UTC, skelz0r commented
@Samuelfaure need review ici ?

2022-07-19 08:04 UTC, Samuelfaure commented
@skelz0r yes

2022-07-19 08:43 UTC, skelz0r requested changes
Quelques détails mais rien de bien méchant.

2022-07-19 08:43 UTC, skelz0r commented on app/assets/javascripts/utils/tooltip.js
> +function addTooltip(id, text) {
Pourquoi ne pas en faire un controller stimulus ?

2022-07-19 08:43 UTC, skelz0r commented on app/assets/javascripts/utils/tooltip.js
> +function addHideEvents(target) {
Ce nom de méthode est trop générique

2022-07-19 08:43 UTC, skelz0r commented on app/assets/javascripts/utils/tooltip.js
> +function hide(tooltip) {
Ce nom de méthode est trop générique

2022-07-19 08:43 UTC, skelz0r commented on app/assets/stylesheets/dsfr-extensions.scss
> +    color: #cfe2f3;
Cette variable n'est pas déjà définie dans le dsfr ?

2022-07-19 08:43 UTC, skelz0r commented on app/views/shared/_tooltip.html.erb
> +  <div id="arrow" data-popper-arrow></div>
cet id est trop générique

```suggestion
  <div id="tooltip-arrow" data-popper-arrow></div>
```

2022-07-19 08:43 UTC, skelz0r commented on config/initializers/assets.rb
> +Rails.application.config.assets.precompile += %w(application.js)
imo ça peut se revert ici

2022-07-20 09:21 UTC, Samuelfaure commented on app/assets/stylesheets/dsfr-extensions.scss
> +    color: #7f7fc8;
Non, apparemment @DorineLam utilise l'ancienne palette plus à jour (ça évolue vite x)

2022-07-20 09:36 UTC, Samuelfaure commented on app/assets/javascripts/utils/tooltip.js
> +function addTooltip(id, text) {
J'ai juste besoin d'une fonction à appeler dans un autre fichier (qui se trouve être un controller stimulus)

imho c'est davantage simple de faire juste une fonction JS vanilla

2022-07-20 09:36 UTC, Samuelfaure commented on app/assets/javascripts/utils/tooltip.js
> +function addTooltip(id, text) {
(je vais pas mentir y'a aussi une grosse part de flemme)

2022-07-20 09:41 UTC, skelz0r requested changes
Y'a des trucs en resolve non résolu (fail rebase ?) + une propale pour un stimulus param.

Modulo l'id trop générique du `arrow` c'est mergeable pour moi

2022-07-20 09:41 UTC, skelz0r commented on app/assets/javascripts/controllers/anchor_buttons_controller.js
> +        const bigTitles = document.querySelectorAll("h1, h2, h3, section")
J'en ferai un stimulus param histoire de rendre ça flex

2022-07-20 09:41 UTC, skelz0r commented on app/views/faq/index.html.erb
> +      <div class="fr-col-12 fr-col-sm-8 fr-col-md-9" data-controller='anchor-buttons'>
bah c'est pas resolve ?

2022-07-20 09:41 UTC, skelz0r commented on app/views/faq/index.html.erb
> +
idem, pourquoi c'est marqué en resolve ici ?

2022-07-20 09:41 UTC, skelz0r commented on app/views/shared/_tooltip.html.erb
> +  <div id="arrow" data-popper-arrow></div>
idem, pourquoi c'est marqué en resolve ici ?

2022-07-20 09:44 UTC, Samuelfaure commented on app/views/faq/index.html.erb
> +      <div class="fr-col-12 fr-col-sm-8 fr-col-md-9" data-controller='anchor-buttons'>
Bien vu le fail rebase lol

2022-07-20 10:21 UTC, merged

2022-07-21 13:40 UTC, skelz0r commented on app/assets/javascripts/utils/generate_anchor_icons.js
> +window.addEventListener('load', function() {
Pour info, ça ne marche pas si on vient d'une autre page (car `load` n'est effectué que sur le 1e chargement).