Bandeau bureau
etalab/admin_api_entreprise pull request #617
Opened 2022-07-19 13:45 UTC by Samuelfaure

- Mise à jour du DSFR

=> Il y a quelques bugs graphiques du coup... Je vais prendre une heure demain matin pour les chasser

- Ajout d'un bandeau avec la prochaine date de bureau ouvert 

A noter: le lien dans la bannière marchera quand on aura mergé https://github.com/etalab/admin_api_entreprise/pull/610

![image](https://user-images.githubusercontent.com/14159757/179764029-eb9ee1d0-0d6b-4f02-b8f3-cc86e0e45b23.png)

2022-07-19 13:52 UTC, skelz0r requested changes
Cf mes coms

2022-07-19 13:52 UTC, skelz0r commented on spec/services/open_bureau_date_spec.rb
> +RSpec.describe OpenBureauDate, type: :service do
ça ne teste pas tous les cas du code en unit

2022-07-19 13:52 UTC, skelz0r commented on app/services/open_bureau_date.rb
> +  def next_date
J'aurais renvoyer une date ici: c'est plus facilement manipulable dans la vue dans ce cas.

2022-07-19 13:52 UTC, skelz0r commented on app/services/open_bureau_date.rb
> +  def next_date_with_time
cette méthode me parait overkill, autant le faire dans la vue direct (avec i18n and stuff)

2022-07-19 13:52 UTC, skelz0r commented on app/services/open_bureau_date.rb
> +    false
```suggestion
  first_tuesday_after_beginning_month == next_tuesday ||
    (first_tuesday_after_beginning_month + 14) == next_tuesday
```

2022-07-19 13:52 UTC, skelz0r commented on app/services/open_bureau_date.rb
> +  def next_date
Une justification très simple: tu couples la langue (et donc la vue) avec cette classe (alors que c'est la responsabilité du controller et de la vue (i18n))

2022-07-19 14:25 UTC, DorineLam approved these changes
A la lecture de la capture d'écran, ça m'a l'air parfait :)

2022-07-20 09:43 UTC, skelz0r approved these changes
Modulo un micro truc (pas important imo) c'est OK

2022-07-20 09:43 UTC, skelz0r commented on config/locales/fr.yml
> +        banner_migration: Une question sur la migration vers la V3 ? Un tech et un métier vous répondent au <a href='/faq#quand-et-pourquoi-un-bureau-ouvert'>bureau ouvert du %{date} à 10 heures</a>.
ce `/faq` en dur c'est pas ouf (c'est du détail)

2022-07-20 09:43 UTC, skelz0r commented on docs/design.md
> +1. Remplacer le fichier `app/assets/javascripts/dsfr.module.js` par le fichier
ah ? intéressant, c'est quoi l'explication ?

2022-07-20 09:53 UTC, Samuelfaure commented on docs/design.md
> +1. Remplacer le fichier `app/assets/javascripts/dsfr.module.js` par le fichier
Y'a plus de fichier nomodule, ils ont remplacé par un fichier avec modules ¯\_(ツ)_/¯

Y'a quelques différences, mais en gros les modules c'est plus pratique bien que ça soit pas géré par les vieux browsers

2022-07-20 11:55 UTC, merged