Enhance/route
etalab/admin_api_entreprise pull request #655
Opened 2022-08-18 11:25 UTC by Samuelfaure

fix https://github.com/etalab/admin_api_entreprise/issues/652

2022-08-18 12:20 UTC, Samuelfaure commented on spec/acceptances/application_helper_spec.rb
> +RSpec.describe ApplicationHelper, type: :helper do
Je savais vraiment pas où mettre ça donc je l'ai mis dans spec/acceptance... Ça me paraissait le plus légitime du lot

2022-08-18 12:21 UTC, Samuelfaure commented on spec/rails_helper.rb
> +  config.include ApplicationHelper
J'espère que c'est permis pour tester les helpers :sweat_smile:

2022-08-22 07:37 UTC, skelz0r commented on spec/acceptances/application_helper_spec.rb
> +RSpec.describe ApplicationHelper, type: :helper do
`spec/helpers` 🤷

2022-08-22 07:39 UTC, skelz0r commented on spec/rails_helper.rb
> +  config.include ApplicationHelper
Un poil violent.

2022-08-22 07:41 UTC, skelz0r requested changes
Je mettrai les helpers d'url externes dans `app/helpers/external_urls_helpers.rb` histoire de séparer un peu.

De plus ça permet de faire ça dans le `rails_helper.rb` (moins violent):

```ruby
  config.include ExternalRoutesHelper, type: :feature 
```

ça limite aux tests d'inté, which is nice

2022-08-22 07:41 UTC, skelz0r commented on app/helpers/application_helper.rb
> +  def datapass_renewal_url(token)
Je passerai en argument la demande plutôt que le jeton.

2022-08-22 11:23 UTC, merged