Particulier/login contacts techniques
etalab/admin_api_entreprise pull request #739
Opened 2022-10-18 12:17 UTC by Samuelfaure

Partie 1 - Service pour récup une liste de tokens depuis un mail

2022-10-18 12:24 UTC, skelz0r requested changes
J'aurais fait un query object pour le coup (à placer soit dans `app/queries` soit dans `app/services` qui est plus générique).

Ce que j'entend par un query object: une classe qui prend des paramètres et renvoi un object `ActiveRecord::Relation`. 

Cela permet de respecter une interface classique rails, typiquement dans le `APIEntreprise::TokensController` on pourra remplacer ça:

```ruby
  def index
    @tokens = current_user.tokens.valid_for('entreprise')
  end
```

par ça:

```ruby
  def index
    @tokens = TokensAssociatedToEmailQuery(email: current_user.email)
  end
```

(un truc du genre)

Typiquement ici l'interactor n'a pas vraiment de sens (il n'y a pas vraiment de sens d'avoir un "success" ou "failure".

Au passage je pense que ça devrait pouvoir prendre le type d'API.

2022-10-24 10:15 UTC, skelz0r requested changes
J'ai proposé des optimisations SQL (parce que là clairement c'est pas foufou ^^)

A harden imo, je pense qu'on peut faire une seule requête SQL ici.

2022-10-24 10:15 UTC, skelz0r commented on app/services/tokens_associated_to_email_query.rb
> +      .where(contacts:)
```suggestion
    Token
      .joins(:contacts)
      .where(contacts: { email: })
```

2022-10-24 10:15 UTC, skelz0r commented on app/services/tokens_associated_to_email_query.rb
> +    Token.where(authorization_request:)
```suggestion
    Token.joins(:authorization_request, 'authorization_requests.users').where('users.email = (?)', email)
```

pas sûr de la syntaxe

2022-10-24 11:42 UTC, Samuelfaure commented
Merci pour les propositions! Tout ce qui est DB/SQL c'est mon plus gros point faible j'avoue

Par contre quand tu dis que là on fait plusieurs requêtes je m'interroge - Même si c'est découpé en plusieurs méthode, ActiveRecord ne factorise pas tout ça en une seule requête au final?

2022-10-24 11:46 UTC, Samuelfaure commented on app/services/tokens_associated_to_email_query.rb
> +      .where(contacts:)
On veut un `left_outer_joins` ici en fait je crois (le simple join ne passe pas les specs)

2022-10-24 11:49 UTC, skelz0r commented
> Même si c'est découpé en plusieurs méthode, ActiveRecord ne factorise pas tout ça en une seule requête au final?

Non, faut optimiser.

2022-10-24 11:51 UTC, Samuelfaure commented on app/services/tokens_associated_to_email_query.rb
> +    Token.where(authorization_request:)
L'idée est bonne mais ça rend la requête incompatible avec le `or` ci-dessus, faut d'abord que je vois si on peut faire une seule requête du coup

2022-10-24 12:57 UTC, merged