Login contact techniques/refactor magic link
etalab/admin_api_entreprise pull request #756
Opened 2022-10-27 13:09 UTC by Samuelfaure

Draft mais quasi-prêt, faut juste que je me relise un peu, fasse des tests manuels + 2-3 optimisations

**Changements dans la PR :**
- Nouveau modèle MagicLink, suppression des colonnes correspondantes dans le modèle Token
- Dans les interactors, on manipule maintenant l'objet MagicLink
- Le Magic Link étant lié à un email (et non plus à un token), on affiche maintenant tous les tokens liés à cet email (contact ou user)

2022-10-27 13:11 UTC, Samuelfaure commented on app/models/magic_link.rb
> +  before_save :generate_random_token
Je suis pas fan des callbacks (dans mon ancien taff ils en abusaient et c'était l'horreur absolue)

Mais dans ce cas de figure je pense que c'est OK

2022-10-27 13:13 UTC, Samuelfaure commented on app/views/token_mailer/magic_link.html.erb
> +    <p>Un lien vers votre ou vos jeton(s) d'accès vient d'être généré à votre intention. Vous pouvez accéder à ce jeton via le lien <%= link_to('suivant', @magic_link_url) %></p>
Rendu ce mail générique plutôt que ciblé API Entreprise, et ouvert une issue pour avoir un mail personnalisé pour chaque API plus tard => https://github.com/etalab/admin_api_entreprise/issues/755

2022-10-27 13:17 UTC, skelz0r commented
ça se lit commit par commit ?

2022-10-27 13:20 UTC, skelz0r commented on app/models/magic_link.rb
> +  before_save :generate_random_token
Ici c'est un `before_create` que tu veux btw

2022-10-27 13:25 UTC, Samuelfaure commented
@skelz0r Yes

2022-10-27 13:48 UTC, skelz0r requested changes
La lecture commit par commit été painful: tu flip du code en amont de l'introduction des nouvelles fonctionnalités, ce qui fait que ton code n'est pas fonctionnel sur certains commits, ce qui n'est pas clair du pourquoi. Tu aurais du introduire les fonctionnalités puis clean l'ancien (ou à la limite tout squash).

En lisant d'une traite c'est plus compréhensible en tout cas.

Sinon globalement:

1. La couche modèle doit être dans un seul commit.
2. Je suis plus fan du `expires_at` qui permet d'être plus flex et plus compréhensible à lire / potentiellement étendre.

Et vis-à-vis des emails, imo faut tacler ça à part, car il va falloir imo faire 2 AbstractMailer pou gérer Entreprise d'une part Particulier d'autre part (ne serait-ce que pour les sender emails).

A court terme clairement pas problématique.

2022-10-27 13:48 UTC, skelz0r commented on db/migrate/20221024133726_move_magic_link_from_token_into_own_model.rb
> +    remove_column :tokens, :magic_link_issuance_date, :datetime
Plutôt que de supprimer ces colonnes (et du coup potentiellement créer un problème pour les users ayant généré un magic link) il faudrait migrer ces données dans la nouvelle table.

2022-10-27 13:48 UTC, skelz0r commented on db/migrate/20221024133726_move_magic_link_from_token_into_own_model.rb
> +
espace à supprimer

2022-10-27 13:48 UTC, skelz0r commented on db/migrate/20221024133726_move_magic_link_from_token_into_own_model.rb
> +      t.integer :expiration_offset
ces 3 valeurs sont non null à priori

2022-10-27 13:48 UTC, skelz0r commented on db/migrate/20221024133726_move_magic_link_from_token_into_own_model.rb
> +      t.integer :expiration_offset
je suis plus pour un `expires_at` qui est clairement plus flex.

2022-10-27 13:48 UTC, skelz0r commented on app/models/magic_link.rb
> +class MagicLink < ApplicationRecord
imo il faut squash avec le premier commit

2022-10-27 13:48 UTC, skelz0r commented on app/models/magic_link.rb
> +    self.random_token = random_token_for(:random_token)
Histoire que ce soit flex-> `||=` (au cas où ça a été affecté).

2022-10-27 13:48 UTC, skelz0r commented on app/models/magic_link.rb
> +  end
Ceci est de la vue, à flip d'ici

2022-10-27 13:48 UTC, skelz0r commented on spec/models/magic_link_spec.rb
> +  let(:described_class_symbol) { described_class.name.underscore.to_sym }
Pourquoi ? 😅 c'est seulement utilisé plus bas, c'est moins lisible comme ça.

2022-10-27 13:48 UTC, skelz0r commented on spec/models/magic_link_spec.rb
> +  end
pas besoin de mettre `callbacks` ici, faut décrire le métier pas l'implem

2022-10-27 13:48 UTC, skelz0r commented on app/lib/seeds.rb
> +    create_api_particulier_token_valid
Pourquoi ?

2022-10-27 13:48 UTC, skelz0r commented on spec/factories/tokens.rb
> -    trait :with_magic_link do
Je laisserai ce trait pour ne pas trop modifier les tests de feature, en faisant la modif suivante:

```ruby
trait :with_magic_link do
  after(:create) do |token|
    create(:magic_link, email: token.user.email)
  end
end
```

2022-10-27 13:48 UTC, skelz0r commented on spec/organizers/token/deliver_magic_link_to_email_spec.rb
> +        expect(new_magic_link.created_at.to_i).to eq(creation_time.to_i)
ce test est useless: tu testes le framework rails.

2022-10-27 13:48 UTC, skelz0r commented on spec/models/magic_link_spec.rb
> +      after { Timecop.return }
J'aurais pas fait ces tests, clairement c'est du test de feature qui valide ces divers attributs

2022-10-28 10:15 UTC, Samuelfaure commented on spec/models/magic_link_spec.rb
> +      after { Timecop.return }
C'était surtout pour faire de la TDD j'avoue :sweat_smile: faire de la BDD ici m'aurait perdu assez vite imho

2022-10-28 10:18 UTC, Samuelfaure commented on spec/models/magic_link_spec.rb
> +  let(:described_class_symbol) { described_class.name.underscore.to_sym }
J'avoue je sais pas ce qu'il m'est passé par la tête lol

2022-10-28 10:19 UTC, skelz0r commented on spec/models/magic_link_spec.rb
> +      after { Timecop.return }
tu peux toujours le flip après avoir fini (en vrai as u ouiche ça m'est égal).

2022-10-28 11:45 UTC, Samuelfaure commented on app/lib/seeds.rb
> +    create_api_particulier_token_valid
Ça fonctionnait plus vu le refactor; je remet en place une création de token du coup

2022-11-03 10:46 UTC, skelz0r requested changes
Quelques détails, le point bloquant pour moi est le souci relevé sur `MagicLink #public_token_or_tokens`

2022-11-03 10:46 UTC, skelz0r commented on app/models/magic_link.rb
> +  def public_token_or_tokens(api: nil)
Je suis peu fan de cette interface, qui va à l'encontre du duck typing.

Si on veut manipuler cette interface, on se retrouve soit à faire un check de type (anti-pattern en ruby) soit à caster en array (`Array(magic_link.public_token_or_tokens)`), donc autant renvoyer directement un array.

Je renommerai donc en `#tokens` (on s'en fout in-fine que ça soit 1 ou plusieurs tokens sur la vue)

2022-11-03 10:46 UTC, skelz0r commented on app/models/magic_link.rb
> +  def generate_random_token
Bon, ici je me rends compte que c'est assez brainfuck d'avoir un `random_token` qui soit une chaîne de caractère ici ..

J'ai pas mieux en l'état là, peut-être `access_token` ..?

2022-11-03 10:46 UTC, skelz0r commented on app/controllers/api_entreprise/restricted_token_magic_links_controller.rb
> +    Token::DeliverMagicLinkToEmail.call(
```suggestion
    @organizer ||= Token::DeliverMagicLinkToEmail.call(
```

cela évite de le call potentiellement N fois

en vrai je préfère l'ancienne version qui est plus rails way

2022-11-03 10:46 UTC, skelz0r commented on app/interactors/token/create_magic_link.rb
> +      expires_at: context.expires_at || 4.hours.from_now
pourquoi mettre cette valeur ici alors qu'elle est déjà définie dans le modèle ?

2022-11-03 10:46 UTC, skelz0r commented on app/mailers/token_mailer.rb
> +    @magic_link_url = Rails.configuration.token_magic_link_url + magic_link.random_token
Faut refactor ça c'est très moche, pourquoi on n'utilise pas des routes ???

Dans la vue:

```
<%= token_magic_link_url(token: magic_link.token) %>
```

dans les routes faut ajouter de quoi gérer ça --^

2022-11-03 10:46 UTC, skelz0r commented on app/views/token_mailer/magic_link.html.erb
> +    <p>Ce lien est temporaire. Il est valable pour une durée de 4 heures pour une connection API Entreprise, ou 24h pour une connection API Particulier.</p>
Ici pourquoi ne pas prendre le `expires_at` et afficher la date de péremption exacte ?

2022-11-03 10:46 UTC, skelz0r commented on app/views/token_mailer/magic_link.html.erb
> +    <p>Un lien vers votre ou vos jeton(s) d'accès vient d'être généré à votre intention. Vous pouvez accéder à ce jeton via le lien <%= link_to('suivant', @magic_link_url) %></p>
Ici pourquoi ne pas utilise du i18n en pluralize ?

```yaml
sentence:
  one: Un lien vers votre jeton d'accès vient d'être ...
  others: Un lien vers vos jetons d'accès
```

```ruby
t('.sentence', count: tokens.count)
```

2022-11-03 10:46 UTC, skelz0r commented on db/migrate/20221024133726_move_magic_link_from_token_into_own_model.rb
> +    Token.where.not(magic_link_token: nil).each do |token|
je migrerai uniquement les jetons qui sont encore valides

2022-11-03 10:54 UTC, Samuelfaure commented on app/models/magic_link.rb
> +  def generate_random_token
autres propositions: `guest_token`, `public_token`

`access_token` me va très bien

2022-11-03 10:56 UTC, skelz0r commented on app/models/magic_link.rb
> +  def generate_random_token
partons sur access_token, ça suffira imo

2022-11-03 11:18 UTC, Samuelfaure commented on app/controllers/api_entreprise/restricted_token_magic_links_controller.rb
> +    Token::DeliverMagicLinkToEmail.call(
l'ancienne version me faisait une erreur rubocop à cause de la complexité donc je préfère laisser dans la méthode à part

2022-11-03 11:27 UTC, Samuelfaure commented on app/interactors/token/create_magic_link.rb
> +      expires_at: context.expires_at || 4.hours.from_now
Petit soucis ici, je veux qu'on puisse passer un expires_at à l'interactor, mais si je passe `expires_at: nil` ça tente d'outrepasser le default dans le modèle

Je peux faire ceci:

```
if context.expires_at.present?
  MagicLink.create(
        email: context.email,
        token_id: context.token_id
)
else
  MagicLink.create(
        email: context.email,
        token_id: context.token_id,
        expires_at: context.expires_at
)
end
```

Mais c'est pas très beau

Sinon je met la valeur `4.hours.from_now` dans une constante du modèle et je l'utilise ici, comme ça c'est pas répété sur 2 fichiers

2022-11-03 12:15 UTC, skelz0r commented on app/interactors/token/create_magic_link.rb
> +      expires_at: context.expires_at || 4.hours.from_now
Oui go constante.

2022-11-04 14:43 UTC, skelz0r reviewed
Des bricoles à fixer mais c'est OK sinon.

2022-11-04 14:43 UTC, skelz0r commented on app/controllers/api_entreprise/restricted_token_magic_links_controller.rb
> +    @organizer = Token::DeliverMagicLinkToEmail.call(
```suggestion
    @organizer ||= Token::DeliverMagicLinkToEmail.call(
```

sinon ça sert à rien d'affecter la variable (sauf si on la manipule derrière mais peu conventionnel)

2022-11-04 14:43 UTC, skelz0r commented on app/views/token_mailer/magic_link.html.erb
> +      <%= link_to('suivant', token_show_magic_link_url(host: @host, token: @magic_link.access_token)) %>
il est possible de tout mettre en une seule entrée i18n (et imo c'est mieux)

2022-11-04 14:43 UTC, skelz0r commented on config/locales/api_entreprise/fr.yml
> +            title: Lien magique expiré
```suggestion
            title: Lien expiré
```

🪄

2022-11-04 14:43 UTC, skelz0r commented on config/locales/api_entreprise/fr.yml
> +        others: Un lien vers vos jetons d'accès vient d'être généré à votre intention. Vous pouvez accéder à ce jeton via le lien
```suggestion
        other: Un lien vers vos jetons d'accès vient d'être généré à votre intention. Vous pouvez accéder à ce jeton via le lien
```

cela m'étonne que ça passe les tests ici

2022-11-04 14:43 UTC, skelz0r commented on db/migrate/20221024133726_move_magic_link_from_token_into_own_model.rb
> +    Token.active.unexpired.where.not(magic_link_token: nil).each do |token|
quand je parlais d'expiré je parlais de ceux ayant des magic link non expirés (c'est pas bien grave vu qu'on a peu de modèles)

2022-11-07 11:33 UTC, merged