Amelioration cas usage
etalab/admin_api_entreprise pull request #763
Opened 2022-11-01 08:39 UTC by DorineLam

Améliore le contenu des cas d'usage : 
- ajoute une section "exemple"

2022-11-01 08:45 UTC, DorineLam commented
@Samuelfaure, cette PR concerne les fiches cas d'usage. 

Je me demandais si c'était compliqué de modifier le tableau de façon à ce que les API dont le cas d'usage est marqué comme forbidden, ne soient pas affichées dans le tableau ?

Je pense que ça ce joue au niveau de cette ligne du fichier `_list-api.html.erb` ...
J'ai essayé de remplacer `all` mais ça ne fonctionne pas.

Merci pour ton retour.

https://github.com/etalab/admin_api_entreprise/blob/196559ae636d2607c16f2ca18146d023f0369079/app/views/api_entreprise/cas_usages/_list-api.html.erb#L15

2022-11-01 09:27 UTC, Samuelfaure commented
@DorineLam pas compliqué IIRC je m'en occupe dans cette PR stu veux

2022-11-01 10:24 UTC, DorineLam commented
> @DorineLam pas compliqué IIRC je m'en occupe dans cette PR stu veux

Oui je veux bien :) 🙏

2022-11-01 10:45 UTC, Samuelfaure commented
Fait dans commit https://github.com/etalab/admin_api_entreprise/pull/763/commits/1c28b8416fb41317dab9d2b393b23a2065c24f56

(@skelz0r si tu veux y jeter un oeil)

2022-11-01 12:45 UTC, DorineLam commented
@Samuelfaure j'ai eu un conflit mais normalement j'ai réussi à merger le tout. Cf mon commit de merge précédent :)

2022-11-01 15:19 UTC, Samuelfaure commented
@DorineLam Ah ma faute, j'ai réecris l'historique parce que j'ai changé mon commit, si je m'étais rappellé que y'avais une débutant de Git sur la branche j'aurais évité

2022-11-10 10:51 UTC, Samuelfaure commented
@DorineLam Que penses-tu de merger ça aujourd'hui quitte à ouvrir une nouvelle PR pour la suite? Les commits s'accumulent de ouf là :sweat_smile:

2022-11-11 08:47 UTC, DorineLam commented
> @DorineLam Que penses-tu de merger ça aujourd'hui quitte à ouvrir une nouvelle PR pour la suite? Les commits s'accumulent de ouf là 😅

Hello @Samuelfaure oui tu as raison, je boucle une version aujourd'hui comme ça tu peux merger lundi :)

2022-11-11 15:42 UTC, DorineLam commented
Quand  tu mergeras faudra pas tout de suite mettre en prod car je dois changer les données pré-cochées dans les cas d'usage et ajouter un formulaire Datapass pour le cas d'usage Portail GRU - instruction.

@Haelle si tu as le temps de regarder les données qui seront cochées dans les Datapass ce serait super. Ce sont les données qui sont "indispensables" dans le tableau

2022-11-12 15:13 UTC, Samuelfaure commented
@DorineLam Je préfère pas merger si ça bloque la livraison de prod du coup ^^`

2022-11-14 18:24 UTC, Haelle commented
@DorineLam la politique c'est que tout ce qui est mergé va en production sinon faut l'indiquer (et c'est au créateur de la PR de merger lui même comme ça il sait mieux quand il faut mettre en production).

À terme ça sera automatique, mais c'est plus compliqué pour nous que pour api.gouv.fr vu nos contraintes tech.

2022-11-14 18:33 UTC, Haelle requested changes

2022-11-14 18:33 UTC, Haelle commented on config/endpoints/12_bdf_bilans.yml
> +    - Aides & subventions publiques
C'est pas clair si on a le droit de le donner pour les MP et AP...

2022-11-14 18:33 UTC, Haelle commented on config/endpoints/13_dgfip_liasses_fiscales.yml
> +    - Aides & subventions publiques
C'est pas clair si on a le droit de le donner pour les MP et AP...

2022-11-14 18:33 UTC, Haelle commented on config/endpoints/3_insee_adresse_etablissement.yml
> +    - Portail GRU - Préremplissage
Justement l'adresse c'est pertinent pour les pré-remplissage

2022-11-14 18:33 UTC, Haelle commented on config/endpoints/3_insee_siege_social.yml
> +    - Portail GRU - Préremplissage
ça peut aller en optional

2022-11-14 18:33 UTC, Haelle commented on config/endpoints/3_insee_unites_legales.yml
> +    - Portail GRU - Préremplissage
ça peut aller en optional

2022-11-15 09:45 UTC, DorineLam commented on config/endpoints/3_insee_adresse_etablissement.yml
> +    - Portail GRU - Préremplissage
Oui mais ici on est sur de l'adresse comprenant celle des non-diffusibles ? Donc pas utilisable pour du pré-remplissage ?

2022-11-15 09:45 UTC, DorineLam commented on config/endpoints/3_insee_siege_social.yml
> +    - Portail GRU - Préremplissage
Idem ici j'ai interdit car on autoriserait alors du pré-remplissage avec du non-diffusibles

2022-11-15 09:46 UTC, DorineLam commented on config/endpoints/3_insee_unites_legales.yml
> +    - Portail GRU - Préremplissage
Idem ici j'ai interdit car on autoriserait alors du pré-remplissage avec du non-diffusibles

2022-11-15 11:02 UTC, merged