Table de correspondance précise entre les champs des API Insee
etalab/admin_api_entreprise pull request #774
Opened 2022-11-16 14:54 UTC by DorineLam

2022-11-16 14:55 UTC, DorineLam commented on config/locales/api_entreprise/documentation_entries.fr.yml
> +                  ![Description image](<%= image_path('Correspondance des champs - API V.2 Entreprises.pdf') %>)
@Samuelfaure j'ai ajouté deux fichiers PDF, mon objectif c'est que l'utilisateur puisse les télécharger... Je ne sais pas comment on intègre ça...
Ici j'ai essayé de faire comme pour une image,  je n'ai pas d'erreur mais ça ne fonctionne juste pas.


L'idée est de proposer le doc au format PDF et au format excel

2022-11-16 19:08 UTC, DorineLam commented
@Samuelfaure j'ai fini par intégré les tableaux en markdown.
J'aurai aimé quand même ajouter un lien de téléchargement du PDF et de l'excel.

Il y a aussi deux autres problèmes que je n'arrive pas à résoudre : 

- Le tableau ne se scroll pas à l'horizontal, c'est très gênant car le contenu dépasse
- Autre pb qui n'est pas lié à l'ajout des tables : le lien vers la partie etablissements ne marche pas. je ne sais pas pourquoi, et je ne retrouve plus les ancres.
- <img width="678" alt="Capture d’écran 2022-11-16 à 20 07 18" src="https://user-images.githubusercontent.com/46896006/202270856-6a6c5b65-3165-4d83-9db3-ca1be0a6d072.png">

Merci d'avance pour ton aide 🙏

2022-11-17 10:14 UTC, Samuelfaure commented on config/locales/api_entreprise/documentation_entries.fr.yml
> +                  ![Description image](<%= image_path('Correspondance des champs - API V.2 Entreprises.pdf') %>)
Bonne question pour les PDF - je sais pas quelles sont nos méthodes pour le téléchargement de fichiers statiques.

Est-ce qu'on fout juste ça en vrac quelque part sur le site @skelz0r ? Ou on utilise un bucket quelque part ou autre?

2022-11-17 10:14 UTC, Samuelfaure commented
@DorineLam Je m'en occupe cette semaine

2022-11-17 10:18 UTC, skelz0r commented on config/locales/api_entreprise/documentation_entries.fr.yml
> +                  ![Description image](<%= image_path('Correspondance des champs - API V.2 Entreprises.pdf') %>)
imo on met ça dans `app/assets/files` et on utilise le helper `asset_path` qui (je pense) va lookup dans l'ensemble des dossiers de `app/assets`

2022-11-17 10:21 UTC, skelz0r commented on config/locales/api_entreprise/documentation_entries.fr.yml
> +                  ![Description image](<%= image_path('Correspondance des champs - API V.2 Entreprises.pdf') %>)
sinon on introduit un `FilesController#download` et `FilesController#show` qui lookup dans un dossier `files` à la racine et on fait du `send_file` ( `disposition: :inline` pour `show` et `disposition: :attachment` pour `download`)

2022-12-12 11:10 UTC, Samuelfaure commented
@DorineLam Ah oui ça a du passer à la trappe... Heureusement mon autre PR est en cours de bouclage donc je vais pouvoir m'en occuper ici.

2022-12-15 10:48 UTC, Samuelfaure commented
@DorineLam OK il me reste plus qu'à mettre un lien pour le fichier Excel (je suis pas certain où tu veux ce lien exactement)

@skelz0r tu peux review

2022-12-15 10:53 UTC, Samuelfaure commented on app/controllers/api/files_controller.rb
> +  PUBLIC_FILES = Rails.public_path.join('files').children
Implémentation paranoïaque de ma part

2022-12-16 08:30 UTC, DorineLam commented
@Samuelfaure j'ai effectué mes modifs de formulation. C'est bon de mon côté.

2022-12-20 08:54 UTC, DorineLam commented
@Samuelfaure on peut merger ? ça sera de terminé

2022-12-20 08:55 UTC, Samuelfaure commented
@DorineLam Sorry, j'ai besoin d'une review et je pense qu'on est seuls sur le pont^^ ça va devoir attendre un peu

2022-12-27 10:21 UTC, skelz0r requested changes
C'est très compliqué pour quelque chose qui me semble assez simple pour le coup:

```ruby
class FilesController < ApplicationController
  rescue_from Errno::ENOENT, with: :not_found

  def show
    send_file file, disposition: :inline
  end

  def download
    send_file file, disposition: :attachment
  end

  private

  def not_found
    render plain: 'Not found', status: :not_found
  end

  def file
    File.open(file_path).path
  end
end
```

Autre point: pourquoi c'est dans API ?

2022-12-27 10:21 UTC, skelz0r commented on app/controllers/api/files_controller.rb
> +      render json: { error: 'Fichier non trouvé' }, status: :not_found
```suggestion
      render plain: 'Fichier non trouvé', status: :not_found
```

aucune raison de rendre un json ici

2022-12-27 10:21 UTC, skelz0r commented on app/controllers/api/files_controller.rb
> +      render json: { error: 'Fichier non trouvé' }, status: :not_found
```suggestion
      render plain: 'Fichier non trouvé', status: :not_found
```

idem qu'au dessus.

2022-12-27 10:21 UTC, skelz0r commented on app/controllers/api/files_controller.rb
> +    end
Clairement peu optimisé comme approche.

Pourquoi ne pas faire ça (un truc du genre) ?

```suggestion
    path = Rails.root.join('files', file_name)
    return unless File.exists?(path)
    path
```

2022-12-27 10:21 UTC, skelz0r commented on app/controllers/api/files_controller.rb
> +    end
Clairement peu optimisé comme approche.

Pourquoi ne pas faire ça (un truc du genre) ?

```suggestion
    path = Rails.root.join('files', file_name)
    return unless File.exists?(path)
    path
```

2022-12-27 10:21 UTC, skelz0r commented on spec/controllers/api/files_controller_spec.rb
> +    File.write(file_path, file_content)
du moment que tu cleanes y'a 0 souci (et dtf .. c'est pas possible autrement)

2022-12-27 10:21 UTC, skelz0r commented on app/controllers/api/files_controller.rb
> +  end
.. pourquoi ? c'est très brainfuck

2023-01-04 13:21 UTC, Samuelfaure commented
@skelz0r Mon approche "compliquée" c'est de recenser les fichiers présents dans `public_files/files` et sélectionner parmi eux; en effet comme on renvoie un fichier demandé par un user en param, j'ai peur que l'user puisse récup n'importe quoi sur notre serveur  (ex: je request '../../../../../../../etc/shadow`)

WDYT?

2023-01-04 13:33 UTC, Samuelfaure commented
@skelz0r MaJ la branche avec tes remarques

2023-01-04 13:35 UTC, skelz0r commented
> @skelz0r Mon approche "compliquée" c'est de recenser les fichiers présents dans `public_files/files` et sélectionner parmi eux; en effet comme on renvoie un fichier demandé par un user en param, j'ai peur que l'user puisse récup n'importe quoi sur notre serveur (ex: je request '../../../../../../../etc/shadow`)
> 
> WDYT?

Faut en effet filter sur le nom. Je ne suis pas sûr qu'un paramètre avec un `/` à l'intérieur fonctionne (car c'est une uri) (test en local voir ..?). 
Si cela fonctionne, je pense qu'il faut en effet restreindre avec une regex dans la route. Du genre on n'autorise que `(?:[a-zA-Z]|\.|\-|\_)`

2023-01-04 13:44 UTC, skelz0r commented
D'ailleurs tu devrais tester que tu ne peux pas read un fichier en dehors du folder (ex: `CGI::escape('../Gemfile')`) histoire d'être sûr.

2023-01-04 14:50 UTC, skelz0r requested changes
Pour moi faut tester qu'on ne peut pas accéder à un fichier en dehors du dossier autorisé.

De plus, je trouve que ton test d'appartenance au dossier autorisé est peu robuste: il ne fonctionne pas avec des sous-dossiers.

Je ferai plus ça:

```ruby
def authorized_file?
  File.exists?(file_full_path) &&
    file_full_path.starts_with?(authorized_folder_path)
end

def file_full_path
  File.expand_path(File.join(authorized_folder_path, params[:file]))
end

def authorized_folder_path
  Rails.root.join('public_files')
end
```

Faudrait aussi exclure les dossiers dans `authorized_file?` (ou alors catch `Errno::EISDIR`)

2023-01-04 14:50 UTC, skelz0r commented on app/controllers/files_controller.rb
> +  end
overkill ici

2023-01-04 14:50 UTC, skelz0r commented on app/controllers/files_controller.rb
> +  end
c'est brainfuck, c'est un file path ici (absolute d'ailleurs non ?)

2023-01-04 14:50 UTC, skelz0r commented on app/controllers/files_controller.rb
> +  rescue_from Errno::ENOENT, with: :not_found
ce rescue n'a plus lieu d'être vu le `before_action`

2023-01-04 14:50 UTC, skelz0r commented on spec/controllers/files_controller_spec.rb
> +RSpec.describe FilesController, type: :request do
Comme dit en commentaire, je testerai que tu ne puisses pas accéder à un fichier en dehors du dossier que tu veux.

2023-01-04 14:50 UTC, skelz0r commented on app/controllers/files_controller.rb
> +  def public_file_folder
pourquoi mettre ça dans `public` btw ?

2023-01-04 14:50 UTC, skelz0r commented on app/controllers/files_controller.rb
> +  end
c'est brainfuck ici, `authorized_file?` est mieux.

2023-01-04 14:50 UTC, skelz0r commented on app/controllers/files_controller.rb
> +  end
ça se remonte sur le `before_action` ça:

```ruby
before :not_found, unless: :authorized_file?
```

2023-01-04 15:05 UTC, Samuelfaure commented on app/controllers/files_controller.rb
> +  def public_file_folder
um parce que c'est public^^´ faudrait ptetre que je renomme le controller `PublicFilesController`

2023-01-04 15:07 UTC, Samuelfaure commented on spec/controllers/files_controller_spec.rb
> +RSpec.describe FilesController, type: :request do
J'ai oublié de préciser, mais si on tente ça lève une alerte "Route inexistante" - je peux test pour ça

2023-01-04 15:20 UTC, Samuelfaure commented
Je crois pas que ton `authorized_files?` réponde au problème:
```
def authorized_file?
  File.exists?(file_full_path) &&
    file_full_path.starts_with?(authorized_folder_path)
end
```

En effet, le fichier `public/files/../../../Gemfile` existe et commence bien avec `public/files`

2023-01-04 15:26 UTC, skelz0r commented
> Je crois pas que ton `authorized_files?` réponde au problème:
> 
> ```ruby
> def authorized_file?
>   File.exists?(file_full_path) &&
>     file_full_path.starts_with?(authorized_folder_path)
> end
> ```
> 
> En effet, le fichier `public/files/../../../Gemfile` existe et commence bien avec `public/files`



```ruby
3.2.0 (main):0 > File.expand_path(File.join(Rails.public_path, '../../Gemfile'))
=> "/Users/skelz0r/work/dinum/Gemfile"
```

🤷

2023-01-04 15:27 UTC, skelz0r commented on spec/controllers/files_controller_spec.rb
> +RSpec.describe FilesController, type: :request do
`..%2F..%2F..%2FGemfile` ne passe pas ? ça m'étonne.

2023-01-04 16:07 UTC, Samuelfaure commented
Okay mais y'a un AUTRE problème qui revient (jpp de ces trucs simples mais prise de tête) - on peut pas passer un argument avec un point apparemment (whatever.txt devient `whatever`)

En vrai je propose qu'on scrape tout et qu'on laisse juste les gens télécharger avec le lien "/files/nom-du-fichier.txt" (ça fonctionne)

2023-01-04 16:10 UTC, Samuelfaure commented
Ok j'ai tout scrap, si ça te convient je rebase puis je merge

2023-01-04 16:15 UTC, skelz0r commented
> Okay mais y'a un AUTRE problème qui revient (jpp de ces trucs simples mais prise de tête) - on peut pas passer un argument avec un point apparemment (whatever.txt devient whatever)

lol 

Ouais rebase merge 😅

2023-01-04 16:19 UTC, merged