Blog article non diffusibles
etalab/admin_api_entreprise pull request #808
Opened 2022-12-09 17:53 UTC by DorineLam

2022-12-12 10:49 UTC, Samuelfaure requested changes
Super boulot, quelques modifs et suggestions imho

2022-12-12 10:49 UTC, Samuelfaure commented on config/blog_posts/insee-non-diffusibles.md
> +On parle de "non-diffusibles" dans le cadre des entreprises et associations enregistrées au répertoire Sirene de l'Insee. Ce statut à un impact sur la diffusion des informations les concernant.
Ça existe les associations non diffusibles?

2022-12-12 10:49 UTC, Samuelfaure commented on config/blog_posts/insee-non-diffusibles.md
> +2. Auparavant, aucune donnée des unités légales et établissements "non-diffusibles" était diffusable publiquemen, bientôt, **certaines informations seront disponibles et en diffusion libre**, comme p
```suggestion
Auparavant, aucune donnée des unités légales et établissements "non-diffusibles" n'était diffusable publiquement
```

2022-12-12 10:49 UTC, Samuelfaure commented on config/blog_posts/insee-non-diffusibles.md
> +- État administratif (A VERIFIER)
Petit rappel ici pour le A VERIFIER

2022-12-12 10:49 UTC, Samuelfaure commented on config/blog_posts/insee-non-diffusibles.md
> +- le sigle (A VERIFIER)
Rappel A VERIFIER

2022-12-12 10:49 UTC, Samuelfaure commented on config/blog_posts/insee-non-diffusibles.md
> +API Entreprise met à disposition des administrations habilitées deux types d'API en ce qui concerne les données du répertoire Sirene&nbsp;:
Je rajouterais une phrase pour bien préciser que cela concerne UNIQUEMENT les API de l'INSEE et non pas les autres

2022-12-12 10:49 UTC, Samuelfaure commented on config/blog_posts/insee-non-diffusibles.md
> +Les API de l'API Entreprise sont généralement utilisées de deux façons&nbsp;:
Vu qu'on a plein de cas d'usage je remplacerais "généralement" par "souvent"

2022-12-12 10:49 UTC, Samuelfaure commented on config/blog_posts/insee-non-diffusibles.md
> +| **API avec les "diffusibles" et "non-diffusibles"**<br><span class='fr-badge fr-badge--sm fr-badge--white fr'>Données publiques **et protégées**</span><br><br/>  [API Données établissement - Insee]
Remplacer "non-diffusable" par "non-diffusible"

2022-12-12 10:49 UTC, Samuelfaure commented on config/blog_posts/insee-non-diffusibles.md
> +Parmi les clés renvoyées par les API ayant les non-diffusibles, il y a un champ `Diffusable commercialement` qui indique si l'entreprise est diffusible ou non. Vous pouvez donc filtrer les unités lég
```suggestion
Parmi les clés renvoyées par les API retournant les entités non-diffusibles, il y a un champ `Diffusable commercialement` qui indique si l'entreprise est diffusible ou non. Vous pouvez donc filtrer les unités légales selon qu'elles sont diffusibles ou non-diffusibles.
```

Je pense qu'il vaut mieux être super-clair quitte à être verbeux dans cet article

2022-12-12 10:49 UTC, Samuelfaure commented on config/blog_posts/insee-non-diffusibles.md
> +Parmi les clés renvoyées par les API ayant les non-diffusibles, il y a un champ `Diffusable commercialement` qui indique si l'entreprise est diffusible ou non. Vous pouvez donc filtrer les unités lég
Autre point, le champs est-il bien "Diffusable commercialement" et non pas "Diffusible commercialement" ? De plus il y a un espace dans cette clef ce qui me fait dire que ce n'est pas la clef exacte

2022-12-13 08:41 UTC, DorineLam commented on config/blog_posts/insee-non-diffusibles.md
> +On parle de "non-diffusibles" dans le cadre des entreprises et associations enregistrées au répertoire Sirene de l'Insee. Ce statut à un impact sur la diffusion des informations les concernant.
Hum tu as raison cette formulation est bizarre ...

2022-12-13 08:44 UTC, DorineLam commented on config/blog_posts/insee-non-diffusibles.md
> +On parle de "non-diffusibles" dans le cadre des entreprises et associations enregistrées au répertoire Sirene de l'Insee. Ce statut à un impact sur la diffusion des informations les concernant.
J'ai changé par ça : 

> **Qu'est qu'une unité légale ou un établissement non-diffusible ?**
> On parle de "non-diffusibles" dans le cadre des entités enregistrées au répertoire Sirene de l'Insee.

2022-12-13 08:52 UTC, DorineLam commented on config/blog_posts/insee-non-diffusibles.md
> +API Entreprise met à disposition des administrations habilitées deux types d'API en ce qui concerne les données du répertoire Sirene&nbsp;:
J'ai ajouté : 

> API Entreprise met à disposition des administrations habilitées deux types d'API en ce qui concerne **les données issues de l'Insee** et du répertoire Sirene

2022-12-13 08:59 UTC, DorineLam commented on config/blog_posts/insee-non-diffusibles.md
> +| **API avec les "diffusibles" et "non-diffusibles"**<br><span class='fr-badge fr-badge--sm fr-badge--white fr'>Données publiques **et protégées**</span><br><br/>  [API Données établissement - Insee]
@Samuelfaure je n'ai pas compris où est-ce que tu souhaites que je remplace ?

2022-12-13 09:44 UTC, Samuelfaure commented on config/blog_posts/insee-non-diffusibles.md
> +| **API avec les "diffusibles" et "non-diffusibles"**<br><span class='fr-badge fr-badge--sm fr-badge--white fr'>Données publiques **et protégées**</span><br><br/>  [API Données établissement - Insee]
Fin de la ligne 75 y´a écrit `Il n'y a pas de contre-indication légale à utiliser cette API en back-office, en revanche vos agents habilités n'auront pas les données des "non-diffusables`

2022-12-23 09:42 UTC, DorineLam commented
@Samuelfaure j'ai pris en compte les retours de l'Insee, je pense qu'on peut merger cet article

2022-12-23 10:29 UTC, merged