[Page accueil] Préciser la mission d'API Entreprise
etalab/admin_api_entreprise pull request #821
Opened 2022-12-16 11:51 UTC by DorineLam

2022-12-20 14:18 UTC, Charlottecho approved these changes
* "title_end: <br>dans le traitement des démarches 🗂 !" : Le titre doit indiquer qui cela concerne et le service proposé . 
Du coup , je proposerai : " Vous êtes une administration ? Vous traitez des démarches destinées aux entreprises / associations ? API entreprise va vous faire gagner du temps !
Pour le reste , j'aime bien ce que t'as fait : la disposition type possiblité d'avoir" accès direct aux données" en dessous + "API entreprise ca sert a quoi" ? + cas d'usage en dessous 
* "1 seul interlocuteur à 1 seul endroit" i/o "un seul ...": + percutant

2022-12-20 15:35 UTC, DorineLam commented
> * "title_end: dans le traitement des démarches 🗂 !" : Le titre doit indiquer qui cela concerne et le service proposé .
>       Du coup , je proposerai : " Vous êtes une administration ? Vous traitez des démarches destinées aux entreprises / associations ? API entreprise va vous faire gagner du temps !
>       Pour le reste , j'aime bien ce que t'as fait : la disposition type possiblité d'avoir" accès direct aux données" en dessous + "API entreprise ca sert a quoi" ? + cas d'usage en dessous
> 
>     * "1 seul interlocuteur à 1 seul endroit" i/o "un seul ...": + percutant

Merci @Charlottecho 
J'ai essayé de rester fidèle à ton idée mais la phrase est trop longue telle que tu l'as proposée.

Voici le résultat : 

![image](https://user-images.githubusercontent.com/46896006/208703473-eb953466-8743-4c07-9961-dc9953e0a40e.png)

2022-12-21 14:00 UTC, Samuelfaure requested changes
Super taff! Peux-tu juste changer les références à I18n dans les vues:

```
I18n.t('blabla')
```

```
t('blabla')
```

En effet l'objet I18n est accessible globalement dans les vues

Dès que c'est fait on peut merge :)

2022-12-21 14:02 UTC, Samuelfaure commented
Autre correction: un test échoue car les clefs suivantes sont inutilisées:

```
|   fr   | api_entreprise.pages.home.section_how.cards.editeur.description                 | Éditeurs, intégrez API Entreprise pour vos clients publics |
|   fr   | api_entreprise.pages.home.section_how.cards.fraude.description                  | Accéder rapidement aux informations-clés                   |
|   fr   | api_entreprise.pages.home.section_how.cards.marches_publics.description         | Faciliter la candidature et l'instruction                  |
|   fr   | api_entreprise.pages.home.section_how.cards.portail_gru.description             | Préremplir et personnaliser les formulaires                |
|   fr   | api_entreprise.pages.home.section_how.cards.portail_gru_instruction.description | Faciliter l'instruction des démarches                      |
|   fr   | api_entreprise.pages.home.section_how.cards.subventions.description             | Faciliter le dépôt et l'instruction           
```

Il faudrait les supprimer

2022-12-21 14:19 UTC, DorineLam commented
> Super taff! Peux-tu juste changer les références à I18n dans les vues:
> 
> ```
> I18n.t('blabla')
> ```
> 
> ```
> t('blabla')
> ```
> 
> En effet l'objet I18n est accessible globalement dans les vues
> 
> Dès que c'est fait on peut merge :)

Je n'ai pas compris ce que je dois faire exactement... Est-ce que tu peux me donner un exemple dans le code ?

2022-12-21 14:23 UTC, Samuelfaure commented
![image](https://user-images.githubusercontent.com/14159757/208927271-f58a8031-72c6-4e57-9d2f-7930b1f492f1.png)
Graphiquement j'ai quelques problèmes sur mon grand écran: 

- ça dépasse les marges sur le coté
- faudrait que les cases soient de la même hauteur (donner un `min-height` peut marcher)
- leur largeur est un peu grosse (je réduirais la largeur)

2022-12-21 14:41 UTC, Samuelfaure commented
@DorineLam C'est bon de mon coté pour les changements graphiques! En effet ça s'est réglé tout seul

2022-12-21 15:06 UTC, DorineLam commented
> BTW sur Github tu ne peux pas écrire des balises (relis ton dernier commentaire), tu dois mettre dans des `

Merci pour l'info je ne savais pas  !!

2022-12-21 15:07 UTC, DorineLam commented
Est-ce que c'est bon pour les `I18n.t('blabla')` ?

2022-12-21 15:11 UTC, Samuelfaure commented
@DorineLam Je le vois pas corrigé

J'ai écris une suggestion pour un des deux

2022-12-21 15:15 UTC, Samuelfaure commented
@DorineLam My bad mes commentaires étaient Pending - pas visibles pour toi! Je viens de les valider

2022-12-21 15:39 UTC, DorineLam commented
Normalement c'est pris en compte :) @Samuelfaure

2022-12-21 16:11 UTC, merged