Enhancement/modelized use cases
etalab/admin_api_entreprise pull request #934
Opened 2023-02-27 17:38 UTC by Un3x

Il faut probablement adapter certaines parties pour que ce soit un peu plus 'the rails way', je me suis inspiré de ce qui est fait ailleurs donc ca devrait pas être trop gros.

Vu l'existant j'ai choisi de nommer le modèle `Cas_Usage` j'ai longtemps hésité avec `Use_case`. Normalement je serais parti sur du full anglais, mais là j'avoue que je savais pas trop comme il y a les 2 dans l'app.

2023-02-27 18:12 UTC, skelz0r requested changes
Ça mérite encore un peu de refactor ici.

En l'état t'as juste wrap dans un modèle, en regardant l'issue initiale (que tu n'as pas référencé d'ailleurs) https://github.com/etalab/admin_api_entreprise/issues/867 tu as taclé le point 1. (partiellement le point 3., manque les tests du modèle ici)

Le point principal de mon ticket était surtout de ne pas faire de `Model.all` dans les vues ^^

Au passage en voyant la gueule de certains contenu, je pense qu'on n'a pas forcément besoin de mettre ça dans le modèle en tant que tel, genre `introduction`/`roles`/`use_case_examples`/`users`

En ce qui concerne les relations, je vois qu'on a des uids de endpoint dans `comments_endpoints` on pourrait potentiellement exploiter pour refactor (voir même tester l'intégrité dans le modèle, genre si un uid n'existe pas => ça lève une erreur. Peut-être dans une autre itération, mais ce sont aussi des pistes de pourquoi c'est intéressant de transformer cette ressource en modèle.

2023-02-27 18:12 UTC, skelz0r commented on app/views/api_entreprise/cas_usages/_others.html.erb
> +  <% CasUsage.all { |item| item.cas_usage_key == current_use_case }.sample(3).each do |use_case| %>
1. Ce code ne fonctionne pas (il manque un `.reject`)
2. C'est bien dégueu .. 

Pour 2., dans le controller:

```ruby
def show
  @cas_usage = CasUsage.find(params[:uid])
  @other_cas_usages = CasUsage.all - @cas_usage
end
```

et dans la vue => `@other_cas_usages.each`

On ne manipule pas des recherches d'objets dans la vue.

De plus pour une question de consistance => `use_case` => `cas_usage`

2023-02-28 07:42 UTC, Un3x commented
C'est vrai que j'ai un peu pris littéralement la demande 'reprendre les usecases en modèle'.

2023-02-28 13:14 UTC, Un3x commented
J'viens de push en traitant un certains nombre de point - littéralement les points lié à des problèmes de qualité sur ce que j'avais fourni.

Il reste principalement le sujet des endpoints et des usages moches dans les vues

2023-02-28 13:27 UTC, skelz0r reviewed
On va dire que c'est good enough (modulo mes 2/3 remarques), y'aura une repasse (soon) sur tout ça quand on intégrera le site vitrine d'API Particulier ici.

2023-02-28 13:27 UTC, skelz0r commented on app/controllers/api_entreprise/cas_usages_controller.rb
> +  rescue I18n::MissingTranslationData, ActiveRecord::RecordNotFound
```suggestion
  rescue ActiveRecord::RecordNotFound
```

A priori ici ça suffit

2023-02-28 13:27 UTC, skelz0r commented on app/views/api_entreprise/cas_usages/_list-api.html.erb
> -            <% if endpoint.use_cases&.include?(@data[:name]) %>
> A minima je pense qu'un helper serait mieux.

Toujours valide ici.

2023-02-28 13:27 UTC, skelz0r commented on spec/controllers/api_entreprise/cas_usages_controller_spec.rb
> +RSpec.describe APIEntreprise::CasUsagesController do
Ce n'est pas bien grave, mais ici un test de feature aurait été plus consistant avec le reste de la codebase (mais honnêtement ça peut rester)

2023-02-28 14:56 UTC, Un3x commented on app/views/api_entreprise/cas_usages/_list-api.html.erb
> -            <% if endpoint.use_cases&.include?(@data[:name]) %>
Pour le moment j'ai ignoré un peu cette partie. Je me demande si ca vaut pas le coup de faire une 2nde PR dédiée ?

Imo la solution du helper ca cache la misère. Je serais plutot partie sur le loading des cas_usages dans les endpoints (d'où ma question) --^

2023-02-28 15:02 UTC, skelz0r commented
> Typiquement sur ce que tu as remonté @skelz0r
> 
> ```
> <% if endpoint.use_cases&.include?(@data[:name]) %>
> ```
> 
> Il y en a d'autre dans le code, et qui sont aussi à reprendre (et pas que les vues).
> 
> genre dans endpoint.rb
> 
> ```
>   def self.without_forbidden_use_case(use_case)
>     all.reject { |endpoint| endpoint.use_cases_forbidden&.include?(use_case) }
>   end
> ```
> 
> Qui est le même genre de code, mais je suis pas convaincu de l'utilité de la présence de ca dans l'entitée (en l'occurence, celui là n'est pas utilisé).

Dans le meilleur des mondes cela devrait être un décorateur ou une facade (imo le décorateur est une meilleure approche). En tout cas je préfère que ça soit dans du code ruby que dans de la vue, c'est refactorisé plus rapidement que dans la vue.

Btw si la méthode `without_forbidden_use_case` n'est pas utilisée tu peux la remove dans un scout commit ;)

2023-02-28 15:03 UTC, skelz0r commented on app/views/api_entreprise/cas_usages/_list-api.html.erb
> -            <% if endpoint.use_cases&.include?(@data[:name]) %>
Ça me va que ça se fasse dans une 2e PR

> Imo la solution du helper ca cache la misère.

oui

2023-02-28 16:33 UTC, Un3x commented on app/models/endpoint.rb
> +  def self.all_decorated
Je suis pas amoureux de ce nommage

2023-03-06 09:21 UTC, skelz0r requested changes
Y'a 2 `all` dans des vues que je remonterai dans les controller + le refactor du decorator. 

Dès que c'est fixé, tu peux merger.

2023-03-06 09:21 UTC, skelz0r commented on app/decorators/endpoint_decorator.rb
> +  end
Ça peut encore se refactor ici:

```suggestion
  def cas_usage_to_icon(cas_usage_name)
    cas_usge_icon_tag('#1f8d49')if use_case?(cas_usage_name)
  end

  def cas_usage_to_icon_optionnal(cas_usage_name)
    cas_usge_icon_tag('#1f8d49') if use_case_optionnal?(cas_usage_name)
  end

  def cas_usage_to_icon_forbidden(cas_usage_name)
    cas_usge_icon_tag('#d64d00') if use_case_forbidden?(cas_usage_name)
  end
  
  def cas_usage_icon_tag(color)
    "<span style=\"color:#{color}\" class=\"fr-icon-close-circle-line\" aria-hidden=\"true\"></span>"
  end
```

2023-03-06 09:21 UTC, skelz0r commented on app/models/endpoint.rb
> +  def self.all_decorated
Non plus, et je vois que c'est utiliser dans une vue d'une façon qui ne me plaît pas non plus.

Je supprimerai cette méthode et j'irais directement dans le controller faire ça:

```ruby
@active_endpoints = EndpointDecorator.decorate_collection(Endpoint.all.reject(&:deprecated))
```

2023-03-06 09:21 UTC, skelz0r commented on app/views/api_entreprise/cas_usages/index.html.erb
> +    <% CasUsage.all.each do |cas_usage| %>
Je remonterai ceci dans le controller

2023-03-06 16:15 UTC, skelz0r approved these changes

2023-03-07 08:04 UTC, merged