Defining priority on valid token
etalab/admin_api_entreprise pull request #937
Opened 2023-03-01 10:49 UTC by Un3x

closes https://github.com/etalab/admin_api_entreprise/issues/892

2023-03-01 10:52 UTC, Un3x commented on app/models/authorization_request.rb
> +  has_one :valid_token, -> { where(blacklisted: false, archived: false) },
Ici j'ai repris la définition de 'token actif' depuis la classe token. 

Alors je sais pas si c'est un bug ou intentionnel mais on peut visiblement avoir un token actif qui est expiré (ca me semble pas logique mais bon).

2023-03-06 13:20 UTC, Un3x commented
Petit warning sur cette PR.

Il y a assez peu de code métier mais quand même pas mal d'impact vu comment les tests ont pété.
Je m'attends à ce qu'il y ai des modifs niveau "rails way", mais je pense qu'il faut bien check les impacts métiers parce que je suis pas convaincu de tout.

Genre je sais pas si c'est pertinent de définir un valid_token dans la classe contact par exemple.

2023-03-06 14:01 UTC, skelz0r requested changes
> Je m'attends à ce qu'il y ai des modifs niveau "rails way", mais je pense qu'il faut bien check les impacts métiers parce que je suis pas convaincu de tout.

Il y a en effet le petit `has_one`

> Genre je sais pas si c'est pertinent de définir un valid_token dans la classe contact par exemple.

Alors ça l'est parce que un user au sens de applicatif web (i.e. qui peut s'authentifier sur l'application) est soit un contact soit un user (oui, c'est fucked up mais c'est de la dette qui va, je l'espère, sauter quand on aura un login full MonComptePro).

Les contacts peuvent lister leurs jetons (les vues sont partagées entre user et contact), donc il faut que ça soit "iso" en terme de relation sur la vue.

2023-03-06 14:45 UTC, Un3x commented on app/models/authorization_request.rb
> +  end
Ben justement, ca, ca renvoi nil systématiquement. C'est la question que j'avais posé plus haut. On a regardé avec Samuel pourquoi ca faisait ca et on a pas trouvé

2023-03-06 14:51 UTC, skelz0r commented on app/models/authorization_request.rb
> +  def valid_token
Faut inspecter la différence en sql (soit dans la console soit dans les logs de tests), je ne vois pas pourquoi ça ne fonctionne pas, doit y avoir une subtilité du coup.

2023-03-06 14:52 UTC, skelz0r commented on app/models/authorization_request.rb
> +  end
Je close ici pour discuter plus haut.

2023-03-06 14:54 UTC, skelz0r commented on spec/interactors/datapass_webhook/archive_previous_token_spec.rb
> +  let(:tokens) { [create(:token)] }
Dans ce cas précis voir mon commentaire sur la même ligne.

2023-03-06 14:59 UTC, Un3x commented on app/interactors/datapass_webhook/create_token.rb
> -    token = create_token
Ouais alors cette syntax particulière marche pas mais ok.

Y a eu des changements aussi parce que Rubocop était pas content de la complexité de `call`

2023-03-06 15:00 UTC, skelz0r commented on app/models/authorization_request.rb
> +  def valid_token
```
   28:     it 'returns a valid token' do
   29:       expect(authorization_request.tokens.first.blacklisted?).to be true
   30:       byebug
=> 31:       expect(authorization_request.valid_token).to be_present
   32:       expect(authorization_request.token.id).to eq(authorization_request.valid_token.id)
   33:     end
   34:   end
   35: end
(byebug) authorization_request.valid_token
nil
(byebug) authorization_request.reload.valid_token
#<Token id: "be3985b9-fdbe-4751-8edb-3781f8a8c1b8", iat: 1678114665, created_at: "2023-03-06 15:57:45.692841000 +0100", updated_at: "2023-03-06 15:57:45.700171000 +0100", exp: 1725631065, version: "1.0", blacklisted: false, days_left_notification_sent: [], archived: false, temp_use_case: nil, authorization_request_id: "12342", authorization_request_model_id: "cb4c5691-00a6-4e1e-94e9-b895ec7c89ae", extra_info: {}>
```

Le souci est dans la factory =>

```ruby
    trait :with_multiple_tokens_one_valid do
      after(:build) do |authorization_request|
        authorization_request.tokens << build(token, :blacklisted, :not_archived, authorization_request:)
        authorization_request.tokens << build(token, :not_blacklisted, :not_archived, authorization_request:)
      end
    end
```

L'ancienne version ne fait pas bien le lien au moment du commit. Une autre approche est de reload post create dans la factory.

2023-03-06 15:01 UTC, Un3x commented on spec/interactors/datapass_webhook/archive_previous_token_spec.rb
> +  let(:tokens) { [create(:token)] }
Ok plus consistant avec ce que j'ai fais ailleurs.

2023-03-06 15:03 UTC, Un3x commented on spec/models/authorization_request_spec.rb
> +      expect(authorization_request.tokens.first.blacklisted?).to be true
mieux

2023-03-06 15:23 UTC, Un3x commented on app/models/contact.rb
> +  delegate :valid_token, to: :authorization_request
Ouais en fait, la première def c'est celle que je voulais faire, mais elle ne fonctionne que s'il y avait un valid_token en tant qu'associations ou attribut pas si c'est une méthode (mon fall back).

Du coup je l'ai écrasé juste en dessous pour patcher temporairement en attendant de savoir pourquoi.

2023-03-06 16:10 UTC, skelz0r commented on app/interactors/datapass_webhook/create_token.rb
> +    create_token
Ce code pour moi est faux:

A ce stade dans le code il y a potentiellement 2 "valid" token. Il faut **explicitement** manipuler le jeton qu'on vient de créer.

J'ai le code de cette classe sous les yeux sur develop, et honnêtement je ne comprends pas pourquoi il y a tant de modification 🤷 La seule méthode a modifier est `create_token`

Il y a sur develop:

```ruby
  def create_token
    authorization_request.create_token(
      Token.default_create_params.merge(
        authorization_request_id: authorization_request.external_id
      ).merge(
        context.token_create_extra_params || {}
      )
    )
  end
```

Pourquoi ça ce n'est pas valide ?

```ruby
  def create_token
    authorization_request.tokens.create(
      Token.default_create_params.merge(
        authorization_request_id: authorization_request.external_id
      ).merge(
        context.token_create_extra_params || {}
      )
    )
  end
```

2023-03-07 08:00 UTC, Un3x commented on app/interactors/datapass_webhook/create_token.rb
> +    create_token
Oui ca marche aussi, j'ai fixé et remis comme ca, mais j'avoue que je comprends pas la diff entre ce que tu proposes et ce que j'ai fais ?

Il y avait plus de modifs parce que j'avais eu des erreur Rubocop sur la complexité cyclomatique de la fonction `call` donc j'ai juste encapsulé le contexte (j'ai remis comme avant du coup)

2023-03-07 08:58 UTC, skelz0r commented on app/interactors/datapass_webhook/create_token.rb
> +    create_token
La version d'avant il y avait un `authorization_request.tokens.first` utilisé. Ceci n'est pas déterministe.

Je concède qu'en pratique cela fonctionne (car le sgbd postgresql sort par ordre d'insertion de manière général) mais c'est le risque d'avoir des side effects indésirables (par exemple si on décide de changer l'ordre pour X/Y raison, ou comment la relation se load via un overide d'accesseur). Cette justification, couplé au fait que la modification que je propose (et que tu as adopté) est minime (donc moins de complexity change sur le fichier) fait que je trouve ça mieux de faire ça de manière simple.

2023-03-07 10:11 UTC, Un3x commented on app/interactors/datapass_webhook/create_token.rb
> +    create_token
Ouais. En fait avec ma modif, j'avais un retour Rubocop\AbcSize et du coup j'ai du faire plus de modif pour gérer la complexité de la méthode.

Mais du coup, c'est effectivement mieux comme ca.

2023-03-07 15:11 UTC, Un3x commented
@Samuelfaure Vu que t'as suivi la discussion je te laisse check le dernier commit qui reprend la notion de token valid.

Je me suis fais un petit kiff avec la définition en utilisant les scope déjà défini dans token, j'avoue que mon cerveau a explosé quand j'ai pigé que rails pouvait faire ca.

2023-03-08 10:07 UTC, Samuelfaure commented
Oublié de répondre mais j'ai bien regardé hier thk.

2023-03-08 13:16 UTC, merged