[Draft] Integration du nouveau status datapass revoked
etalab/admin_api_entreprise pull request #949
Opened 2023-03-07 13:13 UTC by Un3x

2023-03-07 14:18 UTC, Un3x commented
Je suis pas ultra convaincu de ce que j'ai fais.

J'ai fais un interactor vite fait pour faire genre on a un process minimal, mais j'ai fais exprès de pas le mettre dans l'organizer des api pour voir le comportement du test.

Du coup, si j'ai bon, on renvoi bien une 200 sur l'event `revoke`, et on applique juste les interactors générique qui vont avec la payload datapass.

2023-03-07 20:18 UTC, skelz0r reviewed
En effet là ton code en l'état est branché nul part et ne fait .. rien 😂

Ma reco dans un premier temps: 

1. Fait un test sur `DatapassWebhook::APIEntreprise` avec le status `revoked` et vérifie que ça ne lève pas d'exception 
2. Ajoute l'i18n du status dans les locales

2023-03-13 09:13 UTC, Samuelfaure commented
OK pour la PR à priori, mais vu qu'on teste pour vérifier que ça ne lève pas d'exception il faudrait peut-être rajouter un petit test qui teste directement que ça ne lève pas d'exception (si ça success on sait que ça ne lève pas mais juste pour la clarté sémantique)

2023-03-13 09:57 UTC, skelz0r approved these changes
Contrairement à Samuel pour moi tester que c'est un success me suffit, vu qu'implicitement on sait que ça ne lève pas d'erreur.

2023-03-13 10:34 UTC, Un3x commented
Ok bon, vu que vous êtes pas d'accord, battez vous.

Vu qu'on a décidé de ne pas faire de traitement pour les 3 events revoke - archive - delete, j'ai rajouté un test pour les 3 (avec success et raise_error) et j'ai refs les différents tickets dedans pour clore le tout.

2023-03-13 10:44 UTC, skelz0r requested changes
> Vu qu'on a décidé de ne pas faire de traitement pour les 3 events revoke - archive - delete

Alors ici non, je t'ai fait ouvrir des tickets justement pour traiter au cas par cas :D 

Donc pour moi ici il faut changer le message de commit pour ne pas close les tickets mais juste les référencer.

2023-03-13 11:12 UTC, Samuelfaure commented
> Ok bon, vu que vous êtes pas d'accord, battez vous.

Dans le doute quand on est pas d'accord, l'expérience passe avant la beauté donc tu peux suivre Loïc

2023-03-13 11:15 UTC, skelz0r commented
> > Ok bon, vu que vous êtes pas d'accord, battez vous.
> 
> Dans le doute quand on est pas d'accord, l'expérience passe avant la beauté donc tu peux suivre Loïc

C'est tellement du détail que franchement balec en vrai ^^

2023-03-13 13:52 UTC, Un3x commented
Je vais attaquer le traitement du archived du coup

2023-03-13 13:58 UTC, skelz0r requested changes
Je vais encore être relou, mais pour moi on ne solve pas réellement le ticket https://github.com/etalab/admin_api_entreprise/issues/382 .. je mettrai seulement un ref et non un close.

2023-03-13 14:53 UTC, skelz0r approved these changes
c'est ok pour moi, y'a juste les tests qui ne passent pas (?)

2023-03-13 14:59 UTC, Un3x commented
J'ai rebase et c'est ok

2023-03-13 15:07 UTC, merged