DatapassWebhook::ArchiveCurrentToken Initialisation
etalab/admin_api_entreprise pull request #957
Opened 2023-03-13 14:44 UTC by Un3x

closes https://github.com/etalab/admin_api_entreprise/issues/947

Initialized archive event handler

2023-03-13 14:52 UTC, skelz0r commented
Honnêtement là pour moi un soft delete c'est un blacklist du jeton. En l'état on ne peut pas blacklister un jeton de manière automatisé.. donc le mieux je pense c'est de shoot un email sur equipe@ quand on a 'archive'.

2023-03-13 15:00 UTC, Un3x commented
Ben de ce que j'avais compris des discussions,

2023-03-13 15:04 UTC, skelz0r commented
Honnêtement .. je ne sais pas. C'est pas clair pour moi quand on doit archiver et quand on doit revoke 🤷

Faut aller demander à DataPass.

2023-03-14 11:59 UTC, Samuelfaure requested changes
le "if -> unless" j'y tiens un peu, le reste c'est du bonus

2023-03-14 11:59 UTC, Samuelfaure commented on app/interactors/datapass_webhook/archive_current_token.rb
> +    return if %w[archive].exclude?(context.event)
Je trouve cette formulation plus claire:
```suggestion
    return unless %w[archive].include?(context.event)
```

2023-03-14 11:59 UTC, Samuelfaure commented on spec/interactors/datapass_webhook/archive_current_token_spec.rb
> +  context 'when event is not archive' do
je chipote un peu mais:


```suggestion
  context "when event is not 'archive'" do
```

2023-03-14 11:59 UTC, Samuelfaure commented on spec/interactors/datapass_webhook/archive_current_token_spec.rb
> +  context 'when event is archive' do
```suggestion
  context "when event is 'archive'" do
```

2023-03-15 07:46 UTC, Samuelfaure commented on app/interactors/datapass_webhook/archive_current_token.rb
> +    return if %w[archive].exclude?(context.event)
bon si c'est iso ça fait une bonne raison

2023-09-13 08:10 UTC, closed without merging