Site API Particulier
etalab/admin_api_entreprise pull request #987
Opened 2023-04-03 13:18 UTC by skelz0r

* [x] "Finaliser" la HP
* [x] Finaliser la page développeur
* [x] Endpoints -> ~ok index, i18n sur show + parameters à harden sur chaque fiches
* [x] Endpoint#example
* [x] Page documentation développeur (minimal)
* ML Cas usages
* [x] Nav bar
* [x] Tests basic

Post review:

* [x] Nav bar -> le Demander un accès n'est pas à droite
* [x] Developers: recherche

2023-04-06 10:37 UTC, skelz0r commented
allez hop() https://sandbox.particulier.api.gouv.fr/catalogue

@DorineLam techniquement c'est prêt

Comme évoqué de vive voix, il manque:

* les cas d'usages: faut refaire une passe dans les endpoints et nettoyer ça + mettre les pages
* la FAQ

J'ai fait un peu de clean sur les endpoints de API Part vu qu'il y a pas mal de choses qui ne sont pas utilisés par rapport à API Entreprise

2023-04-06 10:38 UTC, skelz0r commented
@Un3x @Samuelfaure ça se lit commit par commit, globalement y'a rien de bien compliqué, c'est juste de l'implémentation des classes abstraites et créations des controllers/routes, les vues sont pas mal partagées en vrai.

Y'a des "grosses" modifs sur les endpoints

2023-04-11 09:26 UTC, Un3x reviewed
Okay pavé incoming.

Ras au niveau du code c'est propre impecc.

Par contre, il y a quelques éléments un peu étonnant dans l'interface et comme je sais pas comment tu as fait ton découpage je me permets d'étaler ici ce que j'ai remarqué, pas forcément à traiter ici IMO: 

UI/UX
* Header HP - Pas de status des API et pas de FAQ ? J'ai vu que en prod il y avait le "Une question ??" 
* Bandeau Catalogue HP - Demander un accès à aligner sur la droite pour être iso ApiEntreprise
* Bandeau Catalogue HP - Pas d'onglet cas d'usage ?
* Footer : Les liens plans du site et données personnelles sont ko coté part et entreprise (Et en prod aussi)
* Je suppose qu'il n'y a pas de newletter API-part mais au cas ou c'est posé là

Catalogue des API : 
* Pas de recherche algolia ? J'imagine que c'est volontaire, je me posais la questions de la pertinence d'unifier le mécanisme et de le faire fonctionner même si on a que 4 api aujourd'hui. Pas forcément à traiter ici.
* Idem Espace développeur : Pas de recherche algolia. Pour le coup ici ca semble pertinent de le mettre mais t'as peut être prévu en next step.
*

2023-04-11 09:37 UTC, skelz0r commented
> * Header HP - Pas de status des API et pas de FAQ ? J'ai vu que en prod il y avait le "Une question ??"

Status des API: on verra plus tard (on a rien dtf)
FAQ: oui ça va venir, clairement pas important pour shipper maintenant

> * Bandeau Catalogue HP - Demander un accès à aligner sur la droite pour être iso ApiEntreprise

Indeed, j'avais pas remarqué, c'est le même code pourtant 🤷

> * Bandeau Catalogue HP - Pas d'onglet cas d'usage ?

Je manquais d'infos pour ship ça, ça viendra plus tard

> * Footer : Les liens plans du site et données personnelles sont ko coté part et entreprise (Et en prod aussi)

Lol, ça peut ouvrir des tickets ici du coup (imo ça va flip les liens).

> * Je suppose qu'il n'y a pas de newletter API-part mais au cas ou c'est posé là

Aucune idée, si c'est important on me le dira.

> Catalogue des API :
> 
> * Pas de recherche algolia ? J'imagine que c'est volontaire, je me posais la questions de la pertinence d'unifier le mécanisme et de le faire fonctionner même si on a que 4 api aujourd'hui. Pas forcément à traiter ici.

Oui c'est volontaire, y'a 0 raison de mettre une recherche avec 4 APIs. C'est la même mécanique cependant (j'indexe le contenu aussi), la seule différence c'est que je n'ai pas appliqué le controller stimulus.

> * Idem Espace développeur : Pas de recherche algolia. Pour le coup ici ca semble pertinent de le mettre mais t'as peut être prévu en next step.

Là en effet c'est un oubli.

J'update ma todo liste plus haut.

2023-04-11 10:00 UTC, Samuelfaure requested changes
Petit oubli de lignes à supprimer sinon c'est good

2023-04-11 10:00 UTC, Samuelfaure commented on config/locales/api_particulier/fr.yml
> +        #   no_maintenance: "Disponible 24h/24 et 7j/7"
Oubli ici

2023-04-11 10:01 UTC, Samuelfaure commented on app/views/shared/api_particulier/header/_menu.html.erb
> +
A supprimer aussi

2023-04-11 14:07 UTC, merged